### ISSUE TITLE
adminserver V1.70 initialization failed 

### ISSUE THREAD

**Issue by D-PENG** [goharbor/harbor#6672] opened 2019-01-02 06:45 UTC
>```
> 2019-01-02T06:36:15Z [INFO] initializing system configurations...
> 2019-01-02T06:36:15Z [INFO] Registering database: type-PostgreSQL host-my-release-harbor-database port-5432 databse-registry sslmode-"disable"
> 2019-01-02T06:36:15Z [INFO] Register database completed
> 2019-01-02T06:36:15Z [INFO] Upgrading schema for pgsql ...
> 2019-01-02T06:36:15Z [ERROR] [pgsql.go:112]: Failed to upgrade schema, error: "Dirty database version 1. Fix and force version."
> 2019-01-02T06:36:15Z [FATAL] [main.go:45]: failed to initialize the system: Dirty database version 1. Fix and force version.
>```
Database is new, PVC is also new,why?

**Comment by chamhaw** [comment] 2019-01-08 12:23
+1

**Comment by omegazeng** [comment] 2019-03-07 16:43
same issue
kubenetes 1.13.4
harbor helm chart 1.0.0
```bash
kubectl get po -n harbor
NAME                                                     READY   STATUS             RESTARTS   AGE
awesome-lionfish-harbor-adminserver-79fd97c87b-zt9vz     0/1     CrashLoopBackOff   27         118m
awesome-lionfish-harbor-chartmuseum-778b4cb6c4-m7pqc     1/1     Running            0          4h52m
awesome-lionfish-harbor-clair-59ff96c975-88r95           1/1     Running            12         4h52m
awesome-lionfish-harbor-core-7d8d45cd48-vb98c            0/1     CrashLoopBackOff   32         117m
awesome-lionfish-harbor-database-0                       1/1     Running            2          4h52m
awesome-lionfish-harbor-jobservice-97c8f9585-v7qzq       0/1     Running            25         119m
awesome-lionfish-harbor-notary-server-7ddd974895-4h5xq   1/1     Running            2          4h52m
awesome-lionfish-harbor-notary-signer-b8fdd6748-gzzsx    1/1     Running            2          4h52m
awesome-lionfish-harbor-portal-5f864688b-7qlp6           1/1     Running            0          4h52m
awesome-lionfish-harbor-redis-0                          1/1     Running            0          4h52m
awesome-lionfish-harbor-registry-cdcfdc59-lkxfc          2/2     Running            0          4h52m
```
```
2019-03-07T16:38:02Z [INFO] initializing system configurations...
2019-03-07T16:38:02Z [INFO] Registering database: type-PostgreSQL host-awesome-lionfish-harbor-database port-5432 databse-registry sslmode-"disable"
2019-03-07T16:38:02Z [INFO] Register database completed
2019-03-07T16:38:02Z [INFO] Upgrading schema for pgsql ...
2019-03-07T16:38:02Z [ERROR] [pgsql.go:112]: Failed to upgrade schema, error: "Dirty database version 1. Fix and force version."
2019-03-07T16:38:02Z [FATAL] [main.go:45]: failed to initialize the system: Dirty database version 1. Fix and force version.
```
helm chart  update  harbar to 1.7.1 may fix this.

**Comment by reasonerjt** [comment] 2019-04-03 04:15
@omegazeng have you had a chance to verify on 1.7.1?

**Comment by omegazeng** [comment] 2019-04-03 14:49
@reasonerjt 
no, I changed storageclass(ceph-rbd) filesystem from ext4 to xfs,
then use the same values.yaml reinstall harbor, the issue does not happen again.
I don't know why.
```bash
[hitoshi@hitoshi-pc ~/Documents/harbor-helm] $ helm list |grep harbor
irreverent-woodpecker	1       	Thu Mar 28 20:15:05 2019	DEPLOYED	harbor-1.0.0              	1.7.0      	harbor     
[hitoshi@hitoshi-pc ~/Documents/harbor-helm] $ kubectl get po -n harbor
NAME                                                          READY   STATUS    RESTARTS   AGE
irreverent-woodpecker-harbor-adminserver-5ff5645c94-vrz27     1/1     Running   5          28h
irreverent-woodpecker-harbor-chartmuseum-6d7fb98df8-zqkf7     1/1     Running   1          27h
irreverent-woodpecker-harbor-clair-69996557c-nvmcd            1/1     Running   5          27h
irreverent-woodpecker-harbor-core-7f5b8cdff5-pgc8q            1/1     Running   13         28h
irreverent-woodpecker-harbor-database-0                       1/1     Running   1          28h
irreverent-woodpecker-harbor-jobservice-cd954786f-k48pq       1/1     Running   12         28h
irreverent-woodpecker-harbor-notary-server-774845f945-gxsdb   1/1     Running   1          27h
irreverent-woodpecker-harbor-notary-signer-64c7db4696-khpqk   1/1     Running   1          28h
irreverent-woodpecker-harbor-portal-6ff6d8d65b-dddzg          1/1     Running   1          27h
irreverent-woodpecker-harbor-redis-0                          1/1     Running   1          27h
irreverent-woodpecker-harbor-registry-5d89c568b5-ztrt6        2/2     Running   2          27h
```

I find this https://github.com/goharbor/harbor-helm/commit/4bad3bde1e00d610c390de26513f5e8f0d3d9fc5
so, I guess the new chart version may resolve this problem.

**Comment by reasonerjt** [comment] 2019-04-11 08:36
Thanks, closing.

**Closed by reasonerjt** 2019-04-11 08:36 UTC
Labels: area/helm-chart, pending-for-more-info

**Comment by duyanghao** [comment] 2019-09-04 03:37
@reasonerjt I am afraid the problem is that migrate timeout and cause the `Dirty database version` as below
```
migrate.ErrLockTimeout will be thrown when another process is doing migration and timeout.
```
Refs to this [Issue](https://github.com/mattes/migrate/issues/217)
