### ISSUE TITLE
Docker swarm support

### ISSUE THREAD

**Issue by fitzplb** [goharbor/harbor#3309] opened 2017-09-26 10:36 UTC
It would be good if Harbor could be deployed on docker swarm as swarm services rather than single instance containers so they can move around the swarm nodes when carrying out maintenance.

**Comment by bweston92** [comment] 2018-01-04 10:28
Duplicate of #2868

**Comment by clouderati** [comment] 2018-08-17 15:57
Please continue discussion in https://github.com/goharbor/harbor/issues/2868.

**Closed by clouderati** 2018-08-17 15:57 UTC
Labels: area/deployment, request/feature
