### ISSUE TITLE
Member information is not transferred during project replication

### ISSUE THREAD

**Issue by dgutierr27** [goharbor/harbor#5041] opened 2018-05-25 15:25 UTC
AD/LDAP Authentication
When a project is configured for replication, the members configured on the source are not transferred over to the destination project.  On the destination side, only the default admin account is configured as a member of the replicated project.

For an enterprise deploying an internal Harbor solution, we leverage a single Active Directory.  All of our Harbor instances will authenticate against this one AD.  It would be very useful to have the membership information transferred over to the destination during replication, especially during a DR situation.

Although replication is currently focused on images, it would be nice to have replication of metadata available when desired.

**Comment by reasonerjt** [comment] 2018-05-26 00:06
This is by design, the `image replication` is for images only, **NOT** for user data.

**Comment by dgutierr27** [comment] 2018-05-26 00:31
I understand what the original design was intended for.  However, I think an enhancement would be useful in several (common) scenarios for customers (maintenance, DR, etc.).  You are essentially replicating storage.  Most solutions that replicate storage (e.g. images in your case) also replicate the properties (ACLs, users, etc.) of the storage being replicated.  I don’t think this issue should be dismissed so quickly and closed out.

**Comment by reasonerjt** [comment] 2018-05-28 06:11
Sorry but the description of this issue does sound like a misunderstanding of the feature.
In future we may consider to introduce some external manager tool to replicate all data across instances, but it's not happening very soon I'm afraid
You need to rely on some external tool to replicate all data.

**Comment by clouderati** [comment] 2018-05-29 13:43
Hi all, I've updated the name of the issue and re-opened to keep track of this customer-requested feature.

Thanks!

**Comment by xaleeks** [comment] 2020-11-19 05:01
possible dupe of https://github.com/goharbor/harbor/issues/8709

**Closed by xaleeks** 2020-11-19 05:01 UTC
Labels: Epic, backlog, community, kind/requirement
