### ISSUE TITLE
Get token parsing error in the log when calling APIs with robot account

### ISSUE THREAD

**Issue by ywk253100** [goharbor/harbor#13986] opened 2021-01-13 07:43 UTC
The API call success and there are some errors in the log.
robot account name: `robot$robot01` 
robot account token: `fI5pn7bqHX9AmiZ0mQDY1yDCbLM2SEaK`
```
2021-01-13T07:39:51Z [ERROR] [/pkg/token/token.go:66]: parse token error, token contains an invalid number of segments
2021-01-13T07:39:51Z [ERROR] [/server/middleware/security/robot.go:45][requestID="3427689a8ec7da36f936e3d5e6063281"]: failed to decrypt robot token: token contains an invalid number of segments
```

**Comment by wy65701436** [comment] 2021-01-13 07:52
It's by design.

As the name you used with robot$ prefix, which is identified by robotv1 security context as a valid name, then it will try to decode the password, and raise the error.  After that, the robotv2 security context will take over the job.

**Comment by reasonerjt** [comment] 2021-01-14 06:17
@wy65701436  Are you saying if the prefix is changed, the error will be gone?

**Comment by wy65701436** [comment] 2021-01-14 07:19
> @wy65701436 Are you saying if the prefix is changed, the error will be gone?

yes, if the prefix is changed, it will not treat the incoming user as a robot, and certainly don't rasie the error.

**Comment by defreng** [comment] 2021-04-30 09:46
this message is also completely spamming our log files when using v2 robot accounts...

IMHO this should only be logged as error if the token couldn't be parsed as v1 or v2 token.

**Comment by SimonAlling** [comment] 2021-05-26 07:51
> if the prefix is changed

Does this mean

1. "if the _Robot Name Prefix_ setting is changed to something other than `robot$`", or
2. "if the user name is changed to start with something other than the value of the _Robot Name Prefix_ setting"?

> it will not treat the incoming user as a robot

Does this mean

1. that it won't be identified as a robot account at all, or
2. that it won't be identified as a v1 robot account, but still a v2 robot account?

**Comment by wy65701436** [comment] 2021-06-01 09:04
If the sytem updates the robor prefix to something other than `robot$`, the incoming user won't be identified as robotv1, but still a valid v2 robot. It because the roborv1 identifier uses the `robot$` as a hardcode prefix.

So, the workaround here is that, just updates the robot prefix to something else for v2 robot account, also deprecates the v1 robot account.

**Comment by wy65701436** [comment] 2021-06-01 10:38
https://github.com/goharbor/harbor/pull/15037

**Comment by wy65701436** [comment] 2021-08-10 09:28
close it as fixed.

**Closed by wy65701436** 2021-08-10 09:28 UTC
Labels: kind/limitation, area/robot-account
