### ISSUE TITLE
[Feature Request] Add ability to trigger external webhooks when image pushed

### ISSUE THREAD

**Issue by pengjiang80** [goharbor/harbor#2583] opened 2017-06-20 11:03 UTC
We would like to have a similar feature with Dockerhub. When there is new version of imaged pushed, Harbor can trigger external webhook URLs. This is quite helpful to build a smooth CICD pipeline. 

![untitled](https://user-images.githubusercontent.com/16434640/27330215-14bad6e4-55eb-11e7-9ba4-de03f4a9240b.png)

**Comment by pengjiang80** [comment] 2017-07-04 02:01
A little more information, both Dockerhub and Aliyun Registry support webhook. The HTTP post body is a 
 little different between Dockerhub and Aliyun. In our (Rancher) side, we can support both. Harbor can either follow Dockerhub/Aliyun or use its own body format. We can add support for Harbor's format if required.

**Comment by whytoe** [comment] 2017-11-29 19:51
Any progress on this, Jenkins other CI/CD workflows support this and it seems like an essential feature to use this in production environments

**Comment by nlowe** [comment] 2018-06-28 12:57
This may be a dupe of #2448. @reasonerjt Are there plans to implement this? Or should we be expected to tweak the config of the backing docker registry container to support this via [notifications](https://docs.docker.com/registry/notifications/#configuration)?

**Comment by reasonerjt** [comment] 2018-06-28 13:28
@nlowe Sorry it's not in the short term plan, but yes you can update the configuration of the registry to add another notification handler.

**Comment by nlowe** [comment] 2018-06-28 13:59
@reasonerjt Would you accept a pull request for this? We may be looking to contribute something, still trying to judge how necessary this is for us.

**Comment by clouderati** [comment] 2018-08-17 15:37
Hi @nlowe – we'd definitely love help with something like this.

Would really appreciate any contributions. If you'd like to help please ping me and @reasonerjt on this thread so that we can chat about potential architectural implications before you start writing lots of code. 👍

**Comment by clouderati** [comment] 2018-10-10 15:24
Hi @shinebayar-g – thanks for the feedback. We love contributions. :smile:

**Comment by kaybinwong** [comment] 2019-01-05 08:39
the feature would be very useful  for ci/cd pipeline.

**Comment by nlowe** [comment] 2019-01-07 04:53
Support for this is proposed in #6676. A formal proposal will be drafted in the near future. Please follow that issue for updates.

**Closed by nlowe** 2019-01-07 04:53 UTC
Labels: backlog, request/feature
