### ISSUE TITLE
UI cant fetch metadata for Helm Chart v2 - HELM_CHART.NO_DETAIL

### ISSUE THREAD

**Issue by dntosas** [goharbor/harbor#12394] opened 2020-07-04 07:37 UTC
**Expected behavior and actual behavior:**
Harbor UI supports showing information for Helm Charts based on their README.md and values.yaml and we expect when pushing Helm Charts with `apiVersion: v2` to see their metadata on UI.

But when pushing a Helm Chart with `apiVersion: v2`, UI cant fetch its metadata and returns and errors as follows:
```
Internal Server Error: HELM_CHART.NO_DETAIL
```
This happens when pushing only `v2` Charts, while with `v1` Charts everything works as expected

**Steps to reproduce the problem:**
Package any dummy Helm chart with `apiVersion: v2` and push it to Harbor Registry. Then navigate to UI and click on this chart to check details

**Versions:**
- harbor version: [2.0.1]

**Additional context:**
Also tried with `absoluteUrl: enable` on chartmuseum without luck

**Comment by ninjadq** [comment] 2020-07-06 07:39
I think that the 500 Error is caused by Webhook. But the root cause is that `apiVersion: v2` can only parsed by Helm v3.  I think this is by design in helm base on [this issue](https://github.com/helm/helm/issues/6753). Harbor chart's library is v2 and it can not parse chart with `apiVersion: v2`.
A workaround now is to use harbor oci-compatible registry to store your chart.

**Comment by reasonerjt** [comment] 2020-07-06 08:23
@ninjadq could you check if this can be fixed by upgrading the depended library.

**Comment by MaxRink** [comment] 2020-07-09 18:51
Weve hit the same issue.
Ontop, deleted charts stay visible within the Version list

**Closed** 2020-07-22 05:31 UTC
Labels: area/helm-chart-repo, target/2.1.0

**Comment by Lemmons** [comment] 2020-07-30 18:47
any chance of this fix making it into v2.0.2?

**Comment by AlexOQ** [comment] 2020-08-30 08:28
Helm v2.0.0
When trying to access chart version in UI, we receive the red banner on to with `500 Internal server error`.
Console inspection shows `GET https://{server_url}/api/chartversions/{project_name}/charts/{chart_name}/{chart_version} 500`
Anyone has suggestions?
