### ISSUE TITLE
Unable to Access Harbor UI 

### ISSUE THREAD

**Issue by McCoyAle** [goharbor/harbor#14481] opened 2021-03-19 21:41 UTC
When attempting to access the Harbor UI, in the browser we are receiving a 401 Unauthorized message. All pods are currently up and in a running state, and Harbor is configured with an NGINX reverse proxy. Have tried multiple browsers and cleared the cache/cookies.

**Browser Errors:**
Preview Output: {errors: [{code: "UNAUTHORIZED", message: "UnAuthorize"}]}
* errors: [{code: "UNAUTHORIZED", message: "UnAuthorize"}]
* 0: {code: "UNAUTHORIZED", message: "UnAuthorize"}
* code: "UNAUTHORIZED"
* message: "UnAuthorize"

**Users are able to push and pull to the registry. When checked Harbor Core logs, we see the following error message:** 

`
2021/03/19 15:40:31.464 [server.go:3088]  [HTTP] http: TLS handshake error from XXX.XX.XX.XX:2322: EOF
`

and also 

2021-03-19T15:41:49Z [ERROR] [/replication/adapter/native/adapter.go:126]: failed to ping registry https:/<redacted>: http status code:404 Not Found nginx/1.19.2

**Curling the harbor signing page produces the following:**

curl -v https://<redacted>/harbor/sign-in\?redirect_url\=%2Fharbor%2Fprojects
 Trying XXX.XX.XX.XX...
 TCP_NODELAY set
 Connected to <redacted> (XXX.XX.XX.XX) port 443 (#0)
 ALPN, offering h2
 ALPN, offering http/1.1
 successfully set certificate verify locations:
 CAfile: /etc/ssl/cert.pem
CApath: none
 TLSv1.2 (OUT), TLS handshake, Client hello (1):
 TLSv1.2 (IN), TLS handshake, Server hello (2):
 TLSv1.2 (IN), TLS handshake, Certificate (11):
 TLSv1.2 (IN), TLS handshake, Server key exchange (12):
 TLSv1.2 (IN), TLS handshake, Server finished (14):
 TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
 TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
 TLSv1.2 (OUT), TLS handshake, Finished (20):
 TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
 TLSv1.2 (IN), TLS handshake, Finished (20):
 SSL connection using TLSv1.2 / 
 ALPN, server accepted to use h2
 Server certificate:
 subject: ST=Gauteng; L=Sandton; O=TS Platform Services; OU=Discovery Group
 start date: Mar 18 14:10:11 2021 GMT
 expire date: Jun 16 14:10:41 2021 GMT
 subjectAltName: host "<redacted>" matched cert's ",<redacted>"
 issuer: C=ZA; ST=Gauteng; L=Sandton; O=TS Platform; OU=TS; CN=Kubernetes Ingress CA
 SSL certificate verify ok.
 Using HTTP2, server supports multi-use
 Connection state changed (HTTP/2 confirmed)
 Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
 Using Stream ID: 1 (easy handle 0x7fbf22010800)
 GET /harbor/sign-in?redirect_url=%2Fharbor%2Fprojects HTTP/2
 Host: <redacted>
 User-Agent: curl/7.64.1
 Accept: */*

 Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
 HTTP/2 200
 server: nginx/1.19.2
 date: Fri, 19 Mar 2021 20:16:12 GMT
 content-type: text/html
 content-length: 856
 vary: Accept-Encoding
 last-modified: Wed, 16 Sep 2020 02:45:15 GMT
 etag: "5f617c3b-358"
 cache-control: no-store, no-cache, must-revalidate
 accept-ranges: bytes
 strict-transport-security: max-age=15724800; includeSubDomains

<!doctype html>
<html>

<head>
<meta charset="utf-8">
<title>Harbor</title>
<base href="/">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="icon" type="image/x-icon" href="favicon.ico?v=2">
<link rel="preload" as="style" href="./light-theme.css">
<link rel="preload" as="style" href="./dark-theme.css">
<link rel="stylesheet" href="styles.fd4a2ff060f99b077bef.css"></head>
<body>
<harbor-app>
<div class="spinner spinner-lg app-loading app-loading-fixed">
Loading...
</div>
</harbor-app>
<script src="runtime.9ad22a88fcc70a015907.js" defer></script><script src="polyfills-es5.c04cfdffe6ecc730c69c.js" nomodule defer></script><script src="scripts.f4c015c4300c31a9a23c.js" defer></script><script src="main.50faa391a4ae8743ad63.js" defer></script></body>

Connection #0 to host <redacted>s left intact
 Closing connection 0
`

**Version Information:**
Harbor: 2.1.0-a3eca103
Browser: Chrome
Kubernetes:
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-13T13:14:05Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by McCoyAle** [comment] 2021-03-19 21:47
In addition, the nginx configuration is below:

apiVersion: v1
data:
  nginx.conf: |
    worker_processes auto;
    pid /tmp/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        client_body_temp_path /tmp/client_body_temp;
        proxy_temp_path /tmp/proxy_temp;
        fastcgi_temp_path /tmp/fastcgi_temp;
        uwsgi_temp_path /tmp/uwsgi_temp;
        scgi_temp_path /tmp/scgi_temp;
        server {
            listen 8443 ssl;
            # SSL
            ssl_certificate /etc/harbor/tls/portal.crt;
            ssl_certificate_key /etc/harbor/tls/portal.key;

            # Recommendations from https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
            ssl_protocols TLSv1.2;
            ssl_ciphers '!aNULL:kECDH+AESGCM:ECDH+AESGCM:RSA+AESGCM:kECDH+AES:ECDH+AES:RSA+AES:';
            ssl_prefer_server_ciphers on;
            ssl_session_cache shared:SSL:10m;

            server_name  localhost;
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            include /etc/nginx/mime.types;
            gzip on;
            gzip_min_length 1000;
            gzip_proxied expired no-cache no-store private auth;
            gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
            location / {
                try_files $uri $uri/ /index.html;
            }
            location = /index.html {
                add_header Cache-Control "no-store, no-cache, must-revalidate";
            }
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-22T11:59:16Z"
  labels:
    app: harbor
  name: harbor-portal
  namespace: harbor
  resourceVersion: "73385239"
  selfLink: /api/v1/namespaces/harbor/configmaps/harbor-portal
  uid: ecee2e7a-9c89-4f10-8f80-b27d2c5d70d6

**Comment by moshloop** [comment] 2021-03-21 14:34
This is a duplicate of https://github.com/goharbor/harbor/issues/14147

**Comment by heww** [comment] 2021-03-22 02:52
Can you share the screenshot of the network panel in the developer tools when access Harbor UI by chrome?

Let me get more info about `All pods are currently up and in a running state, and Harbor is configured with an NGINX reverse proxy`.  
1. Is the harbor running in k8s cluster and it's installed by helm? 
2. What is the type of expose of the harbor, ingress,clusterIP, nodePort or loadBalancer? 
3. Is the NGINX reverse proxy a single service not part of the harbor?
4. Is the reverse proxy also running in the k8s cluster?
5. What is the configuration in the proxy for the harbor?

**Comment by moshloop** [comment] 2021-03-22 07:23
This issue was resolved by scaling harbor-core replicas to 1
The /c/login request does not appear in developer tools  (even after getting it to work) I suspect this is due to 200 response code without a body - It should be a 204 response code for no content.

**Comment by McCoyAle** [comment] 2021-03-22 18:29
@heww Thanks for the update. I only have the following captures from the call on Friday:
<img width="918" alt="Screen Shot 2021-03-19 at 5 22 56 PM" src="https://user-images.githubusercontent.com/25905730/112039530-857e7580-8b1a-11eb-982b-571dc1ee9b47.png">

In addition to that, it seems they have the following setup:

1. They are deploying with Karina, and not helm. 
2. Harbor is exposed via nodePort
3. Everything is running within the cluster except for the NSX LoadBalancer
4. nginx.conf [file is above](https://github.com/goharbor/harbor/issues/14481#issuecomment-803152400), but it seems the commented didn't format correctly

**Comment by McCoyAle** [comment] 2021-03-22 18:33
In addition, it seems [the bug](https://github.com/goharbor/harbor/issues/14147) referenced above, they are using helm but here a different deployment so, is it that it's likely not related to the method of deployment?

**Comment by perithompson** [comment] 2021-05-24 10:38
@heww are we still waiting for more info here? This this has the info you requested?

**Comment by moshloop** [comment] 2021-05-24 10:42
@perithompson  this can be closed, it was due to the incorrect variable for the REDIS_CORE_URL

**Comment by perithompson** [comment] 2021-05-24 11:47
Thanks for getting back to this @moshloop  really appreciate it!

**Closed** 2021-06-05 15:24 UTC
Labels: area/configuration, env_issue
