### ISSUE TITLE
"Internal Server Error" occurred  when add a replication rule

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#8464] opened 2019-07-29 10:37 UTC
![image](https://user-images.githubusercontent.com/44018302/62041985-8cfb5780-b22f-11e9-823f-c0b23a19cadf.png)

![image](https://user-images.githubusercontent.com/44018302/62042014-9ab0dd00-b22f-11e9-972e-13af588fc94d.png)

**Comment by ywk253100** [comment] 2019-07-31 02:33
Cannot reproduce it, move it out of scope 1.9.0 and will check it when find the issue again.

**Comment by ywk253100** [comment] 2019-08-19 06:56
Not happen again, closing it

**Closed by ywk253100** 2019-08-19 06:56 UTC
Labels: area/replication
