### ISSUE TITLE
Helm Charts not downloadable via UI since 2.3

### ISSUE THREAD

**Issue by Shadowghost** [goharbor/harbor#15228] opened 2021-06-29 11:06 UTC
**Expected behavior and actual behavior:**
Downloading a Helm Chart is currently not possible via the UI. Adding the repo and using the charts with helm works fine.

**Steps to reproduce the problem:**
- Create Helm Chart on any repo
- Try downloading the Helm Chart via UI
- UI shows a 404 error from calling `<domain>/api/chartrepo/<repo>/charts/<chart>-<version>.tgz`

**Versions:**
- harbor version: [2.3.0]
- docker engine version: [20.10]

**Additional context:**
- harbor is installed via helm on a RKE cluster

**Comment by shad2y** [comment] 2021-07-20 21:50
I faced the same issues with 2.3.0 app version:
Helm installation, GKE cluster, GCS storage backend.

logs:
`2021-07-20T21:19:48Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 0c8fa62c605fe8792b081ddf65207f3d to the logger for the request GET /api/chartrepo/library/charts/appstructure-1.0.1.tgz
2021-07-20T21:19:48Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /api/chartrepo/library/charts/appstructure-1.0.1.tgz
2021-07-20T21:19:48Z [DEBUG] [/server/middleware/security/session.go:46][requestID="0c8fa62c605fe8792b081ddf65207f3d"]: a session security context generated for request GET /api/chartrepo/library/charts/appstructure-1.0.1.tgz
2021-07-20T21:19:48Z [DEBUG] [/pkg/permission/evaluator/admin/admin.go:35]: system administrator admin require list action for resource /project/1/helm-chart-version
2021-07-20T21:19:48Z [DEBUG] [/lib/http/error.go:59]: {"errors":[{"code":"NOT_FOUND","message":"fail to get chart: not found"}]}`

Object listing:
` gsutil ls -r gs://harbor-registry-storage/library
gs://harbor-registry-storage/library/:
gs://harbor-registry-storage/library/appstructure-1.0.1.tgz
gs://harbor-registry-storage/library/index-cache.yaml`

Screen from the WebUI:
<img width="1436" alt="Screenshot 2021-07-21 at 00 47 39" src="https://user-images.githubusercontent.com/5433753/126399923-56ca46ea-790f-495c-a799-e8b040e8a720.png">

**Comment by rafis** [comment] 2021-07-29 13:24
The bug is in adding `/api/` into URL which should be without.

**Comment by dbalpha** [comment] 2021-08-11 10:24
I faced the same issue to：
![图片](https://user-images.githubusercontent.com/37523304/129013151-1a235ece-01a6-4e9c-96e1-c28126fe60ce.png)

**Comment by adityati** [comment] 2021-08-13 23:47
Looks like a UI issue, I have the same issue (could not download the Helm charts via Download link) in Harbor Version **v2.3.1-1058f330** deployed via Docker Containers.

**Comment by wy65701436** [comment] 2021-08-20 17:46
@ninjadq I can reproduce it, we need to address a fix. 

@danfengliu @YangJiao0817 we need a test here.

**Comment by AllForNothing** [comment] 2021-08-25 01:57
Close it. The test case is tracked by another issue #15479

**Closed by AllForNothing** 2021-08-25 01:57 UTC
Labels: kind/bug, needs/test-case, area/helm-chart, target/2.4.0, target/2.3.3
