### ISSUE TITLE
docker login 使用oidc账号未授权

### ISSUE THREAD

**Issue by koulq** [goharbor/harbor#10256] opened 2019-12-13 09:25 UTC
What can we help you?
@steven-zou 你好harbor-core在启动的时候未注册oidc_auth
![image](https://user-images.githubusercontent.com/18571340/70789061-41f07400-1dcd-11ea-8a15-5deebfe82581.png)
使用docker login -u cloud-operator -p qgj6282hzf943he0zgpxksq6q70sfjjx harbor91.iop.com不能登录，显示未授权
![image](https://user-images.githubusercontent.com/18571340/70789136-6ba99b00-1dcd-11ea-9690-014caed16bf3.png)
core的日志：
![image](https://user-images.githubusercontent.com/18571340/70789181-7f550180-1dcd-11ea-95e4-4ca3a88b132b.png)

**Comment by reasonerjt** [comment] 2019-12-16 03:31
@koulq what version of build are you using?

**Comment by koulq** [comment] 2019-12-16 03:47
@reasonerjt 用的是1.8.1

**Comment by reasonerjt** [comment] 2019-12-16 06:50
is `could-operator` onboarded via OIDC authn flow and the password a valid cli secret?

**Comment by koulq** [comment] 2019-12-16 07:01
OIDC用户能够登陆harbor控制台，cli密码是通过使用文档，从harbor控制台获取的，如下：
![image](https://user-images.githubusercontent.com/18571340/70885759-bbc66e80-2014-11ea-98f7-6c54825fdd86.png)

**Comment by koulq** [comment] 2019-12-16 07:42
@reasonerjt 找到问题了，为啥我的OIDC用户是cloud-operator，到了harbor之后变成cloud_operator了，这是问题所在

**Comment by danielzhanghl** [comment] 2019-12-16 08:17
it seems oidc user can't login directly from CLI,
 it has to use "secret" after login from GUI, right?

**Comment by reasonerjt** [comment] 2019-12-16 08:21
@koulq  Harbor的用户名有限制，因此在onboard时候做了转换。
@danielzhanghl yes, because the CLI does not have support for the SSO authentication flow.

Closing this issue and the problem is fixed.

**Closed by reasonerjt** 2019-12-16 08:21 UTC
Labels: area/oidc
