### ISSUE TITLE
where's the image: vmware/harbor-core:v1.2.0?

### ISSUE THREAD

**Issue by nicklv** [goharbor/harbor#6341] opened 2018-11-24 06:27 UTC
What can we help you?
vmware/harbor-core:v1.2.0 cant be found in hub.docker.com. where can download it?

**Comment by clouderati** [comment] 2018-11-30 21:50
The images should now be in the `goharbor` namespace, right @reasonerjt?

**Comment by ninjadq** [comment] 2018-12-03 10:32
maybe this is caused by the older version of helm chart.
you can try using this chart https://github.com/goharbor/harbor-helm

**Comment by reasonerjt** [comment] 2019-03-05 07:01
I assume this is fixed, closing.

Please reopen if you need further help.

**Closed by reasonerjt** 2019-03-05 07:01 UTC
Labels: kind/question
