### ISSUE TITLE
failed to pull images from harbor backend is S3

### ISSUE THREAD

**Issue by sinycn** [goharbor/harbor#6730] opened 2019-01-10 08:54 UTC
hi 
i get some error when push or pull from harbor,the backend is S3
![image](https://user-images.githubusercontent.com/1812254/50957146-70e4d280-14f8-11e9-9234-15618dfbcbe6.png)

**Comment by reasonerjt** [comment] 2019-01-10 09:16
The problem is in your client that it times out to access S3.... 

I don't think Harbor can fix it given its scope.

**Comment by ninjadq** [comment] 2019-01-11 04:32
@sinycn plz provide more information like error log and your enviroment

**Comment by sinycn** [comment] 2019-01-11 05:14
@ninjadq  i finally find the reason: our proxy https inspect function cause this issue

**Comment by reasonerjt** [comment] 2019-01-18 07:07
@sinycn  thanks for the update, let me close this one...

**Closed by reasonerjt** 2019-01-18 07:07 UTC
Labels: pending-for-more-info
