### ISSUE TITLE
get tags by pager

### ISSUE THREAD

**Issue by liuchaoheliang** [goharbor/harbor#6551] opened 2018-12-19 02:02 UTC
when i get tag list by project, there is too many data response, seems like all the tags data .
so, Did you consider add a paging query Interface for this scenario.
because when i call the Interface ,it takes a long time.

**Comment by zhoumeina** [comment] 2018-12-25 01:53
this need both backend api change and frontend change. Need to estimate the effort.

**Comment by lizpark** [comment] 2018-12-29 10:36
@zhoumeina what about tags api default to get all tags, new params to get limit tags ? when images increase rapidly, request timeout frequently.

**Comment by louyiping** [comment] 2019-01-04 09:59
@zhoumeina  Getting tags timeout trouble me a lot. My program can't work now because of it.

**Comment by reasonerjt** [comment] 2019-01-10 09:15
@louyiping how many tags are there in your env and how long does it take to timeout?

We need a systematic way to solve the perf issue.  
Set a proper goal and see how we can achieve it.

**Comment by louyiping** [comment] 2019-01-10 17:58
@reasonerjt  I think this situation I met is caused by the Ceph RBD storage I use.
In our env, there are Tens of thousands of tags. And this api is ok in our aliyun env and the corresponding storage is aliyun disk.
But When I call this api in another env using Ceph RBD , Even taking ten minutes I can't receive the reponse.

**Comment by zhoumeina** [comment] 2019-08-19 08:11
this can be easily fix if backend support get tag detail api by page. Frontend change is small.

**Comment by zhoumeina** [comment] 2019-08-19 08:17
@AllForNothing , could you please take care of this?

**Comment by AllForNothing** [comment] 2019-08-19 08:36
@ywk253100 need backend-api paging support

**Comment by ywk253100** [comment] 2019-08-21 02:09
We are considering storing the tag information in the database and the design is in progress, after that the pagination for listing tags will be supported

**Comment by petvaa01** [comment] 2020-01-10 14:06
Either pagination or filtering for `/repositories/{repo_name}/tags` would be great. We have repositories currently with over 1500 tags and using this causes a lot of load on Harbor.

**Comment by xaleeks** [comment] 2020-04-08 09:02
This is useful, has this been fixed in upcoming release? @ywk253100 @AllForNothing

**Comment by ywk253100** [comment] 2020-04-11 23:11
Harbor supports registry API and the listing tag API of registry always supports the pagination.

And Harbor 2.0 introduces the API to list tags of artifact, this API supports pagination as well.

**Closed by ywk253100** 2020-04-11 23:11 UTC
Labels: kind/requirement
