### ISSUE TITLE
[proxy cache] The pull time of tag doesn't change in the proxy cache project

### ISSUE THREAD

**Issue by wy65701436** [goharbor/harbor#12722] opened 2020-08-11 08:13 UTC
1, cache hello-world:latest
2, docker pull ***/mycache/library/hello-world:latest 

the pull time in the tag details page doesn't change.

**Comment by stonezdj** [comment] 2020-08-18 07:50
cannot reproduce it with latest build. it might be related to the #12741

**Comment by reasonerjt** [comment] 2020-08-25 03:33
Closing as a dup to #12741

**Closed by reasonerjt** 2020-08-25 03:33 UTC
Labels: target/2.1.0, target/RC
