### ISSUE TITLE
Newly built harbor, there are residual events in the event log

### ISSUE THREAD

**Issue by gglnp** [goharbor/harbor#16204] opened 2022-01-11 07:15 UTC
Hi.
I have built a latest version of the harbor repository here.
After the deployment was successful, I logged in and found that there were still residual events in the event log, which was incredible! ! !
I am operating on a brand new server, the mount directory is also generated by it, and the warehouse log shows an empty log. I don't quite understand why this event log exists?

- harbor version: [v2.4.1]
- docker engine version: [v20.10.10]
- docker-compose version: [v2.2.2]

![harbor-log-error](https://user-images.githubusercontent.com/61819511/148897257-92eadb72-99ba-4c24-9c13-26025ee7cbe4.png)

![harbor-log-null](https://user-images.githubusercontent.com/61819511/148897325-b971a709-19d6-4cc9-893d-3b84ee07262d.png)

**Comment by AllForNothing** [comment] 2022-01-12 02:57
@gglnp This is by design. We store some UI operations grouped by user id into the browser's local storage, so you need to manually delete the local storage data for your Harbor's domain

**Comment by AllForNothing** [comment] 2022-01-18 03:59
Closing it, if any other questions, please open a new issue.

**Closed by AllForNothing** 2022-01-18 03:59 UTC
Labels: area/ui
