### ISSUE TITLE
AUTH_MODE and UAA auth env variables do not seem to be loaded by core

### ISSUE THREAD

**Issue by paulczar** [goharbor/harbor#7087] opened 2019-03-07 00:36 UTC
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

When starting core via docker/kubernetes with UAA settings in environment variables, it should come online full configured for UAA auth.   When I log in the first time using the `admin` user it shows configured for db users. 

```console
root [ /harbor ]# env | grep -i uaa
UAA_CA_ROOT=/etc/core/uaa/ca.crt
UAA_VERIFY_CERT=true
UAA_ENDPOINT=https://pks.xxxxxx:8443
UAA_CLIENTSECRET=xxxxxxxx
UAA_CLIENTID=harbor
AUTH_MODE=uaa_auth
```

![uaa_1](https://user-images.githubusercontent.com/2488346/53923356-a52ec800-403d-11e9-9506-e0109cd7f44e.png)

if I swap the dropdown box to uaa it shows only one setting being set:

![uaa-2](https://user-images.githubusercontent.com/2488346/53923364-b24bb700-403d-11e9-9ecc-3e1fae7eb823.png)

**Steps to reproduce the problem:**
Please provide the steps to reproduce this problem.

**Versions:**
Please specify the versions of following systems.
- harbor version: dev image

**Additional context:**

I'm installing harbor via my fork of the helm charts.  You can see my changes to the chart in adding UAA support [here](https://github.com/goharbor/harbor-helm/pull/177)

including subdirectory.
* **Log files:**

not sure if this helps much:

```
k logs -f harbor-dev-harbor-core-7d5b7d7d96-b9d45
2019-03-07T00:21:34Z [DEBUG] [authenticator.go:126]: Registered authentication helper for auth mode: http_auth
2019-03-07T00:21:34Z [DEBUG] [authenticator.go:126]: Registered authentication helper for auth mode: db_auth
2019-03-07T00:21:34Z [DEBUG] [authenticator.go:126]: Registered authentication helper for auth mode: ldap_auth
2019-03-07T00:21:34Z [DEBUG] [authenticator.go:126]: Registered authentication helper for auth mode: uaa_auth
2019-03-07T00:21:34Z [DEBUG] [init.go:37]: topic OnPush is subscribed
2019-03-07T00:21:34Z [DEBUG] [init.go:37]: topic OnDeletion is subscribed
2019-03-07T00:21:34Z [DEBUG] [init.go:37]: topic StartReplication is subscribed
2019-03-07T00:21:34Z [INFO] Config path: /etc/core/app.conf
2019-03-07T00:21:34Z [INFO] initializing configurations...
2019-03-07T00:21:34Z [INFO] key path: /etc/core/key
2019-03-07T00:21:34Z [INFO] init secret store
2019-03-07T00:21:34Z [INFO] init project manager based on deploy mode
2019-03-07T00:21:34Z [INFO] initializing the project manager based on local database...
2019-03-07T00:21:34Z [INFO] configurations initialization completed
2019-03-07T00:21:34Z [INFO] Registering database: type-PostgreSQL host-harbor-dev-harbor-database port-5432 databse-registry sslmode-"disable"
2019-03-07T00:21:35Z [ERROR] [utils.go:101]: failed to connect to tcp://harbor-dev-harbor-database:5432, retry after 2 seconds :dial tcp 10.100.200.111:5432: i/o timeout
2019-03-07T00:21:39Z [ERROR] [utils.go:101]: failed to connect to tcp://harbor-dev-harbor-database:5432, retry after 2 seconds :dial tcp 10.100.200.111:5432: i/o timeout
2019-03-07T00:21:45Z [ERROR] [utils.go:101]: failed to connect to tcp://harbor-dev-harbor-database:5432, retry after 2 seconds :dial tcp 10.100.200.111:5432: i/o timeout
2019-03-07T00:21:55Z [ERROR] [utils.go:101]: failed to connect to tcp://harbor-dev-harbor-database:5432, retry after 2 seconds :dial tcp 10.100.200.111:5432: i/o timeout
```

**Comment by steven-zou** [comment] 2019-03-08 02:47
@ywk253100 

Please take a look at this issue to see if it is caused by Harbor cfg mgmt?

**Comment by ywk253100** [comment] 2019-03-20 11:02
Some refactor has been merged and the UAA settings cannot be set via environment variables anymore. You can call the system setting API to modify them or change them on portal.

**Comment by paulczar** [comment] 2019-03-26 11:54
Is this going to be resolved, or will it left unsettable via environment variables?

**Comment by paulczar** [comment] 2019-03-26 11:55
is there documentation on the system setting api ?

**Comment by ywk253100** [comment] 2019-04-10 02:09
They cannot be set by environment variables anymore, it is by design. And we have opened an issue https://github.com/goharbor/harbor/issues/7324 to track the documentation work. Closing this one.

**Closed by ywk253100** 2019-04-10 02:09 UTC
Labels: area/helm-chart
