### ISSUE TITLE
[OIDC-keycloak] Unable to authenticate with OIDC 

### ISSUE THREAD

**Issue by dedsxc** [goharbor/harbor#18025] opened 2022-12-24 18:41 UTC
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected behavior: After configuring the OIDC authentication with the client_id and client_secret, Harbor should able to connect with OIDC provider. 

Actual behavior: Harbor failed to authenticate with the provided client_secret : "Invalid client or Invalid client credentials"

**Steps to reproduce the problem:**
On keycloak server (version 20.0.2), create a client using oidc protocol with credential. Report the keycloak client's properties on Harbor oidc configuration. Login in harbor via OIDC provider.

On harbor server, choose : 
- Auth mode: oidc
- oidc provider name: Keycloak
- oidc endpoint: https://<hostname_idp>/realms/\<yourRealm>
- oidc client id: \<clientIdKeycloak>
- oidc client secret: \<clientSecretKeycloak>
- oidc scope: openid,profile,email,offline_access
- automatic onboarding : true
- username claim: preferred_username

**Versions:**

- harbor version: [v2.6.0-b035ca7]
- docker engine version: [20.10.3]
- docker-compose version: [v2.10.2]

**Additional context:**
I checked in the postgres db on table "properties", the client_id and client_secret are both correct.

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .
```
[ERROR] [/core/controllers/oidc.go:93]: Failed to exchange token, error: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"unauthorized_client","error_description":"Invalid client or Invalid client credentials"}
```

**Comment by Vad1mo** [comment] 2022-12-26 10:27
Closing, as there are a dozen of examples and tutorials on how to set up Harbor with Keycloack and your reported setup is as standard as it gets. 


Here are some examples on setting up Harbor with Keycloack.
- https://medium.com/@panda1100/keycloak-as-oidc-provider-for-harbor-c25906481619
- https://blog.lazybit.ch/harbor-keycloak-auth/
- https://number1.co.za/integrating-keycloak-and-harbor-registry-with-openid-connect/

**Closed by Vad1mo** 2022-12-26 10:27 UTC

**Comment by dedsxc** [comment] 2022-12-29 17:29
Hi,

THank you for your reply. Before opening the ticket, I also followed the steps described on those link. I checked the client_secret and client_id on harbor's db and the credential are correct. That's why I don't understand the error ..

**Comment by dedsxc** [comment] 2022-12-29 18:11
Ok the issue is fixed. It was due to the CORE_KEY variable which has to be 16 char 

-> https://github.com/bitnami/bitnami-docker-harbor-core/pull/2

**Comment by Julien-Fruteau** [comment] 2025-03-26 03:34
Hello, for those using helm chart, as of version 1.16.2, pay extra attention to the `values.yaml` file which indeed ask for 16 char secret :

```txt
# The secret key used for encryption. Must be a string of 16 chars.
secretKey: "not-a-secure-key"
# If using existingSecretSecretKey, the key must be secretKey
```
i misread the comment at 1st install and set another secretKey length resulting in error `"oauth2: unauthorized_client - Invalid client or Invalid client credentials"` during authentication process, which proved hard to trace back to this root cause.

this secret seems to be used by encrypt lib and if not set as expected leaves Harbor unable to exchange the authorization code for tokens from Keycloak
