### ISSUE TITLE
Enable Anonymous access to all public projects, repos

### ISSUE THREAD

**Issue by mcrosson** [goharbor/harbor#7118] opened 2019-03-11 19:45 UTC
Is there a way to enable full read-only access to all pubic items inside harbor?

Specifically search, projects and registries?

docker pull works if the path to the image is known but discovery for anonymous users is a problem.

I've tried adding the 'anonymous' user to projects but the main UI says the user does not exist even though it shows in the logs as having performed a pull operation

**Comment by nlowe** [comment] 2019-03-12 23:27
I believe this is a duplicate of #6435

**Closed by nlowe** 2019-03-12 23:27 UTC

**Comment by mcrosson** [comment] 2019-03-12 23:28
Agreed, sub'd to appropriate issue
