### ISSUE TITLE
Pull-based replication from Harbor doesn't work with project-level robot accounts

### ISSUE THREAD

**Issue by defreng** [goharbor/harbor#14640] opened 2021-04-13 16:05 UTC
**Expected behavior**
In the following setup consisting of HarborA (master) and HarborB (replica), I'm trying to setup pull-based replication inside HarborB.

As only a single project from HarborA should be replicated, I created a project-level robot account inside HarborA and used this one to configure the pull replication in HarborB, which is expected to discover the artifacts in that project in HarborA and copy them.

**Actual**
The replication jobs all report status SUCCESS, but don't copy any artifacts (no images, no charts). The jobservice logs are empty and just report SUCCESS

**Steps to reproduce the problem:**
I'm assuming the issue comes from the following callchain, which tries to find the origin project by calling the ListProjects API in Harbor, which is inaccessible for project-level robot accounts:

1. https://github.com/goharbor/harbor/blob/v2.2.0/src/replication/adapter/harbor/v2/adapter.go#L54
1. https://github.com/goharbor/harbor/blob/v2.2.0/src/replication/adapter/harbor/base/adapter.go#L200
1. https://github.com/goharbor/harbor/blob/v2.2.0/src/replication/adapter/harbor/base/client.go#L117

**Versions:**
- harbor version: 2.2.0

**Comment by ChristianCiach** [comment] 2021-04-14 19:55
Duplicate of https://github.com/goharbor/harbor/issues/13384

**Comment by ChristianCiach** [comment] 2021-04-14 19:57
I still think that this is a bug that should be fixed. Project-level robot accounts should be semantically equal to system-level robot accounts that are configured to access a single project.

**Comment by wy65701436** [comment] 2021-04-19 06:34
hi @defreng , how did you create the robot account? can you share the request body?

**Comment by BrandonWeng** [comment] 2021-05-07 16:45
FWIW We're running `Version v2.2.1-b0d63082` and push-based replication between two Harbor instances seems to work for us but pull-based replication is failing with different error messages..

Harbor A --> Harbor B: 
Fails with 
`failed to do the prepare work for pushing/uploading resources: http error: code 403, message {"errors":[{"code":"FORBIDDEN","message":"Only system admin can create project"}]}`

Harbor A <-- Harbor B: 
Fails with 
`failed to do the prepare work for pushing/uploading resources: http error: code 404, message {"errors":[{"code":"NOT_FOUND","message":"user robot$robot-user not found"}]}`

**Comment by wy65701436** [comment] 2021-09-02 18:25
To use robot to do the replication will be in v2.4, but it only supports the system level robot. As it's ready now in main, close the issue.

**Closed by wy65701436** 2021-09-02 18:25 UTC
Labels: area/ui, area/robot-account, target/2.4.0
