### ISSUE TITLE
GC Untagged accessory  will get an error and block GC

### ISSUE THREAD

**Issue by AllForNothing** [goharbor/harbor#17200] opened 2022-07-19 07:47 UTC
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
1. GC Untagged accessory will get an error and block GC. This resulted in those images that should have been deleted not being deleted

**Steps to reproduce the problem:**
1.  Push  two images to Harbor, like  `nginx and helloworld`
2.  Sign one(`nginx`) of the two images with cosign
3.  Delete the tags of both the cosign and another image (`helloworld)
4. Execute GC with `untagged` item on
5. you will get an error  in the GC log:
7. GC will be stopped and `helloworld` will not be deleted

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.6.0

Error in  GC log:
`2022-07-19T07:18:14Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:143]: Garbage Collection parameters: [delete_untagged: true, dry_run: false, time_window: 2]
2022-07-19T07:18:14Z [INFO] [/jobservice/job/impl/gc/garbage_collection.go:153]: start to run gc in job.
2022-07-19T07:18:14Z [ERROR] [/jobservice/job/impl/gc/garbage_collection.go:189]: failed to get deleted Artifacts in gc job, with error: accessory type signature.cosign not support
2022-07-19T07:18:14Z [ERROR] [/jobservice/job/impl/gc/garbage_collection.go:161]: failed to execute GC job at mark phase, error: accessory type signature.cosign not support`

**Comment by zyyw** [comment] 2022-07-25 07:08
The root cause of this issue is that jobservice called AccessoryManager.List() while accessories are not imported therefor not registered in jobservice:
* https://github.com/goharbor/harbor/blob/main/src/pkg/accessory/manager.go#L126

this issue should be resolved by this PR:
* https://github.com/goharbor/harbor/pull/17231

**Closed** 2022-07-26 02:31 UTC
Labels: priority/high, area/gc, target/2.6.0
