### ISSUE TITLE
Harbor login through docker login....

### ISSUE THREAD

**Issue by sada2406** [goharbor/harbor#9945] opened 2019-11-20 14:58 UTC
I can login through http://server-ip but cannot login with docker cli as docker login and when i try i throws below message(with https):
 Get https://156.119.56.118/v1/users/: dial tcp server ip x.x.x.x:443: connect: connection refused
Docker version 1.13.1,docker-compose version 1.7.1

Please advise...........

**Comment by sada2406** [comment] 2019-11-20 15:11
Thanks to stackoverflow i add insecure registry entry in daemon file and i can login now successfully

**Comment by wy65701436** [comment] 2019-11-21 04:52
It seems not an issue of harbor, I'll close it as `not a bug`.

**Closed by wy65701436** 2019-11-21 04:52 UTC
