### ISSUE TITLE
could harbor consider to support sub-project?

### ISSUE THREAD

**Issue by elianka** [goharbor/harbor#538] opened 2016-07-14 01:54 UTC
now harbor only support one-level project, such as`ip/project/image:tag`, 
sometimes we want to set a sub folder to classify images, such as`ip/project/moduleA/image:tag`.
official registry is ready for that, so could harbor consider to support this?

**Comment by xiaods** [comment] 2016-07-14 02:12
hi @elianka which docs related the sub namespce support? please clarify, thanks a lot.

**Comment by reasonerjt** [comment] 2016-07-14 03:17
@elianka I think essentially you are asking for another level of permission?

IMO, the issue of permission model is that it's difficult to get one model that fits different users, a good model for user A maybe redundant for user B.  
And we don't currently have a good way to make permission model flexible/pluggable

**Comment by elianka** [comment] 2016-07-16 13:41
@xiaods i don't know whether there are a doc about this, meanwhile, you could compare the implementation of namespace in docker HUB and Harbor.

@reasonerjt actually, i am not asking for another level of permission, and i just want to have a more fine-grained repository structure.

**Comment by guntherboeckmann** [comment] 2016-10-17 17:32
We'd like to see this required feature implementing soon. This is useful in complex environment with many Images being created at same time.
By now, we don't need levels of permissions but in future will be nice!

**Comment by xaleeks** [comment] 2020-11-19 05:58
dupe of https://github.com/goharbor/harbor/issues/10159

**Closed by xaleeks** 2020-11-19 05:58 UTC
Labels: backlog
