### ISSUE TITLE
Replication job not show correct error when credential error

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#9055] opened 2019-09-11 05:45 UTC
in harbor 1.9.0

1. setup 2 harbor instance
2. add registry on harbor1, without credential
3. add replication job harbor1, to copy from 1 to 2
4. job will failed, but in event log it shows success icon
![image](https://user-images.githubusercontent.com/188115/64671061-d29b7900-d499-11e9-91ab-0f84c34f07f4.png)
![image](https://user-images.githubusercontent.com/188115/64671209-42116880-d49a-11e9-942f-8d167d50a67a.png)

**Comment by bitsf** [comment] 2020-03-11 08:47
This event log is a browser based cache, seems some UI side issue @jwangyangls

**Comment by jwangyangls** [comment] 2020-03-11 09:52
The current local event design for replication is only the success or failure when starting the replication task, and the specific asynchronous waiting result is not reflected in the local event. @xaleeks , do you think this design is more reasonable, or have other good ideas.

**Comment by jwangyangls** [comment] 2020-03-11 09:53
So for now this is not a bug

**Comment by steven-zou** [comment] 2020-05-20 09:09
As no further action, let's close this issue now.

**Closed by steven-zou** 2020-05-20 09:09 UTC
Labels: area/job-services, area/replication, candidate/2.0, needs/triage
