### ISSUE TITLE
建议增加镜像的描述信息，如dockerfile，run的启动脚本等。

### ISSUE THREAD

**Issue by muercy** [goharbor/harbor#2746] opened 2017-07-12 02:41 UTC
查看镜像时，如果有dockerfile和启动方面信息展示，就太好了，方便镜像的内部传播和使用，减少沟通成本，更方便管理

**Comment by reasonerjt** [comment] 2017-07-13 11:52
the issue is, we don't have a build engine, so there's no way to  ensure the consistency between image and docker file.

**Comment by whulyx** [comment] 2017-07-18 07:00
哈哈我也觉得有个Dockerfile会效果更好。

**Comment by wangycc** [comment] 2017-08-18 11:03
cool

**Comment by reasonerjt** [comment] 2018-10-10 07:36
This should be mitigated after introducing the "history" of an image.

**Comment by reasonerjt** [comment] 2019-06-05 05:39
Without further a due I'm closing this issue given user can see "history" of an image from UI.

**Closed** 2019-06-05 05:39 UTC
Labels: backlog, kind/requirement
