### ISSUE TITLE
Dockerhub proxy return http-code 500 to client ( rate-limit ?) 

### ISSUE THREAD

**Issue by aladjadj** [goharbor/harbor#14803] opened 2021-05-05 12:51 UTC
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
We have regularly an http-code 500 when an image is pulled from proxy-cache (dockerhub)

**Steps to reproduce the problem:**
Our Harbor setup is docker-compose shared bettween 6 aws ec2 with S3 backend. 
Our CI , CD and Kubernetes use this proxy. 
In the lot of calls, we have Kubernetes must be scale and pull ISTIO image from proxy cache, in this case, more than 1000 calls can be fire on proxy and we have "docker login" http-code 4xx

**Versions:**

- harbor version: 2.1.3
- docker engine version: 19.03.15
- docker-compose version: 1.21.2

**Additional context:**
- **Slack Thread**: https://cloud-native.slack.com/archives/CC1E09J6S/p1618235991164400
- **Log**: differents docker login failure

`core[9023]: 2021-04-12T07:41:14Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"unknown: login to dockerhub error: Post \"https://hub.docker.com/v2/users/login/\": EOF"}]}`

`core[9894]: 2021-05-05T12:38:33Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"unknown: login to dockerhub error: login to dockerhub error: {\"detail\": \"Failed to generate login session. Please try again later.\", \"error\": true}\n"}]}`

` core[9894]: 2021-05-05T12:38:35Z [ERROR] [/lib/http/error.go:54]: {"errors":[{"code":"UNKNOWN","message":"unknown: login to dockerhub error: login to dockerhub error: \u003c!doctype html\u003e\n\u003chtml lang=\"en\"\u003e\n\n\u003chead\u003e\n    \u003cmeta charset=\"utf-8\"\u003e\n    \u003ctitle\u003e404 : Docker\u003c/title\u003e\n    \u003cmeta name=\"viewport\" content=\"width=device-width, initial-scale=1\"\u003e\n    \u003cstyle\u003e\n    * {\n        line-height: 1.2;\n        margin: 0;\n    }\n\n    html {\n        color: #71859d;\n        display: table;\n        height: 100%;\n        text-align: center;\n        width: 100%;\n    }\n\n    body {\n        background: #fff;\n        display: table-cell;\n        font-family: \"HelveticaNeue-Light\", \"Helvetica Neue Light\", \"Helvetica Neue\", Helvetica, Arial, \"Lucida Grande\", sans-serif;\n        font-weight: 300;\n        margin: 2em auto;\n        vertical-align: middle;\n    }\n\n    a {\n  ...`

**Comment by CptDaniel** [comment] 2021-05-05 14:19
We're seeing this the last few hours. In some cases, it works and in other cases, the login request just returns the default error page from docker hub.

**Comment by cbcos** [comment] 2021-05-05 14:29
Hi, I am pretty sure this is a duplicate of #14802

**Comment by aladjadj** [comment] 2021-05-06 09:53
@cbcos for sure last day we have perturbation due to Dockerhub incident, but we have also errors since more one month

**Closed** 2021-05-10 04:06 UTC
