### ISSUE TITLE
docker 20.10 pull proxy cache image failed: Error response from daemon: missing or empty Content-Type header

### ISSUE THREAD

**Issue by morlay** [goharbor/harbor#13740] opened 2020-12-11 05:01 UTC
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

should pull proxy cache repo images success.

but docker 20.10 pull proxy cache repo images got  error `missing or empty Content-Type header`

**Steps to reproduce the problem:**
 
```bash
# docker.io is a proxy cache project
docker pull ${HARBOR_HOST}/docker.io/library/alpine:3.12
Error response from daemon: missing or empty Content-Type header
```
logs of docker desktop for mac

![image](https://user-images.githubusercontent.com/1667873/101866924-042b5480-3bb5-11eb-9ef8-5b040cf766a2.png)

works well with docker 19.03.x
normal project works well

**Versions:**
Please specify the versions of following systems.

- harbor version: v2.1.1-5f52168e
- docker engine version: 20.10

**Comment by alfsch** [comment] 2020-12-11 08:54
I get the same with docker  ce 18.06.3

```
docker --version
Docker version 18.06.3-ce, build d7080c1

docker pull my-harbor-domain/dockerhub/library/alpine:3.12
Error response from daemon: missing or empty Content-Type header

```

**Comment by stonezdj** [comment] 2020-12-11 09:50
I can reproduce this issue, the current proxy missed the Content-Type and Content-Length header in the HEAD response. they are checked in Docker CE 20.10.

**Comment by outime** [comment] 2020-12-14 16:31
I can also reproduce this issue and it's a showstopper. Hope it gets merged soon!

**Comment by cesar-moya** [comment] 2020-12-14 21:58
I'm having the same issue, is there an ETA for this fix to go in?

**Comment by bhartsfield** [comment] 2020-12-14 22:42
Reproduced in Docker version 20.10.0, build 7287ab3

**Comment by mohsen0** [comment] 2020-12-18 13:01
Thanks for the quick response, but this is not a closed issue if the fix is not released yet.

**Comment by tobiashochguertel** [comment] 2020-12-21 08:24
Maybe helpfully, I have this issue also with MacOS Big Sur, Version 11.1 (20C69)

```
0 hochguertelto@de-dus-nb-toh:~
$ docker --version
Docker version 20.10.0, build 7287ab3
```


I tried it from a virtual machine which I had around me, an quickly installed docker.io (version: `Docker version 19.03.8, build afacb8b7f0`), logged me into the registry and tried a docker pull from the proxy-cache project which I created an that worked.

Good to know that this isn't a registry /harbor specific error! because I had this error a few hours ago, also with a different container registry (pulp 3 / pulp_container: https://github.com/pulp/pulp_container).

```
root@vmi424806:~# apt install docker.io
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  bridge-utils cgroupfs-mount containerd pigz runc ubuntu-fan
Suggested packages:
  ifupdown aufs-tools docker-doc rinse zfs-fuse | zfsutils
The following NEW packages will be installed:
  bridge-utils cgroupfs-mount containerd docker.io pigz runc ubuntu-fan
0 upgraded, 7 newly installed, 0 to remove and 0 not upgraded.
Need to get 69.3 MB of archives.
After this operation, 333 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://asi-fs-n.contabo.net/ubuntu focal/universe amd64 pigz amd64 2.4-1 [57.4 kB]
Get:2 http://asi-fs-n.contabo.net/ubuntu focal/main amd64 bridge-utils amd64 1.6-2ubuntu1 [30.5 kB]
Get:3 http://asi-fs-n.contabo.net/ubuntu focal/universe amd64 cgroupfs-mount all 1.4 [6,320 B]
Get:4 http://asi-fs-n.contabo.net/ubuntu focal/main amd64 runc amd64 1.0.0~rc10-0ubuntu1 [2,549 kB]
Get:5 http://asi-fs-n.contabo.net/ubuntu focal/main amd64 containerd amd64 1.3.3-0ubuntu2 [27.8 MB]
Get:6 http://asi-fs-n.contabo.net/ubuntu focal-updates/universe amd64 docker.io amd64 19.03.8-0ubuntu1.20.04.1 [38.9 MB]
Get:7 http://asi-fs-n.contabo.net/ubuntu focal/main amd64 ubuntu-fan all 0.12.13 [34.5 kB]
Fetched 69.3 MB in 2s (30.7 MB/s)
Preconfiguring packages ...
Selecting previously unselected package pigz.
(Reading database ... 102747 files and directories currently installed.)
Preparing to unpack .../0-pigz_2.4-1_amd64.deb ...
Unpacking pigz (2.4-1) ...
Selecting previously unselected package bridge-utils.
Preparing to unpack .../1-bridge-utils_1.6-2ubuntu1_amd64.deb ...
Unpacking bridge-utils (1.6-2ubuntu1) ...
Selecting previously unselected package cgroupfs-mount.
Preparing to unpack .../2-cgroupfs-mount_1.4_all.deb ...
Unpacking cgroupfs-mount (1.4) ...
Selecting previously unselected package runc.
Preparing to unpack .../3-runc_1.0.0~rc10-0ubuntu1_amd64.deb ...
Unpacking runc (1.0.0~rc10-0ubuntu1) ...
Selecting previously unselected package containerd.
Preparing to unpack .../4-containerd_1.3.3-0ubuntu2_amd64.deb ...
Unpacking containerd (1.3.3-0ubuntu2) ...
Selecting previously unselected package docker.io.
Preparing to unpack .../5-docker.io_19.03.8-0ubuntu1.20.04.1_amd64.deb ...
Unpacking docker.io (19.03.8-0ubuntu1.20.04.1) ...
Selecting previously unselected package ubuntu-fan.
Preparing to unpack .../6-ubuntu-fan_0.12.13_all.deb ...
Unpacking ubuntu-fan (0.12.13) ...
Setting up runc (1.0.0~rc10-0ubuntu1) ...
Setting up bridge-utils (1.6-2ubuntu1) ...
Setting up pigz (2.4-1) ...
Setting up cgroupfs-mount (1.4) ...
Setting up containerd (1.3.3-0ubuntu2) ...
Created symlink /etc/systemd/system/multi-user.target.wants/containerd.service → /lib/systemd/system/containerd.service.
Setting up ubuntu-fan (0.12.13) ...
Created symlink /etc/systemd/system/multi-user.target.wants/ubuntu-fan.service → /lib/systemd/system/ubuntu-fan.service.
Setting up docker.io (19.03.8-0ubuntu1.20.04.1) ...
Adding group `docker' (GID 118) ...
Done.
Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
docker.service is a disabled or a static unit, not starting it.
Processing triggers for systemd (245.4-4ubuntu3.3) ...
Processing triggers for man-db (2.9.1-1) ...
```

```
root@vmi424806:~# docker --version
Docker version 19.03.8, build afacb8b7f0
```

```
root@vmi424806:~# docker login container.pkg.hochguertel.work
Username: admin
Password:
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

```
root@vmi424806:~# docker pull container.pkg.hochguertel.work/poxy_cache/goharbor/harbor-core:dev

dev: Pulling from poxy_cache/goharbor/harbor-core
cdb190998d3b: Pull complete
d91c489731df: Pull complete
68c36fb1e259: Pull complete
6e0130cce78a: Pull complete
6456e9078439: Pull complete
588a9373c66e: Pull complete
6624c76fa28c: Pull complete
676a488dc323: Pull complete
ecb7241aaeff: Pull complete
44378739e84c: Pull complete
Digest: sha256:5ac1ba27aeacca7442d198e10e3809e9c7357b549d2f9450c43ef9cb9919461c
Status: Downloaded newer image for container.pkg.hochguertel.work/poxy_cache/goharbor/harbor-core:dev
container.pkg.hochguertel.work/poxy_cache/goharbor/harbor-core:dev
```

**Comment by jkupcho** [comment] 2020-12-21 21:36
Is there a workaround to this for now while the patch is created?

**Comment by morlay** [comment] 2020-12-22 08:25
should fixed when 2.1.3 released

i build arm version with this patch https://github.com/querycap/harbor/blob/master/.hack/patch.sh#L5 
see https://github.com/querycap/harbor

**Comment by unki** [comment] 2020-12-28 06:45
@morlay thanks for providing a fixed image.

But may I suggest to release this fix as soon as possible - maybe as a minor update for `v2.1.2`? Every new harbor-user is currently stumbling over it and may spend ages figuring out what is wrong before finding this issue here...

**Comment by morlay** [comment] 2020-12-30 02:31
@unki this is already fixed by #13828

just waiting for `v2.1.3` releasing. but I don't know when.

cc @stonezdj @reasonerjt @ywk253100

**Comment by lihongjie0209** [comment] 2021-01-01 14:43
just downgrade docker to 18.x

for example, in debian

- remove old version of docker
```
sudo apt-get remove docker docker-engine docker.io containerd runc
```

- find suitable version
```
root@master1:/home/lihongjie/k8sdemo# apt-cache madison docker-ce
 docker-ce | 5:20.10.1~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:20.10.0~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.14~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.13~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.12~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.11~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.10~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.9~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.8~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.7~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.6~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.5~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.4~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.3~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.2~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.1~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:19.03.0~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:18.09.9~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:18.09.8~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:18.09.7~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:18.09.6~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:18.09.5~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:18.09.4~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:18.09.3~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:18.09.2~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:18.09.1~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 5:18.09.0~3-0~debian-buster | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 18.06.3~ce~3-0~debian | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 18.06.2~ce~3-0~debian | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 18.06.1~ce~3-0~debian | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 docker-ce | 18.06.0~ce~3-0~debian | https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/debian buster/stable amd64 Packages
 


```

- install docker with  version

```
apt install docker-ce=5:18.09.0~3-0~debian-buster

```

**Closed** 2021-01-06 07:02 UTC
Labels: area/proxy-cache, target/2.1.3, target/2.2.0

**Comment by tobiashochguertel** [comment] 2021-01-06 16:10
Closed but not released?

I'm confused, after seeing here the issue closing and no newly created release harbor? The latest release of harbor is 24 days old. 

I think the issue is again closed by a mistake?

**Comment by stranljip** [comment] 2021-01-06 16:19
I hope that this is a sign of the imminent release of either 2.1.3 or 2.2.0 with the included bugfix? :-)

**Comment by morlay** [comment] 2021-01-07 06:05
This is closed by github hook `fix #issueid`

I believe v2.1.3 will release soon https://github.com/goharbor/harbor/issues/13833

**Comment by stranljip** [comment] 2021-01-08 05:47
I installed 2.1.3-rc1 and can confirm that the problem no longer occurs.

**Comment by hinyinlam-pivotal** [comment] 2021-01-17 03:50
I've updated the Harbor to 2.1.3 using Helm Chart:

![kubeapp-2_1_3](https://user-images.githubusercontent.com/11515280/104830380-76c8d780-58b9-11eb-8f93-3d40bfc8f10b.png)


The project "Proxy" is a cached project
![harbor-proxy](https://user-images.githubusercontent.com/11515280/104830394-9e1fa480-58b9-11eb-9558-2e0d9116ac4d.png)

`docker -v
Docker version 20.10.2, build 2291f61`

`docker pull harbor.my-domain.com/proxy/library/docker:20-dind` still yield the same missing header issue:
![docker-pull-still-missing-header](https://user-images.githubusercontent.com/11515280/104830319-b511c700-58b8-11eb-9a6e-716e6e8bc489.png)

If I pull the same image from docker hub, retag it and upload to harbor's typical normal project repo, it will success
`export IMAGE=library/docker:20-dind`
`docker pull $IMAGE && docker tag $IMAGE harbor.mydomain.com/normal-project/$IMAGE && docker push harbor.mydomain.com/normal-project/$IMAGE`

Then this one will success `docker pull harbor.mydomain.com/proxy/library/docker:20-dind`

**Comment by stonezdj** [comment] 2021-01-18 04:00
@hinyinlam-pivotal, could you please check the current version of Harbor in "About"

**Comment by savauln** [comment] 2021-02-04 06:49
This issue may reproduced, if harbor proxied over cloudflare.

**Comment by alfsch** [comment] 2021-02-04 08:34
Installed releas 2.1.3 and all problems with proxy are gone. Great work, thanx.

**Comment by himabindu07** [comment] 2021-09-30 19:48
I can reproduce this issue, the current proxy missed the Content-Type and Content-Length header in the HEAD response. 
Docker version 20.10.8, build 3967b7d
