### ISSUE TITLE
Notary server & signer Failed to create a new keydbstore: pq: unknown authentication response: 10 

### ISSUE THREAD

**Issue by InderpreetSaini** [goharbor/harbor#16135] opened 2021-12-17 08:40 UTC
Hi,

I am trying to deploy harbor 2.4.0 using Helm charts as per steps at https://goharbor.io/docs/2.4.0/install-config/harbor-ha-helm/

For external Postgres DB, I am deploying the postgres cluster as per steps from https://access.crunchydata.com/documentation/postgres-operator/5.0.4/quickstart/ 

After deploying the harbor Helm chart, my notary server and signer pods are crashing and not getting into Running state.
![image](https://user-images.githubusercontent.com/17871520/146514743-ddc21763-94c6-47cf-8c1a-f39d73383ee8.png)
 
In the notary signer and server pods, I am seeing the below error:
Notary signer:
![image](https://user-images.githubusercontent.com/17871520/146514859-1fdeb529-db4a-4573-91ed-bc619a3351e7.png)

Notary server:
![image](https://user-images.githubusercontent.com/17871520/146515043-1ff55da2-3bb2-4529-a0b6-b441df9dc9b9.png)

Any help to overcome this issue is highly appreciated.

**Comment by ElioLopez** [comment] 2022-03-25 12:05
Hello @InderpreetSaini, I've had the same problem as you, but using a vanilla Postgresql DB version 14 (latest available on bitnami) and found out that the problem was the DB version, seems like harbor don't support postsgresql 14
you can use the following manifest to install postgres 13 with the crunchy operator:
```
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: pgo-test-cluster
spec:
  image: registry.connect.redhat.com/crunchydata/crunchy-postgres:ubi8-13.5-0
  postgresVersion: 13 
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi  
  backups:
    pgbackrest:
      image: registry.connect.redhat.com/crunchydata/crunchy-pgbackrest:ubi8-2.36-0
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1G
```

**Comment by InderpreetSaini** [comment] 2022-03-28 09:28
Thanks @ElioLopez. Will try that.

**Comment by bbroniewski** [comment] 2022-05-01 10:49
Just use some tool to hash your password with md5 (postgres uses also username to hash) and when you do it, then alter the user like:
```
ALTER USER test WITH PASSWORD 'md5c4c2d8de69efb9041d37711fe303a3dd'
```

Then password will be stored as MD5 encrypted and all pods will work.

**Comment by wy65701436** [comment] 2022-06-17 02:48
hi @InderpreetSaini You can close it if the above comments helps, and I don't have the external Pg environment like yours to have a reproduce.

**Comment by zer0def** [comment] 2022-06-17 04:14
As mentioned by Elio, this situation replicates on pg>=14, so will either require spinning up new pgdata or [upgrading passwords](https://www.postgresql.org/docs/14/auth-password.html).

**Closed** 2022-06-17 16:01 UTC
Labels: area/notary

**Comment by InderpreetSaini** [comment] 2022-06-17 16:03
Thanks @ElioLopez @bbroniewski @wy65701436 @zer0def . This issue can be marked as closed.

**Comment by zer0def** [comment] 2022-08-09 04:54
It's important to mention that while the issue has been closed, the underlying cause has not been resolved.
