### ISSUE TITLE
Create or edit endpoint will fail if using http protocol. 

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#5486] opened 2018-08-02 08:50 UTC
docker: 18
docker-compose:1.19

Try to use http to create a endpoint. Input value according the following value. 

![image](https://user-images.githubusercontent.com/4946616/43573370-2ba855a0-9674-11e8-9450-ea2c28bd8a0d.png)
![image](https://user-images.githubusercontent.com/4946616/43573387-32fdaa80-9674-11e8-93c1-213593545b25.png)

It will response:
failed to ping target

**Comment by xiaodeer** [comment] 2018-08-28 02:43
If it can been fixed now?

**Comment by ywk253100** [comment] 2018-08-28 07:00
@xiaodeer This is caused by configuring the wrong `Endpoint URL`, `https://domain_name` should be used if the target serves with HTTPS.

**Comment by xiaodeer** [comment] 2018-08-28 07:48
My harbor use http, so should we must use the https? If http did not work until 1.7 release?

**Comment by ywk253100** [comment] 2018-08-28 08:06
Your remote Harbor uses `HTTP`? `HTTP` should work. If it does, please check the logs of container `ui` and `registry`.

**Comment by xiaodeer** [comment] 2018-08-28 08:25
I checked the ui.log, it is show below:
Aug 28 16:20:47 bogon ui[100688]: 2018-08-28T08:20:47Z [ERROR] [target.go:65]: failed to ping target: Head http://172.18.2.71/v2/: Get http://dk-repo.xxx.com.cn/service/token?service=harbor-registry: dial tcp: lookup dk-repo.gzs.com.cn: no such host

**Comment by ywk253100** [comment] 2018-08-28 08:38
Closing this one as new issue #5747 is opened.

**Closed by ywk253100** 2018-08-28 08:38 UTC
Labels: wontfix
