### ISSUE TITLE
Images cannot be pulled through proxy cache.

### ISSUE THREAD

**Issue by Dmitry-Dymnov** [goharbor/harbor#18170] opened 2023-02-03 10:21 UTC
Some of the images stopped pulling through the proxy cache, if we pull directly from the dockerhub, there are no problems. If we use sha256 instead of the tag, then the image is pulling.
```
# docker pull harbor.example.org/dockerhub-cache/alvrme/alpine-android-base:latest-jdk11
Error response from daemon: mediaType in manifest list should be 'application/vnd.docker.distribution.manifest.list.v2+json' not 'application/vnd.oci.image.index.v1+json'
# docker pull harbor.example.org/dockerhub-cache/nginxinc/nginx-unprivileged:alpine
Error response from daemon: mediaType in manifest list should be 'application/vnd.docker.distribution.manifest.list.v2+json' not 'application/vnd.oci.image.index.v1+json'
# docker manifest inspect nginxinc/nginx-unprivileged:alpine
no such manifest: docker.io/nginxinc/nginx-unprivileged:alpine
# docker pull nginxinc/nginx-unprivileged:alpine
alpine: Pulling from nginxinc/nginx-unprivileged
8740c948ffd4: Already exists
2a86f1a7318b: Pull complete
db592c155212: Pull complete
b50c9b2e1109: Pull complete
4238467da37a: Pull complete
bbbbcc0cfc32: Pull complete
94c0a2efa337: Pull complete
Digest: sha256:c8d526a2d731f5b84eeeb4269a7e3394a21054440262770d98cd9ffae2024505
Status: Downloaded newer image for nginxinc/nginx-unprivileged:alpine
docker.io/nginxinc/nginx-unprivileged:alpine
```
Harbor installed from the helm chart.
**Versions:**
- harbor version: 2.4.3
- docker engine version: 20.10.22
- Kubernetes Version: v1.20.12

**Comment by vovagib** [comment] 2023-02-03 10:30
I also have a similar problem with "nginx-unprivileged" image when pulling that from harbor's proxy-cache

**Comment by shoeffner** [comment] 2023-02-03 10:34
I have the same issue and was just about to report it.
Here is some information I gathered so far:

This only applies to pulling via `docker`, with `ctr` it works.
The following gives some hints:

```
$ docker buildx imagetools inspect registry.internal/dockerhub/library/ubuntu:20.04
Name:      registry.internal/dockerhub/library/ubuntu:20.04
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:4a45212e9518f35983a976eead0de5eecc555a2f047134e9dd2cfc589076a00d
           
Manifests: 
  Name:      registry.internal/dockerhub/library/ubuntu:20.04@sha256:bffb6799d706144f263f4b91e1226745ffb5643ea0ea89c2f709208e8d70c999
  MediaType: application/vnd.oci.image.manifest.v1+json
  Platform:  linux/amd64
(plus a few more)
```

Note the MediaType `application/vnd.docker.distribution.manifest.list.v2+json` as shown in the error message above.
Now, if you issue the same command against dockerhub, the MediaType is `application/vnd.oci.image.index.v1+json`:

```console
$ docker buildx imagetools inspect ubuntu:20.04
Name:      docker.io/library/ubuntu:20.04
MediaType: application/vnd.oci.image.index.v1+json
Digest:    sha256:4a45212e9518f35983a976eead0de5eecc555a2f047134e9dd2cfc589076a00d
```

If I use `docker manifest inspect`, for dockerhub there is None:
```console
$ sudo docker manifest inspect ubuntu:20.04
no such manifest: docker.io/library/ubuntu:20.04
```
while harbor adds one, but apparently with the wrong types as shown above:
```console
$ sudo docker manifest inspect registry.internal/dockerhub/library/ubuntu:20.04
mediaType in manifest list should be 'application/vnd.docker.distribution.manifest.list.v2+json' not 'application/vnd.oci.image.index.v1+json'
```

This only happens with recent ubuntu images, e.g., the last 20.04 image is ubuntu:focal-20230126 (which doesn't work) while the one before, ubuntu:focal-20221130, seems to work:
```console
$ sudo docker pull registry.internal/dockerhub/library/ubuntu:focal-20221130
focal-20221130: Pulling from dockerhub/library/ubuntu
Digest: sha256:0e0402cd13f68137edb0266e1d2c682f217814420f2d43d300ed8f65479b14fb
Status: Image is up to date for registry.internal/dockerhub/library/ubuntu:focal-20221130
registry.internal/dockerhub/library/ubuntu:focal-20221130
$ sudo docker pull registry.internal/dockerhub/library/ubuntu:focal-20230126
Error response from daemon: mediaType in manifest list should be 'application/vnd.docker.distribution.manifest.list.v2+json' not 'application/vnd.oci.image.index.v1+json'
```
It is also possible to pull from dockerhub and pushing to the registry, so this is only related to the proxy cache and seems to be an issue only with recent images.

**Comment by maksptr** [comment] 2023-02-03 10:55
I've tried to reproduce this and I have this problem too:

```
$ docker pull harbor.local/dh/nginxinc/nginx-unprivileged:alpine
Error response from daemon: mediaType in manifest list should be 'application/vnd.docker.distribution.manifest.list.v2+json' not 'application/vnd.oci.image.index.v1+json'
```
I can't pull image even if it was removed from cache already.

Harbor 2.3.4 installed on k8s v1.21.5 (rancher 2.6) using harbor-helm 1.7.4.

**Comment by stonezdj** [comment] 2023-02-05 04:08
I can pull all these images via Harbor 2.7.0 proxy cache.

**Comment by MinerYang** [comment] 2023-02-06 08:46
Please upgrade Harbor above v2.5.0.
Closed by fixed.

**Closed by MinerYang** 2023-02-06 08:46 UTC

**Comment by shoeffner** [comment] 2023-02-10 16:00
In addition to upgrading Harbor, I also had to manually trigger the garbage collection once, but now it's working again. Thanks!
