### ISSUE TITLE
Report is not shown for the re-pushed artifacts that is deleted before

### ISSUE THREAD

**Issue by steven-zou** [goharbor/harbor#11231] opened 2020-03-24 08:40 UTC
Operations:

- mkdir mybundle
- porter create 
- update the porter.yml to make sure the image path point to harbor
- porter publish
- check the bundle in console
- scan the published bundle and wait for results generated
- remove the two repos published by the porter
-  porter publish [re-publish]

The scan status of the artifacts are "Not Scanned" now

**Comment by heww** [comment] 2020-03-31 16:07
I investigated this issue and found that the scan report of the artifact will be removed if the artifact deleted and no other artifacts with the same digest exists in the system.

So in this issue when the repos published by the porter were deleted, the scan report was deleted too.

**Comment by heww** [comment] 2020-04-01 06:04
I will close this issue for it is by design.

**Closed by heww** 2020-04-01 06:04 UTC
Labels: area/interrogation-service, priority/medium, target/2.0.0
