### ISSUE TITLE
504 Gateway Time-out  - redis lock failed

### ISSUE THREAD

**Issue by zhanghan12** [goharbor/harbor#11965] opened 2020-05-18 16:39 UTC
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
通过UI, 去清理镜像, 报504 Gateway Time-out, 检查 core
```
May 19 00:03:58 11.0.0.1 core[5525]: 2020-05-18T16:03:58Z [ERROR] [/common/api/base.go:200]: failed to delete tag 2020-04-30_14-18_v41: http error: code 500, message {"errors":[{"code":"InternalError","message":"Error occurred when to handle request in size quota handler: require redis lock failed: redigo: nil returned","detail":"Error occurred when to handle request in size quota handler: require redis lock failed: redigo: nil returned"}]}
May 19 00:03:58 11.0.0.1 core[5525]: 2020-05-18T16:03:58Z [ERROR] [/common/api/base.go:73]: DELETE /api/repositories/tutor/share-tutor-smix3/tags/2020-04-30_14-18_v41 failed with error: {"code":500,"message":"{\"errors\":[{\"code\":\"InternalError\",\"message\":\"Error occurred when to handle request in size quota handler: require redis lock failed: redigo: nil returned\",\"detail\":\"Error occurred when to handle request in size quota handler: require redis lock failed: redigo: nil returned\"}]}\n"}
```

**Steps to reproduce the problem:**
harbor 1.7.5 升级到 1.9.3后 , 尝试删除老的项目镜像报错,  删除新的项目镜像目前没有发现问题

**Versions:**
centos7

- harbor version: [1.9.3]
- docker engine version: [19.03.5]
- docker-compose version: [z.z.z]

**Additional context:**

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

**Comment by wy65701436** [comment] 2020-07-14 06:38
hi, @zhanghan12  can you please upgrade to latest Harbor 2.0.0? The redis lock has been deprecated from 2.0.0, so it will no be happen after update.

**Comment by rafal-prasal** [comment] 2020-07-23 04:44
I have exactly the same error every 22:00:00 and afterwards registry is unusable ;( because every push request is 504

after restart of harbor-core it runs flawlesly.

version of harbor is 1.10.3

**Comment by heww** [comment] 2020-07-23 06:04
@rafal-prasal  yes, this problem will happen the harbor-core was nterrupted (often happened after the harbor-core restarted).

Suggest upgrading to Harbor 2.0.0 because in this version the quota feature implements like this, reserve resource in Redis with expiration, compute quota usage by the database, unreserve resource in the Redis. No lock required for the digest of the blob.

**Comment by cobolbaby** [comment] 2020-10-29 07:41
Is the problem caused by a poor network? I have not encountered this problem before. 

Recently, the problem has been exposed due to poor network communication quality.

**Comment by cobolbaby** [comment] 2021-01-07 03:32
The root cause of the bug should be a concurrency problem. 

When I delete more than 6 images at the same time, the problem can be reproduced stably.

**Comment by heww** [comment] 2021-05-19 15:02
Closed as quota feature doesn't depend on the lock of Redis from v2.0

**Closed by heww** 2021-05-19 15:02 UTC
Labels: pending-for-more-info

**Comment by pptfz** [comment] 2024-08-28 03:00
harbor v1.10, encountered the same problem, want to ask if it can be solved without upgrading, we are now cleaning up some old images, some years ago, can not be deleted now, delete a single error 504

/var/log/harbor/core.log
```
Aug 28 10:53:51 192.168.32.1 core[12569]: 2024-08-28T02:53:51Z [ERROR] [/common/api/base.go:200]: failed to delete tag b1172_v20230207160729: http error: code 500, message {"errors":[{"code":"InternalError","message":"Error occurred when to handle request in size quota handler: require redis lock failed: redigo: nil returned","detail":"Error occurred when to handle request in size quota handler: require redis lock failed: redigo: nil returned"}]}
```


The following error occurs on the web page
```
<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->
```

Can this problem be solved without upgrading？
