### ISSUE TITLE
request: extend robot permissions to update individual project quotas

### ISSUE THREAD

**Issue by blancadesal** [goharbor/harbor#20463] opened 2024-05-21 08:36 UTC
This would allow us to automate user quota management in a multi-tenant scenario with thousands of users.

Currently, only regular user accounts can do this, if granted admin permissions, but this is not best-practice from a security standpoint.

In addition to enabling us to set individual quotas, this would also allow updating existing projects to a new default project quota. Changes to the default quota do not apply to existing projects, so having some means to update individual projects is necessary here too.

**Comment by Vad1mo** [comment] 2024-06-13 17:40
duplicate of  https://github.com/goharbor/harbor/issues/20076

**Closed by Vad1mo** 2024-06-13 17:40 UTC
Labels: kind/requirement, area/robot-account
