### ISSUE TITLE
复制dockerhub到harbor timeout

### ISSUE THREAD

**Issue by gopower** [goharbor/harbor#19136] opened 2023-08-09 08:11 UTC
**Versions:**
Please specify the versions of following systems.

- harbor version: v2.8.3
- docker engine version: 24.0.5
- docker-compose version: 24.0.5

### **harbor-core日志如下:**
2023-08-09T07:34:15Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: login to dockerhub error: Post \"https://hub.docker.com/v2/users/login/\": dial tcp 128.242.245.189:443: i/o timeout"}]} 
2023-08-09T07:34:47Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: login to dockerhub error: Post \"https://hub.docker.com/v2/users/login/\": dial tcp 108.160.166.137:443: i/o timeout"}]} 
2023-08-09T07:35:28Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: login to dockerhub error: Post \"https://hub.docker.com/v2/users/login/\": dial tcp 108.160.166.253:443: i/o timeout"}]} 
2023-08-09T07:36:49Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: login to dockerhub error: Post \"https://hub.docker.com/v2/users/login/\": dial tcp 199.59.148.201:443: i/o timeout"}]} 
2023-08-09T07:40:41Z [ERROR] [/lib/http/error.go:57]: {"errors":[{"code":"UNKNOWN","message":"unknown: login to dockerhub error: Post \"https://hub.docker.com/v2/users/login/\": dial tcp 185.60.219.41:443: i/o timeout"}]} 

![image](https://github.com/goharbor/harbor/assets/96470241/95010964-7f7d-442a-bc79-faaf59f11f85)

![image](https://github.com/goharbor/harbor/assets/96470241/d25804cf-b389-4247-bb41-adcdb4d2b0e5)

**Comment by long1318737396** [comment] 2023-08-09 08:29
这个就是超时了185.60.219.41:443 国内连接docker官方本来网络就差

**Comment by chlins** [comment] 2023-08-09 09:34
The error message indicates that this is caused by instability between your environment network and DockerHub, you should consider resolving your network issue or use proxy.

**Closed** 2023-08-14 08:20 UTC
