### ISSUE TITLE
replication feature needed -- allow project admin to do it.

### ISSUE THREAD

**Issue by sinycn** [goharbor/harbor#2333] opened 2017-05-18 04:20 UTC
hi:
    in my org,replication is very often， when new replication is needed  they must email harbor admin to add, so i think if it possible to give the privileges for project admin? it will improve  User Experience.tks

**Comment by reasonerjt** [comment] 2017-05-18 05:56
@sinycn Thanks for the request, technically is easy, but I'm really hearing quite a few different opinions on that, I don't think we can make quick update to support your request.

Leaving it open for future discussion.

**Comment by walkamongus** [comment] 2019-04-16 15:52
#689 makes the same request

**Comment by xaleeks** [comment] 2020-11-19 04:57
dupe of https://github.com/goharbor/harbor/issues/13538

**Closed** 2020-11-19 04:57 UTC
Labels: area/replication, backlog, kind/requirement
