### ISSUE TITLE
gc cron job log only show the latest job log

### ISSUE THREAD

**Issue by zhoumeina** [goharbor/harbor#7692] opened 2019-05-07 08:48 UTC
set a custom gc job. Use cron:* /5* * * * *. 
It generate a job log the first time. 
![image](https://user-images.githubusercontent.com/4946616/57286458-d41df480-70e7-11e9-90c4-3a53e286a3b0.png)
After several minutes, when it run the second time. The log changed to :
![image](https://user-images.githubusercontent.com/4946616/57286507-f1eb5980-70e7-11e9-833d-e962e3b2ebdf.png)
It is really confused users.

**Comment by wy65701436** [comment] 2019-05-08 06:23
It's actually as designed so far.

As the limitation of jobservice in v1.7.0, it has no way for the caller to distinguish schedule and it's execution, the GC just use one record to report the latest instance.

But, the problem has been resolved recently by introducing a new definition(Execution) in jobservice. As we're reaching the release, it's not a bug or shipping blocker but an enhancement, I prefer to defer and put it into v1.9.0 candidate.

**Comment by reasonerjt** [comment] 2019-05-08 09:13
We may defer it b/c this is actually an enhancement rather than a bug.

**Comment by wy65701436** [comment] 2021-08-10 02:06
as GC has been moved to task/schedule model, close it as fixed.

**Closed by wy65701436** 2021-08-10 02:06 UTC
Labels: kind/requirement
