### ISSUE TITLE
Consider supporting sigstore for OCI images.

### ISSUE THREAD

**Issue by smekkley** [goharbor/harbor#9996] opened 2019-11-25 22:57 UTC
Docker notary is at the moment not well integrated with harbor. For example, signed images cannot be deleted from GUI.

With Redhat solutions like podman, buildah gradually gaining popularity, probably more people will use skopeo image signing.

With skopeo, signing happens with gnupg and generate a signature file locally. For verification, clients can specify http endpoint or local directory containing the signature files. No notary-server nor notary-signer needed.

First, it would be nice if we could see which images are signed or not like the current implementation, but check the signature from external web server.

In the future maybe it's good if harbor optionally supports hosting https storage for such signature files for upload and download.

**Comment by bitsf** [comment] 2019-11-29 10:13
It is by design that signed images not allowed be deleted. I think we need more discussion from community that whether this design is reasonable.
We use notary is because docker client support this directly which most people using docker client.
But we also realized that notary has some important defects, especially can't replicate between multi-regions, recently the docker maintainer also show a new idea to redefine notary in Kubecon.

We also have discussed some ideas about signing in harbor without notary, something like using gpg.

The idea that user should see which images are signed is reasonable, only the problem is the performance, maybe we can cache this info in next release that we'll save many metadata in database.

I think hosting storage is not the purpose of harbor now, it's not easy to implement a safety and high available storage unless integrate some other open source projects, users can still use something like s3 storage. Maybe a user-defined redirect link in harbor configure file is enough.

**Comment by smekkley** [comment] 2019-12-03 17:01
By the way, I was inspired by this. It looks like plain gpg. https://developers.redhat.com/blog/2019/10/29/verifying-signatures-of-red-hat-container-images/
I'm not sure what skopeo copy does when remove signature is not specified. They say signature gets copied to the remote server which is only supported by atomic. I'll see how heavy signature verification is.

**Comment by xaleeks** [comment] 2019-12-30 07:59
@smekkley  some of these are being addressed by the next iteration of docker notary.  The disallow deleting these signed images from GUI is by design.

**Comment by kmmanto** [comment] 2020-08-11 06:53
Any updates on this? It would be great to have supprt for buildah image signing.

**Comment by bitsf** [comment] 2020-09-09 10:07
@kmmanto You can use create folder `/var/lib/containers/sigstore/library` with sudo first, and give write permission to user. 
or maybe change this default storage folder, but I'm not sure how to do.

**Comment by wy65701436** [comment] 2022-08-04 07:15
I believe that we can close it since Harbor now supports cosign for signing image.

**Closed** 2022-08-04 07:15 UTC
Labels: kind/requirement, area/artifact-signature
