### ISSUE TITLE
Error message in callback should be consistent with the Harbor UI

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#12740] opened 2020-08-11 12:16 UTC
<img width="938" alt="Screen Shot 2020-08-11 at 11 31 48 AM" src="https://user-images.githubusercontent.com/2696760/89895797-fc5fa180-dc0e-11ea-926a-6071f712cdbd.png">

The callback just return a json, it should be consistent with the Harbor UI, it is better to redirect to an error page with the common UI style or go to the login page with the erorr message displayed.

**Comment by reasonerjt** [comment] 2020-08-11 13:05
This has been reviewed couple of times and this should rarely happen in the real scenario.  
There's no such error page for Harbor, which may require extra cycle for design.  I hope we can defer this problem.
@xaleeks thoughts?

**Comment by ywk253100** [comment] 2020-08-17 08:26
Closing as this is by design

**Closed by ywk253100** 2020-08-17 08:26 UTC
Labels: needs/triage, target/2.1.0
