### ISSUE TITLE
Trying to pull down latest release via github api does not give latest version 2.0.4

### ISSUE THREAD

**Issue by szahri** [goharbor/harbor#13699] opened 2020-12-08 00:11 UTC
Hi there,
I am testing with bit of code to pull the latest tarball from goharbor and install/update Harbor.
However I notice that using github api to get the latest tagged release, I am getting the older version (v1.10.6) instead of v2.0.4 (which I assume is the latest stable version) :

`$curl -L -s https://api.github.com/repos/goharbor/harbor/releases/latest | grep -i tag_name`
 `"tag_name": "v1.10.6",`

Why I am getting the older version and not v2.0.4? Is there a reason for this and a way for me to get the real latest stable version via github api?

Thanks

**Comment by sluetze** [comment] 2020-12-08 07:34
Hi,
the reason is, that github takes the "latest" release as the one which was published last. Since Harbor maintains 3 Branches (1.10.x, 2.0.x, 2.1.x) the latest release will be the last published release of any of these branches.

if you want to get the latest 2.0.x version it may be useful to implement the version logic in your script.

so
1. curl on curl -L -s `https://api.github.com/repos/goharbor/harbor/releases`
2. get the latest 2.0.x version via jq (you can use created_at / published_at and the tag-name or name for that
3. download the version you chose

**Comment by reasonerjt** [comment] 2020-12-14 10:33
Closing as the problem is solved.

**Closed by reasonerjt** 2020-12-14 10:33 UTC
Labels: help wanted
