### ISSUE TITLE
Creating a robot account through api generates a ne secret even though 'secret' field is populated

### ISSUE THREAD

**Issue by sfenzke** [goharbor/harbor#16884] opened 2022-05-19 11:57 UTC
**Expected behavior and actual behavior:**
#### expected behavior
Creating a robot account through the API should use the provided secret if the 'secret' field is populated in the requests JSON body.

#### actual behavior
Creating a robot account through the API generates a new secret even though the 'secret' field is populated in the requests JSON body.

**Steps to reproduce the problem:**
Creating a robot through the API with a populated 'secret' field in JSON body. 

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.4.2
- docker engine version: 20.10.16
- docker-compose version: 1.25.0

**Example JSON**
```
{
  "name": "replication2",
  "secret": "mysecret",
  "disable": false,
  "level": "system",
  "duration": -1,
  "description": "Robot Account für Replikation",
  "permissions": [
    {
      "access": [
        {
          "action": "push",
          "resource": "repository"
        },
        {
          "action": "pull",
          "resource": "repository"
        },
        {
          "action": "delete",
          "resource": "artifact"
        },
        {
          "action": "read",
          "resource": "helm-chart"
        },
        {
          "action": "create",
          "resource": "helm-chart-version"
        },
        {
          "action": "delete",
          "resource": "helm-chart-version"
        },
        {
          "action": "create",
          "resource": "tag"
        },
        {
          "action": "delete",
          "resource": "tag"
        },
        {
          "action": "create",
          "resource": "artifact-label"
        },
        {
          "action": "create",
          "resource": "scan"
        },
        {
          "action": "stop",
          "resource": "scan"
        },
        {
          "action": "list",
          "resource": "artifact"
        },
        {
          "action": "list",
          "resource": "repository"
        }
      ],
      "kind": "project",
      "namespace": "*"
    }
  ]
}
```

**Comment by AllForNothing** [comment] 2022-05-20 04:32
@sfenzke This is by design. You can not specify the secret when creating a robot account.
If you want to do so, you need to:
1. Create a robot first  (post     `api/v2.0/robots`)
2. Specify the secret to the robot created in step1 (patch  `api/v2.0/robots/${robot_id}`  with request body `{secret: "your_secret"}`)

**Comment by sfenzke** [comment] 2022-05-20 05:25
Thanks for clarification. Is this documented somewhere and Ii missed it? If not I think this should be added to the documentation because it is kind off surprising behavior.

**Comment by AllForNothing** [comment] 2022-05-20 07:15
I thank the `Refresh System Robot Account Secret` section of the  [doc](https://goharbor.io/docs/2.5.0/administration/robot-accounts/) contains the related info

**Comment by wy65701436** [comment] 2022-05-23 07:26
as @AllForNothing mentioned, it's by designed, close it.

**Closed by wy65701436** 2022-05-23 07:26 UTC
