### ISSUE TITLE
Unable to Migrate from one OIDC Teanant to Another

### ISSUE THREAD

**Issue by KISStian** [goharbor/harbor#10485] opened 2020-01-14 18:28 UTC
Our organization recently migrated from one Auth0 tenant to another.  The back-end authentication system remained the same, but the Auth0 OIDC endpoint was changed.   We were able to update the OIDC configuration to point to the new tenant, but we are no longer able to authenticate via OIDC.  Error messages are received indicating that the user name already exists while it tries to onboard the existing user.

Is there any way to let Harbor know that the OIDC user that exists in the system is the same as the one trying to log in?  I attempted to update the oidc_user table within the registry database by changing the subiss field so that it reflects the new tenant, but this did not work.

**Comment by reasonerjt** [comment] 2020-01-15 05:34
@KISStian 

I wish to say it's a bit problematic if the OIDC provider map different subject to same user.

However, I do think updating `subiss` SHOULD fix this problem as it's the key Harbor used internally to identify OIDC user.  I will double check and reproduce to let you know.

**Comment by KISStian** [comment] 2020-01-15 14:48
@reasonerjt After digging into this further I noticed that the sub field of the ID token actually changed when me migrated tenants.  When I used the current value, it allowed the user to log in without issue.  The only problem is that this requires a mass database update to ensure all existing users can do the same.  Maybe a feature request could be to allow users to specify a custom key for OIDC authentication.  This will prevent issues for others when migrating from one OIDC provide to another.

**Comment by reasonerjt** [comment] 2020-01-21 07:48
@KISStian 
I'm sorry but I don't think generally speaking"migrating OIDC provider" is a valid use-case.  What does it mean to migrate from Gmail to facebook?
Since the problem of the OP is resolved, I'm closing this issue.
If you want to raise the requirement could you please write up another issue to better describe the scenario.  
We may consolidate the requirement and make update to the design, but it may not be not very high priority.

**Closed** 2020-01-21 07:48 UTC
Labels: area/oidc
