### ISSUE TITLE
harbor 2.0 user can get a bearer token even credencial is wrong

### ISSUE THREAD

**Issue by bitsf** [goharbor/harbor#11632] opened 2020-04-15 13:25 UTC
curl -u admin:asdfdsf "https://10.184.85.205/service/token?scope=repository%3Alibrary%2Fmariadb%3Apull&service=harbor-registry"

![image](https://user-images.githubusercontent.com/188115/79342328-919fa180-7f5f-11ea-8f81-4fc486a09f32.png)

docker hub will fail
![image](https://user-images.githubusercontent.com/188115/79342367-9f552700-7f5f-11ea-8aa2-7e63de082c31.png)

**Comment by reasonerjt** [comment] 2020-04-15 13:28
This is by design, as the token can be used to access public resource.

**Comment by bitsf** [comment] 2020-04-15 13:47
but when I use a scope not exists, it also return a token

**Comment by bitsf** [comment] 2020-04-15 13:47
harbor 1.10.2 has the same behavior too, so this is not introduced by 2.0

**Comment by reasonerjt** [comment] 2020-04-16 03:25
It's also expected if you decode the token, you'll see the token's scope is also empty.

**Comment by reasonerjt** [comment] 2020-04-21 03:20
Closing as it's working as designed.

**Closed by reasonerjt** 2020-04-21 03:20 UTC
Labels: needs/triage, target/2.0.0, wontfix
