### ISSUE TITLE
500 Internal Service Error when pushing OCI manifest

### ISSUE THREAD

**Issue by Elegant996** [goharbor/harbor#11328] opened 2020-03-27 02:32 UTC
**Expected behavior and actual behavior:**
Images created using `oci` format are pushed to `harbor` registry.

Currently, images built using `oci` format fail citing `500 Internal Service Error` when pushed.

**Steps to reproduce the problem:**
Build an image using `oci` format (`podman` with `buildah` will do this by default). Push the new image to the `harbor` registry. Watch as the push fails when handling the OCI manifest:

```
Writing manifest to image destination
DEBU[0000] PUT https://harbor.svc.example.com/v2/library/testapp/manifests/latest
DEBU[0000] Writing manifest using preferred type application/vnd.oci.image.manifest.v1+json failed: Error writing manifest: Error uploading manifest latest to harbor.svc.example.com/library/testapp: received unexpected HTTP status: 500 Internal Server Error
ERRO[0000] Error copying image to the remote destination: Error writing manifest: Error uploading manifest latest to harbor.svc.example.com/library/testapp: received unexpected HTTP status: 500 Internal Server Error
```

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.1]
- podman version: [1.8.2]

**Additional context:**

Originally thought this issue to be related to `podman` but after switch the build format, it was determined to be a `harbor` issue. Citing the initial `podman` issue below for reference.

containers/libpod#5619

**Comment by wy65701436** [comment] 2020-03-27 02:45
In v1.10.1, it's a as designed. From v2.0, Harbor will support OCI manifest

**Comment by xaleeks** [comment] 2020-05-05 06:21
I'm closing this since this is unsupported for the version detailed, please check latest 2.0 release which delivers this capability

**Closed by xaleeks** 2020-05-05 06:21 UTC
