### ISSUE TITLE
After migration, a cron string of "scan all" job in DB appears to be invalid.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#8526] opened 2019-08-01 05:47 UTC
A user tried to upgrade 1.7.5 -> 1.8.1
After the migration, this API returns 500:
`“GET /api/system/scanAll/schedule`
The error message in `harbor-core`:
`failed to convert admin job response: unsupported cron format, {"type":"none"}` 
We checked the database by executing the sql command:
`select * from admin_job where delete=false`
Then we found this record causing the problem:
`59 | IMAGE_SCAN_ALL | Periodic | {"type":"none"} | pending | | 2019-07-20 04:58:24.064678 | 2019-07-20 04:58:24.064678 |`
And the `{"type":"none"}` failed to parse.
We execute the sql command: 
`update admin_job set deleted = true where id = 59;`
to delete the job and after that, everything works fine.

The real reason why this record was inserted need to be investigated, it seems due to migration SQL:
https://github.com/goharbor/harbor/blob/release-1.8.0/make/migrations/postgresql/0004_1.8.0_schema.up.sql#L177

But let's try to reproduce and investigate what could be wrong in this case

**Comment by wy65701436** [comment] 2019-08-01 07:12
Did some investigation on this

[Root Cause]
If the user disables the scan_all policy in v1.7.5 or older, it will set the schedule value to `{"type":"none"}` and store it into table properties. And, the data is moved to table admin_job after migrating to v1.8.*, then harbor converts it to a standard cron string, like {"type":"Daily","cron":"0 1 5 * * *"}, for job service use.

In this case, the data converter doesn't handle well for `{"type":"none"}`, which leads to scan_all API cannot understand the schedule data, and throw the 500 error.

[Fix]
Mark the schedule(`{"type":"none"}`) as delete in table admin_job.

[Manual Workaround]
update admin_job set deleted = true where icron_str = '{"type":"none"}';

I will add the PR link in the issue.

**Comment by wy65701436** [comment] 2019-08-01 08:10
PR to fix: https://github.com/goharbor/harbor/pull/8531

**Comment by wy65701436** [comment] 2019-08-01 10:28
Close it as fixed.

**Closed by wy65701436** 2019-08-01 10:28 UTC
Labels: area/upgrade, kind/bug, target/1.8.2
