### ISSUE TITLE
Failed to export CVEs on any OIDC account

### ISSUE THREAD

**Issue by nevlkv** [goharbor/harbor#18184] opened 2023-02-07 09:52 UTC
Harbor 2.6.3

OIDC  - gitlab
 If user with admin permissions try to export CVEs via UI

results
![изображение](https://user-images.githubusercontent.com/46656585/217210254-80cfde7c-b34e-47e7-8fbb-3354c30ac929.png)

core pod logs:

```
2023-02-07T09:49:16Z [ERROR] [/server/middleware/security/oidc_cli.go:62][requestID="8acdd8dbdfe2f98449bf51a78f3fb613"]: failed to verify secret, username: ui, error: failed to get oidc user info, error: <QuerySeter> no row found
2023-02-07T09:49:16Z [ERROR] [/server/middleware/security/basic_auth.go:72][client IP="10.101.254.93" requestID="8acdd8dbdfe2f98449bf51a78f3fb613" user agent="docker-registry-ui"]: failed to authenticate user:ui, error:not supported
2023-02-07T09:49:16Z [ERROR] [/server/middleware/security/oidc_cli.go:62][requestID="c76569cb8fc28b3d419feb9d8ce439c7"]: failed to verify secret, username: ui, error: failed to get oidc user info, error: <QuerySeter> no row found
2023-02-07T09:49:16Z [ERROR] [/server/middleware/security/basic_auth.go:72][client IP="10.101.254.93" requestID="c76569cb8fc28b3d419feb9d8ce439c7" user agent="docker-registry-ui"]: failed to authenticate user:ui, error:not supported

```

if used internal admin account, always success

**Comment by MinerYang** [comment] 2023-02-13 08:11
closed by duplicate of this https://github.com/goharbor/harbor/issues/18112

**Closed by MinerYang** 2023-02-13 08:11 UTC
