### ISSUE TITLE
Cosign accessory of an artifact currently can be GC-ed individually

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#16434] opened 2022-02-28 11:52 UTC
step to reproduce:
1. push an artifact
2. cosign
3. delete accessary of the artifact
4. run GC with untagged
5. harbor vm tree /data/registry/docker/registry/v2  the revision and blob of the accessary manifest are both deleted (GC-ed) while the blob and manifest of the artifact still exist.
=> cosign accessary signature data is currently GC-ed individually

Is this the expected behavior?

**Comment by wy65701436** [comment] 2022-03-03 05:35
close it by designed.

**Closed by wy65701436** 2022-03-03 05:35 UTC
Labels: area/gc, target/2.5.0, area/cosign
