### ISSUE TITLE
Can not delete user login with oidc

### ISSUE THREAD

**Issue by annProg** [goharbor/harbor#8424] opened 2019-07-26 08:05 UTC
I use `dex` as `oidc provider`. when delete a user from `dex`. user can not login harbor dashboard, but  can still  use `docker` command. I can't delete user in harbor dashboard

![image](https://user-images.githubusercontent.com/4145852/61935918-1a377580-afbe-11e9-9997-b857185d0499.png)

**Comment by reasonerjt** [comment] 2019-07-28 16:55
@annProg This is by design, currently in Harbor any non-local user can't be removed after on-boarded.

**Comment by reasonerjt** [comment] 2019-08-16 07:26
closing as wontfix

**Comment by kkzxak47** [comment] 2019-08-16 09:52
Hi, We encountered similar issue with Keycloak. After deleting the user inside keycloak and recreate one with the same name, the user will not be able to login to harbor with oidc anymore. We have to delete the user in harbor or it's locked out forever. I guess the only option is to drop the harbor user in db directly.

**Comment by verwilst** [comment] 2019-08-27 08:30
How is this a wontfix? We're having the same issue as @kkzxak47 , where we have a couple of test users that are now stuck there forever, and a person who entered his full name instead of his username. Both can't be deleted/renamed ( and i can't seem to find it in the postgres db so delete/rename manually).  An option to delete the 'local' copy in Harbor would be much appreciated. Whenever the user logs in again through OIDC, a new user can be created.

**Comment by verwilst** [comment] 2019-08-27 08:54
Found a workaround which hopefully doesn't break anything else ;-) :
```
\c registry
delete from oidc_user where user_id = xx;
delete from harbor_user where user_id = xx;
```

**Comment by Popsiclestick** [comment] 2019-10-01 16:50
This is a valid issue. Those running harbor with any auth method need the ability to remove the locally made users. `wontfix` does not feel like the appropriate conclusion to this issue. OIDC seems to have limited functionality all throughout harbor.

**Comment by wmgroot** [comment] 2019-10-01 19:04
I agree with verwilst's complaints that there isn't a valid workflow to recreate or change attributes about users who are created via OIDC. I don't think manually modifying values in postgres is intended to be the canonical workflow to address these issues. I think the need for this feature is simple and valid, and should be revisited.

**Comment by Hokwang** [comment] 2019-10-07 05:30
I experienced same situation.
I am using harbor with keycloak for oidc,
for test, I remove my id in keycloak and create again,
after then, I can not log in harbor and admin can not remove user id.
I think harbor can accept username already created,
and admin can remove user id, there's no problem.

**Comment by verwilst** [comment] 2019-11-22 13:05
Can this be re-opened?

**Comment by adityanmishra** [comment] 2019-11-25 22:47
we also experienced the same problem. What is happening is harbor is prompting the user to set a user name for first login when connecting to OIDC not with the actual username from username and they keep forgetting their username. When we go to harbor not able to delete it.

**Comment by claesenm** [comment] 2020-01-20 19:57
We have the exact same problem as @verwilst. A feature to delete onboarded users in the local DB would be very useful.

**Comment by jonhatallasf** [comment] 2020-02-04 23:56
For compliance purposes, this could cause issues with auditors

**Comment by n0rig** [comment] 2020-03-24 19:24
same issue; can't delete user that is non-existent anymore.

**Comment by MelwinKfr** [comment] 2020-04-21 11:43
I also had the issue, in my case I migrated our users to another issuer, their uuid changed but not the email/username. So I just needed to update the `subiss` column of the table `oidc_user` to retrieve my users. Luckily for me I only had 10 users to change... 

1st run:
`select h.user_id, o.subiss, h.email from harbor_user h inner join oidc_user o on o.user_id = h.user_id;`

then for every user:
`update oidc_user set subiss = 'the-new-user-uuidhttps://mynewissuer.com/auth/realms/myrealm' where user_id = 13;`

**Comment by reasonerjt** [comment] 2020-05-24 10:25
Guys, the problem is there's disconnection between Harbor's DB and the ID provider.  Allowing admin to remove a user, when that removal happens, the user may still exists in the ID provider.  We need to consider the case after `jack` is removed from Harbor's DB, what if the user `jack` login via OIDC provider again?

**Comment by reasonerjt** [comment] 2020-05-24 10:43
Sorry for the late response.

If you still have some idea in terms of how we should improve this part, please open a new issue.

**Comment by xaleeks** [comment] 2020-05-27 10:30
@reasonerjt why don't we just discuss on this ticket, I'm reopening to work this through. 

The reason why this we don’t allow deleting non-local users is there is no way to tell the difference btw user being deleted on the OIDC side or they just entered the wrong credentials.  That information doesn’t come through to us on the token, Dex is just fronting for the authn back-end even and it just handle connecting harbor with the back-end.  So if we allow deleting on harbor, that would be problematic if it was actually someone else attempting to login.  I think most of the users are wanting to delete a username that they mistyped but that will be mitigated by this PR where we don’t provide them with that option, the username is taken directly from the OIDC provider - https://github.com/goharbor/harbor/pull/9311

What if we create a UX workflow that allows user to confirm deleting in Harbor but they bear the responsibility of re-adding that user to all the projects and so on if they accidentally deleted the wrong user

**Comment by MelwinKfr** [comment] 2020-05-27 10:47
> What if we create a UX workflow that allows user to confirm deleting in Harbor but they bear the responsibility of re-adding that user to all the projects and so on if they accidentally deleted the wrong user

I was thinking about the same workflow when I wanted to delete my users.

IMHO, if someone is struggling with project permissions after deleting a user AND have OIDC enabled. This person would better need to configure and manage permissions using groups rather than recovering from a previous user profile.

**Comment by wmgroot** [comment] 2020-05-27 14:04
I understand that user will be removed from all projects, and all of their permissions will be reset. That isn't a problem for me, because our project permissions are group-based, so nothing depends directly on the user.

If I'm already having to remove users from the database directly (potentially for compliance reasons after an employee leaves, as jonhatallasf mentions), why not simplify the process with a confirmation box that warns the user?

**Comment by rhuitl** [comment] 2020-05-28 16:55
> Guys, the problem is there's disconnection between Harbor's DB and the ID provider. Allowing admin to remove a user, when that removal happens, the user may still exists in the ID provider. We need to consider the case after `jack` is removed from Harbor's DB, what if the user `jack` login via OIDC provider again?

That's simple: the user is recreated. This request is about a feature for Harbor-Admins to clean up after testing, possibly after deleting the test user on the ID provider, or to re-test the onboarding workflow without creating a new user on the ID provider.

It is not about a way for users to change their username.

It feels like a rather arbitrary decision to not allow admins remove users in Harbors database only because they have been provisioned through OIDC.

**Comment by rhuitl** [comment] 2020-06-15 13:16
AFAIK, when you have OIDC users, you have two ways of handling permissions:
1. Map a claim to groups
2. Manually add users to projects

I don't know if you store the group membership in the Harbor database. It doesn't seem to be necessary as the token will contain the claims and it's not really needed to duplicate this information. When membership changes on the IP side, the next time the user logs in (*), Harbor will see the updated group membership.

Actually you wouldn't even have to store an OIDC user in your database, even though it has the advantage of enabling (2) and allows picking a different username for Harbor.

I understand that with LDAP, the situation is different, because you can pull a list of users and that will reflect users deleted on the LDAP side. However, again AFAIK, I don't think there is a way to do this with OIDC (please correct me if I'm wrong!) - when a user is deleted on the OIDC IP, there is no way for the OIDC client to learn about this.

Therefore, I think you may not be able to keep the LDAP and OIDC flows exactly the same.

*) When changing claims on the ID side (in my case Keycloak), a user has to log into Harbor again before the new claims take effect. I did not investigate this too much, my current recommendation for our users is to log into Harbor again using an incognito browser window. This updates the group membership and even the non-incognito session picks up the new permissions.

**Comment by n0rig** [comment] 2020-06-22 19:33
I also echo the sentiment of https://github.com/goharbor/harbor/issues/8424#issuecomment-634683478 (@wmgroot) because we are not mapping users directly to a project; rather, we are using keycloak groups to handle this.

At t0, when a new user signs up, the user is requested to create an internal user within harbor; I don't know if this is necessary if the username (in this case a company email address) can be used from OIDC.

Anyway, if I were to go through and delete the user on the keycloak side (just for testing), harbor will not let the user log back in (I suppose because the UUID changed).

So, I ran into this scenario above while initially configuring all the OIDC groups and harbor projects to work properly.

In order to fix stale users, I had to run the following many times to delete non-existent users so that the real ones could log in via Keycloak. For my setup, keycloak is in an identity brokering mode so it does not directly manage any user credentials; it is handled by an IT managed authoritative Azure AD service.

**Step 1: log into the database container**
```bash
# Get the pod name
POD_NAME=`kubectl get pods -n harbor --output=json | jq -r -j '.items[].metadata | select(.name | startswith("database")) | .name'`
 
# Log into the pod
kubectl exec -it -n slr-system $POD_NAME -- bash
 
# Drop into the postgres sql cli
psql -U postgres
 
# Follow commands below.
# Examples:
#    username == Some.User
#    user_id  == 0
```

**step 2: delete the user, throughout the db tables, via the user_id**
```bash
\c registry

# Determine user_id
select user_id from harbor_user where username = 'Some.User';
 
# 
# Use user_id from previous step to delete the user across all the tables;
# e.g. replace owner_id = 0, user_id = 0, entity_id = 0 sections with the correct user_id
#
delete from project where owner_id = 0;
delete from oidc_user where user_id = 0;
delete FROM project_member where (entity_id = 0 AND entity_type = 'u');
delete from harbor_user where user_id = 0;
```

Anyway, the fact that I have to do the above is crazy as OIDC/LDAP allow this to be decoupled; I would rather give the authz configuration take precedence and let keycloak tell harbor what the user/group has access to. The guidance should be that a global identifier should be used for the user; in my case, an immutable global identifier is an employee's email address.

So, ideally, in each webui view we would check if the user is logged in via harbor local database, ldap, or if there is a JWT from OIDC (e.g. no local username is required AFAIK).

**Comment by dkulchinsky** [comment] 2020-10-09 13:09
I'd like to reiterate @n0rig, this issue is still a concern for us as we're working toward rolling out Harbor into production use, we have quite large organization and we need the ability to remove stale accounts as well as fix/handle any issues that may arise during onboarding or rejoining of an employee.

I think there's also an issue here with project's ownership, if an IDP authenticated user created a project and is no longer enrolled into the IDP, Admins should have a way to transfer his project(s) ownership to another user, AFAICT this can only be done today by raw DB updates.

**Comment by reasonerjt** [comment] 2020-10-16 10:35
@dkulchinsky I don't think you are talking about the same scenario as @n0rig 
As for ownership, a project owner is the user who created the project, when a owner leaves admin can assign another project admin, so I don't think we need to transfer to ownership.  In other words, you may think of `owner` as `creator` of a project.

**Comment by reasonerjt** [comment] 2020-10-16 10:37
@n0rig 

> 
> At t0, when a new user signs up, the user is requested to create an internal user within harbor; I don't know if this is necessary if the username (in this case a company email address) can be used from OIDC.

If my understanding is correct, it's some internal process within your company, and I don' think it's necessary if you use OIDC auth mode.

**Comment by dkulchinsky** [comment] 2020-10-16 12:24
@reasonerjt thanks for your comment, can you share how can I transfer a project "creator" role to another user?

with regard to the other concerns, I think they are still valid, it's fairly common for users to leave and later join back the company, at which point they get the same username in idp but with different sub claim, so they won't be able to get onboarded (we tested this scenario).

**Comment by jmichelgarcia** [comment] 2020-10-19 12:43
This issue is 1+ year old, so for what its worth, this is my current use case.

When a **developer has left the company**
I want to **offboard developers from Harbor** (in addition to offboarding them in Github)
So that my **Harbor users list reflects the reality** of who has access to the system

```gherkin
Given an employee has left a developer team
When I remove him from the relevant Github group
And I remove him from the relevant Harbor group
Then I don't see his name anymore in Harbor
```

**Comment by bogdanalov-sw** [comment] 2020-11-19 13:02
What is the point of having delete user option when it is not usable? Either fix it or remove it... It just confuses the people. IMO this should be added.

**Comment by footplus** [comment] 2021-02-03 16:08
I have the same use-case than @jmichelgarcia.

I would be happy with an UI that allows to just delete an user that owns no projects, and allows to transfer projet owner_id to another user to keep the relational DB happy.

**Comment by bsctl** [comment] 2021-03-02 17:00
@reasonerjt what about provide a cli command to remove safety a deleted OIDC user from the db?

**Comment by ant31** [comment] 2021-03-03 12:29
They can't login anymore but does all the robot account and other cli-credential removed also? 
1. It seems not, I can remove a user access from the OIDC, but since it still exist in the databse he would have access to it. 
2. It's against law at least in EU,  any user can request to delete information about them in  **every** IT system. Removing only access to harbor while keeping a record of them in the database is not an option. 

Having to workaround directly in the Database isn't a good option and if many people express the same need, maybe there's one ! 
A small cli that would do that as suggested by @bsctl would work great.

**Comment by verwilst** [comment] 2021-03-03 12:37
I honestly don't get why this issue is such a problem to resolve. :-) Allow admins to delete the oidc-created user, if that user later logs in again, just recreate it. Easy peasy!

**Comment by thegasmann** [comment] 2021-04-08 16:25
+1 from me.
It has to be possible to delete a user account, at least when the user has disappeared from ldap.

This is important to be compliant with the GDPR where user accounts have to be deleted (or anonymized) after a certain time after the user has left the organisation.
Thanks to @n0rig for the instructions to remove the user directly from the database - but there should be a working api call

**Comment by bsctl** [comment] 2021-04-08 16:45
@reasonerjt any update on this?

**Comment by kkzxak47** [comment] 2021-04-12 02:24
“You can check out anytime you like but you can never leave”

**Comment by bsctl** [comment] 2021-04-12 02:48
> “You can check out anytime you like but you can never leave”

Welcome to the Hotel California

**Comment by sebas-w** [comment] 2021-04-28 13:22
2 year old issue still not solved and no breath of progress from the developers, this doesn't look like it will get traction anytime soon. It seems Harbor isn't going to be GDPR compliant and that raises the question "Is it even fit for usage in production?"

Harbors front page says "Our mission is to be the trusted cloud native repository for Kubernetes". If that's true, then they should give admins the ability to remove non-local users so we can control access in a cloud native way.

**Comment by rhuitl** [comment] 2021-04-28 13:27
Harbor is an amazing product that we use in production. It works really VERY well. This issue here is an extreme outlier.

**Comment by dkulchinsky** [comment] 2021-04-28 15:29
> Harbor is an amazing product that we use without any major issues in production. It works really VERY well. This issue here is an extreme outlier.

@rhuitl thank you for saying that ☝🏼  and going to say I completely agree! I think this project has a very dedicated team that are doing a lot of work to improve and enhance the product and we highly appreciate all their work and support! ❤️ 

we may have some disagreements and I tend to agree with the overall ask here to be able to easily drop OIDC users if needed, our concern is not GDPR related but actually a real corner case where a user left the company and later came back and couldn't get onboarded since a user with the same email (but different `sub` id) already existed, we were able to work around that and it's a rare corner case.

but in the end, there's a team that drives the project and need to make decisions, we may disagree but the right approach is to share our opinion in a respectful way and I think overall the team has an open mind.

**Comment by bsctl** [comment] 2021-04-28 17:19
@dkulchinsky 

> Harbor is an amazing product

yes, we agree with this, no doubts here

> our concern is not GDPR related but actually a real corner case

GDPR compliance is a real common case in the European Union and that issue prevents to use this amazing product.

**Comment by dkulchinsky** [comment] 2021-04-28 17:30
> GDPR compliance is a real common case in the European Union and that issue prevents to use this amazing product.

I understand that, perhaps it's worth raising this issue on the weekly community calls.

**Comment by sebas-w** [comment] 2021-05-03 15:16
@dkulchinsky  

It's my belief that being honest and frank is respectful. I don't disagree that Harbor is a great product, but no traction on a 2 year old issue is upsetting from a perspective of those of us users that face this real corner case more often than you'd think. It doesn't give users confidence that this issue and issues like this will be resolved anytime soon.

Not being able to handle this in an automated fashion means unnecessary manual intervention to resolve when it does come up and in the case of the env it's hosted in on my side, this is quite an involved process.

**Comment by ant31** [comment] 2021-05-27 18:02
@dkulchinsky was the issue raised? any update on this one ?

**Comment by dkulchinsky** [comment] 2021-05-28 00:41
> @dkulchinsky was the issue raised? any update on this one ?

I was not on the call so can't comment on that.

**Comment by thegasmann** [comment] 2021-05-28 12:45
@sebas-w : Agreed. I would really like to see a reaction on the topic, even if it was a "won't do"

**Comment by lindhe** [comment] 2021-05-31 15:45
> This is by design, currently in Harbor any non-local user can't be removed after on-boarded.

It would be very interesting to see the discussion regarding that design decision, and see what we can do about it. I've tried looking around for design documents, but I have failed to find any. If @reasonerjt or someone else can point me in the right direction, that would be much appreciated!

Clearly this is a desired feature for many Harbor users, and I see no reason for this being _the right design_ per se. On the contrary, I can think of multiple good reasons for changing this design. So perhaps we can have a discussion about it here and try to figure out a better way forward. But that requires attention from at least one maintainer that can speak up on behalf of the project.

We would be happy to contribute with improvements, but doing so without the maintainers' blessing would be somewhat a waste of time. So I hope we can discuss it first just to know we're aiming in a viable direction.

**Comment by stonezdj** [comment] 2021-07-02 02:58
We could solve this issue by 
1. Enable delete user button for other auth_mode 
2. Remove the user from  the project member
3. Delete the user's OIDC token-related info when auth_mode is oidc_auth. 
4. "Soft delete" the user from harbor_user.

If the deleted user created a project before, the project exists after the owner deleted,  and the admin could manage its privileges.

**Closed** 2021-07-14 05:25 UTC
Labels: needs/triage

**Comment by jxsl13** [comment] 2022-01-27 08:32
our ldap has hiccups occasionally deleting users from keycloak and recreating them again leading to them not being able to use Harbor anymore due to changed user ids. fiddling around in thedatabase seems to be a bad solution for this problem.
Would be nice if it was easier to delete users from oidc.

**Comment by Vad1mo** [comment] 2022-04-13 07:14
FYI From version 2.4 on Harbor supports deleting OIDC user.

**Comment by maheshsmartcow** [comment] 2022-06-20 11:26
I am able to delete the harbor user which is onboarded from OIDC (Keycloak) but its manual process. Isn't like deleting a user from keycloak for harbor client deletes from harbor database itself ? why admin has to delete the user from harbor explicitly ?
