### ISSUE TITLE
Use personal token to push images

### ISSUE THREAD

**Issue by ephracis** [goharbor/harbor#6305] opened 2018-11-19 12:31 UTC
I have successfully deployed Harbor and connected it to LDAP and I can push images to it by doing:

```
docker login ... # enter ldap creds
docker push ...
```

Now I want my CI pipeline to do the same. But I don't want to save my LDAP-password anywhere. Instead I would like to generate a token and use that in CI to push images.

is this possible?

**Comment by steven-zou** [comment] 2018-11-20 05:17
@ephracis 

  Unfortunately, we don't have token/robot account to well support CI/CD pipeline at present. But we have started to consider to enhance the supporting of the DevOps process now.

**Comment by nlowe** [comment] 2018-11-27 17:56
Possible duplicate of #4591

**Comment by reasonerjt** [comment] 2019-03-05 06:53
This should be covered by the `robot account` which is targeted for 1.8.0

**Comment by reasonerjt** [comment] 2019-06-05 07:39
Closing as this requirement is addressed by robot account, which has been delivered in v1.8

**Closed by reasonerjt** 2019-06-05 07:39 UTC
Labels: area/devops-support, enhancement, kind/requirement, requirement/status/reviewing
