### ISSUE TITLE
Documentation links leads to 404 error page

### ISSUE THREAD

**Issue by prasad15** [goharbor/harbor#10645] opened 2020-02-05 09:36 UTC
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Clicking on Documentation link redirects to 404 page instead of actual docs page.

**Steps to reproduce the problem:**
The [UserGuide Doc](https://github.com/goharbor/harbor/blob/master/docs/user_guide.md) asks go to this [link](https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md) which in turn redirects to a 404 error page.

**Versions:**
Harbor 1.10 docs

- harbor version: [1.10]

**Comment by bitsf** [comment] 2020-02-05 13:28
@xaleeks please help deal with document issue

**Comment by rowersteven** [comment] 2020-02-05 15:17
Error trying to see 1.10 documentation 
https://github.com/goharbor/harbor/blob/master/docs/1.10/index.md.

**Comment by rowersteven** [comment] 2020-02-07 01:23
Every topic link is broken in 
https://github.com/goharbor/harbor/blob/master/docs/1.10/index.md.

**Comment by catlook** [comment] 2020-02-07 15:47
Do you have an expected resolution time frame?  I'd love to be able to link to your docs in mine!

**Comment by rowersteven** [comment] 2020-02-07 15:59
Thanks for the response. I need to look at the documentation about Harbor replication functions quite urgently. It will be great if the documentation page can be restored completely over the next couple days.

**Comment by bitsf** [comment] 2020-02-11 02:24
@rowersteven  I think you can reference old doc, it's nothing different for replication
https://github.com/goharbor/harbor/blob/v1.10.0/docs/user_guide.md#replicating-resources

**Comment by bitsf** [comment] 2020-02-11 02:25
@reasonerjt can you also help check who can fix this document asap, this would be quite bad experience for users after release.

**Comment by rowersteven** [comment] 2020-02-11 05:02
@bitsf thank you Ziming for the URL. It serves my need for the time being, yet please help urge a fix of the documentation web page soonest.

**Comment by bitsf** [comment] 2020-02-11 06:52
pr #10693 and #10695 seems help fix this

**Comment by bitsf** [comment] 2020-02-11 08:07
this seems already be fixed
url https://github.com/goharbor/harbor/blob/master/docs/installation_guide.md and https://github.com/goharbor/harbor/tree/master/docs/1.10 is working now

**Comment by stuclem** [comment] 2020-02-11 08:14
@bitsf @rowersteven @reasonerjt this happened during a general overhaul of the docs, and it has now been fixed. The redirects in the old doc pages now point to https://github.com/goharbor/harbor/tree/master/docs/1.10, where you can access the new doc table of contents.

**Comment by rowersteven** [comment] 2020-02-11 11:05
Very disappointing, click topic links give you 404 error.

**Comment by catlook** [comment] 2020-02-11 13:12
And why does the index file not have a TOC and serve as the root of the doc?

**Comment by rowersteven** [comment] 2020-02-11 14:04
@bitsf @stuclem the issue is not yet fixed. You select any link in the ToC  https://github.com/goharbor/harbor/tree/master/docs/1.10 and all return 404 :-(

**Comment by stuclem** [comment] 2020-02-11 14:29
@rowersteven @catlook I see what you mean. It seems that all of the files have been renamed to use hyphens instead of underscores, again as a part of the big doc overhaul.

There is already a PR open to fix this: https://github.com/goharbor/harbor/pull/10661

**Comment by stuclem** [comment] 2020-02-12 09:59
@rowersteven @catlook  https://github.com/goharbor/harbor/pull/10661 is now merged, and I it looks like the TOC is now working again: https://github.com/goharbor/harbor/tree/master/docs/1.10

**Comment by rowersteven** [comment] 2020-02-12 11:11
Hurray! It works now! Thanks a lot @stuclem

**Comment by stuclem** [comment] 2020-02-12 12:14
@rowersteven you're welcome (although @jonasrosland is the one who fixed it). Apologies for the inconvenience, but we're going through a major overhaul of the docs, which is still ongoing. Hopefully we won't have any more glitches like this. We hope that you will appreciate the difference when we roll out the final version of the new doc.

**Closed** 2020-02-12 12:14 UTC

**Comment by rowersteven** [comment] 2020-02-13 04:16
Sorry to raise this again but it seems pictures in document are not displayed. E.g. docs/1.10/administration/configuring-replication/create-replication-rules.md
