### ISSUE TITLE
Scan all status is hung after migration from 1.8 to 1.10

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#9963] opened 2019-11-22 03:21 UTC
Test Steps:
    1. Deploy harbor 1.8.5;
    2. Set Scan all shedule to 12 12 12 * * *;
    3. Wait more than 12 minutes;
    4. Update harbor to 1.10;
    5. View page of "Interrogation Services";
Result:
    Page is in scan waiting status for long time.

**Comment by danfengliu** [comment] 2019-12-09 08:52
![image](https://user-images.githubusercontent.com/44018302/70421177-4a327180-1aa4-11ea-9766-17704700af27.png)

**Comment by steven-zou** [comment] 2019-12-10 06:05
en? 

This is very weird. Total is 0 but ongoing is true.

@AllForNothing which property you're using to disable the button?

**Comment by AllForNothing** [comment] 2019-12-10 10:43
on

> en?
> 
> This is very weird. Total is 0 but ongoing is true.
> 
> @AllForNothing which property you're using to disable the button?

ongoing

**Comment by reasonerjt** [comment] 2019-12-11 02:27
Let's be clear that this issue is because the Harbor is shutdown while the job is running and the interrupted job is blocked after Harbor is started.

So it does not only impact upgrading.

**Comment by danfengliu** [comment] 2019-12-11 02:29
@reasonerjt Yes, it's upgrade regardless.

**Comment by steven-zou** [comment] 2019-12-11 08:17
I think the issue can be generalized to the case that, if there is a Redis restart when lots of jobs are in progress, there might be cause job loss issues. Once the jobs could not be recovered, the status data in the database will be out of sync and look like `hung` there.

**Comment by steven-zou** [comment] 2019-12-11 08:25
@stuclem @xaleeks 

Could we add release notes for such known issues?

>If there are jobs are still running in the job service, and a Redis restart happened with any reasons (power outage, crash etc.), job loss issues may happen. That would cause status out of sync issues that appeared in the scan, replication or GC scenarios. As result, some status will be like `hung` there, no change anymore.

**Comment by stuclem** [comment] 2019-12-11 08:26
@steven-zou yes of course. Added the `kind/note` label.

**Comment by renmaosheng** [comment] 2019-12-12 01:30
@steven-zou we also need to mention the workaround when this happens.

**Comment by michmike** [comment] 2019-12-12 01:42
what's the workaround and is it something that happens automatically or someone has to manually execute it?

**Comment by michmike** [comment] 2019-12-12 01:45
does this "hung" issue happen 100% on each upgrade?

**Comment by steven-zou** [comment] 2019-12-12 01:56
@michmike 

No. It will happen only and only if there are jobs are running and then Redis restart occurs for any reason. Most of the time, when users doing their upgrading, there will not be jobs running.

I'll continue to do investigate this issue. The possible root cause is data loss happens after Redis restarts.

Current plan is we can deliver a fix in the patch release 1.10.X.

**Comment by steven-zou** [comment] 2019-12-12 01:57
The workaround approaches will be noted in the FAQ list.

**Comment by michmike** [comment] 2019-12-12 05:08
comments after discussion:
-This is not a new issue
-data loss could be: in progress jobs in the queue. jobs could be replication, scanning, GC
....However, replication will be eventually consistent on the next replication
....scanning is safe since next scan will work. for new images, policy will prevent them from being pulled until they are scanned

i think we are fine to release with this ticket and fix it in the next patch release. this is not data loss, because Harbor is eventually consistent based on user intent.  A redis cache restart (for whatever reasons) will chase the same effects and Harbor will be eventually consistent.

**Comment by stuclem** [comment] 2019-12-13 08:16
Added to the RNs, so removing `kind/note`: https://github.com/goharbor/harbor/releases/tag/v1.10.0#known-issues

- **Scan status freezes after migration from 1.8 to 1.10 [#9963](https://github.com/goharbor/harbor/issues/9963)**  <br>If there are jobs running in the job service, and a Redis restart happens, for example because of a power outage or crash, `status out of sync` issues might appear in scan, replication or garbage collection tasks. Consequently, some task statuses freeze in their current state, and do not update themselves. The cause is known and this will be fixed in a patch.

   **Workaround**: Run the task again. Replication and scanning function correctly on the next run. No data is lost.

**Comment by steven-zou** [comment] 2019-12-28 04:10
It may be related to this issue in the upstream project : https://github.com/gocraft/work/issues/146

**Comment by steven-zou** [comment] 2020-01-17 09:33
The code work is done, pending for PR review.

Move to next SP 78

**Closed** 2020-01-20 08:46 UTC
Labels: area/interrogation-service, area/job-services, known-issue, target/1.10.1
