### ISSUE TITLE
Harbor API Support For Robot Accounts

### ISSUE THREAD

**Issue by niroopj** [goharbor/harbor#13036] opened 2020-09-11 06:55 UTC
Hi Team,
   When can we expect full harbor API Support for robot accounts as well?

API's like POST/DELETE Image tags.

Thanks & Regards,
  Niroop

**Comment by steven-zou** [comment] 2020-09-14 06:13
@niroopj 

Just let you know, the enhancements of robot-account is in our roadmap. Please stay tuned on the coming harbor releases.

**Comment by steven-zou** [comment] 2020-09-14 06:13
cc @wy65701436

**Comment by xaleeks** [comment] 2020-11-18 23:51
dupe of https://github.com/goharbor/harbor/issues/8723

check the APIs we are opening up to robot accounts on the upcoming v2.2 in that thread

**Closed by xaleeks** 2020-11-18 23:51 UTC
Labels: area/robot-account, kind/requirement
