### ISSUE TITLE
[OIDC] Can't delete from Harbor an old or misconfigured user

### ISSUE THREAD

**Issue by julienlefur** [goharbor/harbor#10796] opened 2020-02-20 14:43 UTC
What can we help you?

When an OIDC user has been onboarded in Harbor, it's not possible to delete it even with an admin account:
![image](https://user-images.githubusercontent.com/17261718/74944990-418cde80-53f7-11ea-9b5d-3b98b334c516.png)

2 use cases where deletion of user is mandatory:
- When the user leave the organisation, it is still registered in Harbor. 
- When a user is misconfigured (ie: the username is not what expected), it cannot be changed. 

What's expected?
Enable the "Delete" action for OIDC onboarded users.

**Comment by renmaosheng** [comment] 2020-02-24 02:09
Daojun， could you please share the steps of clean up users? thanks.

**Comment by stonezdj** [comment] 2020-02-25 02:12
You could cleanup the OIDC user with these commands:
```
docker exec -it harbor-db bash
psql -U postgres
\c registry
select * from harbor_user;
 delete from harbor_user where user_id > 2;
```
https://github.com/goharbor/harbor/wiki/Harbor-FAQs#authentication

**Comment by julienlefur** [comment] 2020-02-26 13:01
@stonezdj yes of course I can work it in the database, but it would be interesting to have it from the UI and the API as well.
As an example, when a user leave the company, we would be able to add a step in our automatic chain to request the deletion of the user from harbor instead of deleting it from the database. 
We usually never connect directly to a database of an application or system but rather use the provided APIs to be sure that the operation is consistent.
I think this issue has already been discussed here: #8424

**Comment by xaleeks** [comment] 2020-03-02 17:30
Can we think about API access for this? I also think dropping entries in the db directly is not the best way for the end user to interact with the system.

**Comment by catchups** [comment] 2020-03-09 02:54
Directly accessing the DB to delete the user does not seem to be the right way.

**Comment by stonezdj** [comment] 2020-03-11 13:31
We could enable user deletion when the auth_mode is not db_auth, and show tips that it just clean up the login information in Harbor DB.

**Comment by julienlefur** [comment] 2020-03-18 08:58
@stonezdj yes that is exactly what is expected at first.

**Comment by rhuitl** [comment] 2020-04-08 09:01
We have this issue as well. The person choose non-ASCII characters for the user name and seems to have problems using this to log in on the command line.

**Comment by xaleeks** [comment] 2020-05-27 10:15
@julienlefur this is essentially a duplicate of https://github.com/goharbor/harbor/issues/8424/  Please track progress on that ticket, we will have a better solution than forcing dropping user in DB

**Closed by xaleeks** 2020-05-27 10:15 UTC
