### ISSUE TITLE
Image scan status stays in "queued" right after scanner was switched  and scan it rappidly

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#11720] opened 2020-04-24 10:25 UTC
![image](https://user-images.githubusercontent.com/44018302/80202785-b9c28b00-8658-11ea-967a-1e473f39bcad.png)

**Comment by steven-zou** [comment] 2020-04-24 10:26
```go
2020-04-24T06:29:39Z [INFO] [/jobservice/worker/cworker/c_worker.go:74]: Job incoming: {"name":"IMAGE_SCAN","id":"897a9948ec5cedbd0696864b","t":1587709779,"args":null}
Apr 24 06:29:39 172.18.0.1 jobservice[6655]: 2020-04-24T06:29:39Z [ERROR] [/jobservice/runner/redis.go:65]: Job 'IMAGE_SCAN:897a9948ec5cedbd0696864b' exit with error: failed to get job tracker: {"code":10010,"message":"object is not found","details":"897a9948ec5cedbd0696864b"}
```

**Comment by steven-zou** [comment] 2020-04-24 10:27
The root cause might be:

  The job has been pulled by the worker but the stats of job has not been persisted into Redis DB as these two operations are performed in two methods.

**Comment by steven-zou** [comment] 2020-04-28 02:40
Code merged and cherry-picked, close this issue.

**Closed by steven-zou** 2020-04-28 02:40 UTC
Labels: area/job-services, kind/bug, target/2.0.0
