### ISSUE TITLE
The helm-charts replication doesn't work between Harbors

### ISSUE THREAD

**Issue by olhrabar** [goharbor/harbor#8131] opened 2019-06-24 16:12 UTC
**Expected behavior and actual behavior:**
The replication should be works betwean 2 harbor servers using helm-charts. But in the Harbor version 1.8.1 it doesn't wotks.

**Steps to reproduce the problem:**
1. Install Harbor v1.8.1 on the two instances (Harbor 1 and Harbor 2)
2. Add any repository on the Harbor 1
3. Push any helm-chart to the Harbor 1
4. Go to Harbor 2 and create "New Endpoint" for registry
5. Go to "Replication tab" (Harbor 2) and create "New Replication Rule" using Endpoints from step 4: look at the picture
6. Select the rule from step 5 and click "Replicate" button

Ex:
The all projects and all helm charts should be copied from Harbor 1 to Harbor 2

Act:
Only projects name was copied to Harbor2. The helm-charts is absent.

**Versions:**
Please specify the versions of following systems.
- harbor version: v1.8.1
- docker version 18.09.5, build e8ff056
- docker-compose version: 1.24.0, build 0aa5906

**Additional context:**

![Screenshot from 2019-06-24 19-08-09](https://user-images.githubusercontent.com/38593768/60034513-80756380-96b3-11e9-827d-0ba2b4ac5054.png)

Jun 24 11:49:53 10.15.16.1 core[10450]: 2019-06-24T11:49:53Z [ERROR] [/common/api/base.go:69]: GET /api/chartrepo/cr-43760/charts/status-controller/0.2.7-15-fbd8e55 failed with error: {"code":404,"message":"no chart name found"}
Jun 24 11:49:53 10.15.16.1 core[10450]: 2019/06/24 11:49:53 #033[1;44m[D] [server.go:2619] |     10.15.16.8|#033[43m 404 #033[0m|   61.73341ms|   match|#033[44m GET     #033[0m /api/chartrepo/cr-43760/charts/status-controller/0.2.7-15-fbd8e55   r:/api/chartrepo/:repo/charts/:name/:version#033[0m
Jun 24 11:49:53 10.15.16.1 core[10450]: 2019/06/24 11:49:53 #033[1;44m[D] [server.go:2619] |     10.15.16.8|#033[42m 200 #033[0m|   1.520192ms|   match|#033[44m GET     #033[0m /api/internal/configurations   r:/api/internal/configurations#033[0m
Jun 24 11:49:53 10.15.16.1 core[10450]: 2019-06-24T11:49:53Z [ERROR] [/common/api/base.go:196]: fail to get chart version: http error: code 404, message no chart name found
Jun 24 11:49:53 10.15.16.1 core[10450]: 2019-06-24T11:49:53Z [ERROR] [/common/api/base.go:69]: GET /api/chartrepo/cr-43583/charts/aws-provider/0.2.8-2-d0fd242 failed with error: {"code":404,"message":"no chart name found"}

**Comment by alexz-kh** [comment] 2019-06-25 09:02
Probably related to 
[issues-8124](https://github.com/goharbor/harbor/issues/8124)

**Comment by olhrabar** [comment] 2019-06-25 12:02
The same result with Harbor-Harbor (v1.8.0)

**Comment by loqutus** [comment] 2019-06-26 15:08
i'm having the same problem

**Comment by ywk253100** [comment] 2019-06-28 04:56
@olhrabar The screenshot you uploaded shows that the execution whose ID is 2 contains 1002 tasks, did they all failed? Could you show me the task logs?

**Comment by olhrabar** [comment] 2019-07-01 10:13
look at the logs:

[harbor_which_executed_replication_using_pull_to_enother_harbor.log](https://github.com/goharbor/harbor/files/3345050/harbor_which_executed_replication_using_pull_to_enother_harbor.log)
[harbor_which_should_get_replication_from_enother_harbor.log](https://github.com/goharbor/harbor/files/3345051/harbor_which_should_get_replication_from_enother_harbor.log)
[jobservice.log](https://github.com/goharbor/harbor/files/3345052/jobservice.log)

**Comment by olhrabar** [comment] 2019-07-01 10:15
> @olhrabar The screenshot you uploaded shows that the execution whose ID is 2 contains 1002 tasks, did they all failed? 

Yes, all was failed

**Comment by ywk253100** [comment] 2019-07-01 10:31
Got error in the logs of Jobservice:
```
Jul  1 09:40:27 10.15.1.1 jobservice[1546]: 2019-07-01T09:40:27Z [ERROR] [/jobservice/runner/redis.go:63]: |@_@| Job 'REPLICATION:c1c17e9f43aba5919f2efe6b' exit with error: Get https://harbor-test6.test.net/api/chartrepo/cr-43977/charts/openstack-provider/0.2.8-13-8771a19: dial tcp: lookup harbor-test6.test.net on 127.0.0.11:53: no such host
```

The hostname `harbor-test6.test.net` cannot be resolved.

**Comment by olhrabar** [comment] 2019-07-01 10:38
Yes I know it. This problem is came us after "harbor" installation. It is the first problem which can be resolved when edit /etc/hosts in the harbor-core.
But problem still present after this manipulation.

**Comment by ywk253100** [comment] 2019-07-04 02:38
@olhrabar Could you show me the logs of failed task? You can get it in the portal by entering the task list and client the log icon:
![tasklog](https://user-images.githubusercontent.com/5835782/60636103-b7800d80-9e47-11e9-9543-d5c2f9e44f68.png)

And also package all logs of the source and destination Harbor instances and upload them. The logs is stored under directory `/var/log/harbor` by default.

**Comment by stsuse** [comment] 2019-07-04 10:47
I have the same issue with the following error on transfer. 
![Harbor sync error](https://user-images.githubusercontent.com/46018708/60661076-74c73100-9e59-11e9-9844-0b4fbe045844.png)

**Comment by ywk253100** [comment] 2019-07-05 02:37
@stsuse Could you share me the helm chart you are replicating so that I can try it in my environment and find the root cause for that?

**Comment by stsuse** [comment] 2019-07-05 07:55
Hi

I tried the same scenario with postgresql with the same result as our internal helm charts.
2019-07-05T07:45:01Z [INFO] [/replication/transfer/chart/transfer.go:88]: client for source registry [type: harbor, URL: https://application-service-factory.connect365.net/, insecure: true] created
2019-07-05T07:45:01Z [INFO] [/replication/transfer/chart/transfer.go:98]: client for destination registry [type: harbor, URL: http://harbor-harbor-core, insecure: true] created
2019-07-05T07:45:01Z [INFO] [/replication/transfer/chart/transfer.go:132]: copying rdcap-dev/postgresql:0.9.5(source registry) to p2/postgresql:0.9.5(destination registry)...
2019-07-05T07:45:01Z [ERROR] [/replication/transfer/chart/transfer.go:162]: failed to upload the chart p2/postgresql:0.9.5: http error: code 400, message {"error":"gzip: invalid header"}


Harbor source: Version v1.8.1-16b59c41
Harbor target: Version v1.8.1-16b59c41

Both source and target are setup in Kubernetes with Harbor helm charts.

The following replication rule is setup.
[cid:image001.jpg@01D53317.B896E9A0]


Best regards.
/Stefan

Från: Wenkai Yin(尹文开) <notifications@github.com>
Skickat: den 5 juli 2019 04:38
Till: goharbor/harbor <harbor@noreply.github.com>
Kopia: stsuse <stefan.sehler@solidpark.se>; Mention <mention@noreply.github.com>
Ämne: Re: [goharbor/harbor] The helm-charts replication doesn't work between Harbors (#8131)


@stsuse<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstsuse&data=02%7C01%7Cstefan.sehler%40solidpark.se%7Cf053fed390894044901408d700f1d46d%7C8cd17d6ba88b419c865c16be53db86f1%7C1%7C0%7C636978910956261657&sdata=OLLFjM3mGTRQUdL49L7jpGCJ4w5e7XHMISZ6Vp11dck%3D&reserved=0> Could you share me the helm chart you are replicating so that I can try it in my environment and find the root cause for that?

**Comment by ywk253100** [comment] 2019-07-09 09:10
@stsuse I mean the chart that you are replicating. Could you upload it so that we can try to reproduce the issue?

@olhrabar Could you provide more information as I mentioned in comment: https://github.com/goharbor/harbor/issues/8131#issuecomment-508316655?

**Comment by stsuse** [comment] 2019-07-09 10:46
I noticed the same result with a standard chart. 

2019-07-09T10:39:11Z [INFO] [/replication/transfer/chart/transfer.go:88]: client for source registry [type: harbor, URL: https://application-service-factory.connect365.net/, insecure: true] created
2019-07-09T10:39:11Z [INFO] [/replication/transfer/chart/transfer.go:98]: client for destination registry [type: harbor, URL: http://harbor-harbor-core, insecure: true] created
2019-07-09T10:39:11Z [INFO] [/replication/transfer/chart/transfer.go:132]: copying rdcap-dev/wordpress:3.0.0(source registry) to p2/wordpress:3.0.0(destination registry)...
2019-07-09T10:39:11Z [ERROR] [/replication/transfer/chart/transfer.go:162]: failed to upload the chart p2/wordpress:3.0.0: http error: code 400, message {"error":"gzip: invalid header"}

I changed the file extension to be able to attach the helm chart. 
[wordpress-3.0.0.tgz.txt](https://github.com/goharbor/harbor/files/3372539/wordpress-3.0.0.tgz.txt)

**Comment by olhrabar** [comment] 2019-07-09 13:56
> @olhrabar Could you show me the logs of failed task? You can get it in the portal by entering the task list and client the log icon:
> ![tasklog](https://user-images.githubusercontent.com/5835782/60636103-b7800d80-9e47-11e9-9543-d5c2f9e44f68.png)
> 
> And also package all logs of the source and destination Harbor instances and upload them. The logs is stored under directory `/var/log/harbor` by default.

The logs icon is absent in my Harbor version 1.8.1

**Comment by ywk253100** [comment] 2019-07-10 02:31
@stsuse I cannot reproduce the issue in my environment.

**Comment by ywk253100** [comment] 2019-08-20 06:09
The chart replication is enhanced by https://github.com/goharbor/harbor/pull/8594 and closing this issue.

**Closed by ywk253100** 2019-08-20 06:09 UTC
Labels: kind/bug
