### ISSUE TITLE
Robot account exposure in harbor UI

### ISSUE THREAD

**Issue by drehpehs** [goharbor/harbor#10579] opened 2020-01-27 07:45 UTC
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**
Expected behavior: 
    When I access the Robot Accounts page of my project in harbor UI, I should only see my robot account only.
Actual behavior:
   I can see robot accounts for other projects in UI...
   And I think it retrieves all robot accounts with its project_id containing the current project_id.
  
**Steps to reproduce the problem:**
    If I access robot account page for project id 1, it will retrieve other robot account containing "1". for example "1*" and "*1"

**Versions:**
Please specify the versions of following systems.

- harbor version: [1.10.0]
- docker engine version: [18.09.0]
- docker-compose version: [1.24.1]

**Additional context:**
Is the api query: api/projects/{project_id}/robots using "`project_id` LIKE " sql to retrieve the robot data?

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** You can get them by package the `/var/log/harbor/` .

![Screen Shot 2020-01-27 at 4 04 45 PM](https://user-images.githubusercontent.com/16714954/73157584-c7817680-4124-11ea-8223-f8cc2fe11d0b.png)

**Comment by esantoro** [comment] 2020-01-28 09:19
Hello,
I can confirm that is issue is real. It's happening for us too, running Harbor version 1.10.

**Comment by xaleeks** [comment] 2020-02-05 02:48
@drehpehs  @esantoro  A fix is underway and will be in on the next patch release, this was due to an oversight when we refactored robot accounts implementation so image scanners can better leverage them.

**Comment by wy65701436** [comment] 2020-02-05 05:37
close it as PR https://github.com/goharbor/harbor/pull/10636 merged, will be in v1.10.1

**Closed by wy65701436** 2020-02-05 05:37 UTC
Labels: area/robot-account, target/1.10.1
