### ISSUE TITLE
Scheduled Garbage Collection fails when updating redis endpoint

### ISSUE THREAD

**Issue by czenker** [goharbor/harbor#17984] opened 2022-12-13 10:24 UTC
**Expected behavior and actual behavior:**

When using an external Redis and updating the domain, the Garbage Collection should run correctly as before. 

Garbage Collection fails with the error `exit with error: run error: error retrieving 'blobs::*' keys` and does not do any clean up. The error message is misleading, as the underlying issue is that Harbor Jobservice wants to connect to the old domain.

**Steps to reproduce the problem:**

* Install Harbor using the Helm Chart and configure an external redis under domain `harbor-redis.example.com`
* Setup a scheduled Garbage Collection via GUI and verify it works
* Migrate redis to the domain `harborjobservice-redis.example.com` and update the configuration using the Helm Chart
* Wait for the next scheduled Garbage Collection. This will fail with the error `exit with error: run error: error retrieving 'blobs::*' keys`
* Manually triggering the Garbage Collection will succeed

**Background:**

Harbor seems to persist the Redis Endpoint with the Garbage Collection configuration:
![Auswahl_216](https://user-images.githubusercontent.com/264799/207290909-b985e997-a689-4282-9ffa-9723610a47a2.png)

The domain will be used for _scheduled_ GC, but when triggering the GC manually, the correct new domain will be used and GC will succeed.

**Workaround:**

Update the Garbage Collection Schedule. This will write the new domain to the database.

**Versions:**

- harbor version: `2.6.2`
- helm chart version: `1.10.2`

**Comment by wy65701436** [comment] 2022-12-15 07:44
This is by design behavior because old domains are recorded in the database and you have to reset the schedule to bring the database up to date.

I will close it as it will not be fixed, the workaround is mentioned in the original comment and anyone with this problem can use it as a reference.

**Closed by wy65701436** 2022-12-15 07:44 UTC
