### ISSUE TITLE
Not allowed to copy all?

### ISSUE THREAD

**Issue by zyyw** [goharbor/harbor#20347] opened 2024-04-23 10:36 UTC
How can we help you?
<img width="1608" alt="Screenshot 2024-04-23 at 6 30 33 PM" src="https://github.com/goharbor/harbor/assets/6709992/6e7ee74e-37c2-49ac-96e6-a72c4d743f24">

**Comment by wy65701436** [comment] 2024-04-29 08:24
Close it by design.

**Closed by wy65701436** 2024-04-29 08:24 UTC
Labels: area/OCI, target/2.11.0
