### ISSUE TITLE
External Redis with TLS enabled is not possible to set 

### ISSUE THREAD

**Issue by lukasmrtvy** [goharbor/harbor#11331] opened 2020-03-27 07:46 UTC
Its not possible to setup external redis with TLS enabled. Thats usually problem when is Harbor deployed in Azure, AWS with external redis server with TLS enabled ( PaaS ).

**Comment by natitomattis** [comment] 2021-05-17 22:07
I'm trying to connect external elasticache redis service, but I'm having the same issue. Is it solved in any version?

**Comment by flyingbricks** [comment] 2021-06-14 18:20
@natitomattis It doesn't seem so, also see issue here: https://github.com/goharbor/harbor/issues/13223

**Comment by slushysnowman** [comment] 2022-11-17 11:23
Just to give some workaround hints for anyone struggling with this... you can add an stunnel sidecar to get around this

Is this issue a duplicate of https://github.com/goharbor/harbor/issues/13223?

**Comment by MinerYang** [comment] 2022-11-24 02:25
close by duplicate

**Closed by MinerYang** 2022-11-24 02:25 UTC
Labels: kind/requirement
