### ISSUE TITLE
Image replication doesn't carry the signature in Notary.

### ISSUE THREAD

**Issue by reasonerjt** [goharbor/harbor#2102] opened 2017-04-21 08:24 UTC
When an image is replicated from a Harbor instance deployed with notary to another Harbor instance, if the image is signed, the signature information in notary will not be replicated.

Due to some fundamental design of notary when the hostname of registry is changed the image has to be re-signed, but it can't be done at server-side because the keys are stored offline.  Docker is working to solve this issue.  So this is a limitation.

**Comment by stuclem** [comment] 2017-05-02 14:47
@reasonerjt I only just saw this. Belatedly added the issue to the release notes. Removing kind/note tag.

**Comment by saarktim** [comment] 2019-09-25 06:29
Does this issue still affect to the latest version of Notary?

**Comment by xaleeks** [comment] 2020-11-19 04:53
dupe of https://github.com/goharbor/harbor/issues/8303

**Closed by xaleeks** 2020-11-19 04:53 UTC
Labels: backlog, kind/limitation
