### ISSUE TITLE
Cannot replicate images from the Harbor when current auth_mode is OIDC

### ISSUE THREAD

**Issue by stonezdj** [goharbor/harbor#10217] opened 2019-12-10 06:35 UTC
It seems that only the admin user can be used to replicate image but it is unsafe and not allowed.
robot account can not replicate image and the cli/token of the OIDC user only used for cli login.

**Comment by reasonerjt** [comment] 2019-12-10 07:30
@stonezdj What is the requirement?  Does the user want to replicate using a real user or robot account or he simple does not care?

**Comment by stonezdj** [comment] 2019-12-13 12:26
He prefer to use robot account.

**Comment by reasonerjt** [comment] 2019-12-16 12:24
root cause is for replication now the client has to call Harbor's API for list and create project, neither OIDC CLI secret nor robot account can call API.

Maybe we want to add this capability to robot account.

**Comment by xaleeks** [comment] 2020-04-18 14:27
we should try to address this in 2.1, no reason it shouldn't be supported..

**Comment by reasonerjt** [comment] 2020-09-16 12:21
Closing since it has been fixed in v2.1

**Closed by reasonerjt** 2020-09-16 12:21 UTC
Labels: candidate/2.2.0, kind/limitation, kind/requirement
