### ISSUE TITLE
TLS handshake error from 127.0.0.1:44842: tls: client didn't provide a certificate

### ISSUE THREAD

**Issue by renmaosheng** [goharbor/harbor#11509] opened 2020-04-08 07:14 UTC
testing the tsl certs configuration by doing a replication operation, in the jobservice log:
```
Apr  7 23:59:16 172.20.0.1 jobservice[1660]: 2020/04/08 06:59:16 http: TLS handshake error from 127.0.0.1:44842: tls: client didn't provide a certificate
Apr  7 23:59:47 172.20.0.1 jobservice[1660]: 2020/04/08 06:59:47 http: TLS handshake error from 127.0.0.1:44890: tls: client didn't provide a certificate
Apr  8 00:00:17 172.20.0.1 jobservice[1660]: 2020/04/08 07:00:17 http: TLS handshake error from 127.0.0.1:44936: tls: client didn't provide a certificate
Apr  8 00:00:47 172.20.0.1 jobservice[1660]: 2020/04/08 07:00:47 http: TLS handshake error from 127.0.0.1:44982: tls: client didn't provide a certificate
Apr  8 00:01:18 172.20.0.1 jobservice[1660]: 2020/04/08 07:01:18 http: TLS handshake error from 127.0.0.1:45028: tls: client didn't provide a certificate
Apr  8 00:01:48 172.20.0.1 jobservice[1660]: 2020/04/08 07:01:48 http: TLS handshake error from 127.0.0.1:45076: tls: client didn't provide a certificate
Apr  8 00:02:18 172.20.0.1 jobservice[1660]: 2020/04/08 07:02:18 http: TLS handshake error from 127.0.0.1:45122: tls: client didn't provide a certificate
Apr  8 00:02:48 172.20.0.1 jobservice[1660]: 2020/04/08 07:02:48 http: TLS handshake error from 127.0.0.1:45168: tls: client didn't provide a certificate
Apr  8 00:03:19 172.20.0.1 jobservice[1660]: 2020/04/08 07:03:19 http: TLS handshake error from 127.0.0.1:45220: tls: client didn't provide a certificate
Apr  8 00:03:49 172.20.0.1 jobservice[1660]: 2020/04/08 07:03:49 http: TLS handshake error from 127.0.0.1:45266: tls: client didn't provide a certificate
Apr  8 00:04:19 172.20.0.1 jobservice[1660]: 2020/04/08 07:04:19 http: TLS handshake error from 127.0.0.1:45316: tls: client didn't provide a certificate
Apr  8 00:04:50 172.20.0.1 jobservice[1660]: 2020/04/08 07:04:50 http: TLS handshake error from 127.0.0.1:45362: tls: client didn't provide a certificate
Apr  8 00:05:20 172.20.0.1 jobservice[1660]: 2020/04/08 07:05:20 http: TLS handshake error from 127.0.0.1:45408: tls: client didn't provide a certificate
Apr  8 00:05:50 172.20.0.1 jobservice[1660]: 2020/04/08 07:05:50 http: TLS handshake error from 127.0.0.1:45454: tls: client didn't provide a certificate
Apr  8 00:06:21 172.20.0.1 jobservice[1660]: 2020/04/08 07:06:21 http: TLS handshake error from 127.0.0.1:45500: tls: client didn't provide a certificate
Apr  8 00:06:51 172.20.0.1 jobservice[1660]: 2020/04/08 07:06:51 http: TLS handshake error from 127.0.0.1:45546: tls: client didn't provide a certificate
Apr  8 00:07:21 172.20.0.1 jobservice[1660]: 2020/04/08 07:07:21 http: TLS handshake error from 127.0.0.1:45592: tls: client didn't provide a certificate
Apr  8 00:07:52 172.20.0.1 jobservice[1660]: 2020/04/08 07:07:52 http: TLS handshake error from 127.0.0.1:45644: tls: client didn't provide a certificate
Apr  8 00:08:22 172.20.0.1 jobservice[1660]: 2020/04/08 07:08:22 http: TLS handshake error from 127.0.0.1:45690: tls: client didn't provide a certificate
```
seems current certs are generated with container name, but we are querying 127.0.0.1 ip address. This is a regression from last testing cycle, we must fix this.

**Comment by renmaosheng** [comment] 2020-04-08 07:15
I noticed wenkai has some fix related to hairpin mode, not sure if this is related. thanks.

**Comment by ninjadq** [comment] 2020-04-08 07:29
generated cert only signed Core's domain name. But on some occasions, the core's URL will replaced by 127.0.0.1. we need to add this to SAN's IP field.

**Comment by ywk253100** [comment] 2020-04-08 09:41
The error `http: TLS handshake error from 127.0.0.1:44842: tls: client didn't provide a certificate` isn't related with replication and hairpin mode.
It's caused by the health check defined in Dockerfile `HEALTHCHECK CMD curl --fail -s http://127.0.0.1:8080/api/v1/stats || curl -k --fail -s https://127.0.0.1:8443/api/v1/stats || exit 1`

The certificate should be added to the curl command when mTLS is enabled.

**Comment by ywk253100** [comment] 2020-04-08 09:42
Open another issue https://github.com/goharbor/harbor/issues/11521 to track the hairpin fix for mTLS

**Comment by ywk253100** [comment] 2020-04-08 09:44
@ninjadq We should go through other components to make sure they don't have the same issue

**Comment by reasonerjt** [comment] 2020-04-09 14:07
@renmaosheng 
You enabled mTLS?

We can leverage `--cacert`

**Comment by ninjadq** [comment] 2020-04-10 06:28
fixed in https://github.com/goharbor/harbor/pull/11553

**Closed by ninjadq** 2020-04-10 06:28 UTC
Labels: target/2.0.0, target/RC
