### ISSUE TITLE
1.6 升级到 1.8 采用 installer安装后的chartrepo仓库应用无法部署

### ISSUE THREAD

**Issue by fengshunli** [goharbor/harbor#7960] opened 2019-06-03 09:14 UTC
启动之前修改harbor.yml 中的 absolute_url 为 enabled 了
![image](https://user-images.githubusercontent.com/18587688/58790330-c6925680-8622-11e9-9e60-3c8837e762e5.png)
部署迁移过来的仓库,无法启动
![image](https://user-images.githubusercontent.com/18587688/58790420-f2154100-8622-11e9-830f-ff9d2e6fe52e.png)
报错提示如下
![image](https://user-images.githubusercontent.com/18587688/58790561-37d20980-8623-11e9-99e4-98617a3ad0e7.png)

新创建的项目,然后在上传到新创建的项目里面,重新添加新项目的chartrepo是可以部署成功的

**Comment by heww** [comment] 2019-06-12 10:02
This problem was caused by the cache of the chartmuseum. After change to set `CHART_URL` using absolute url, the cache of `index.yaml` also exist.

**Comment by reasonerjt** [comment] 2019-08-21 09:20
We have added the parm in `harbor.yml`, it's targeting 1.9. closing.

**Closed by reasonerjt** 2019-08-21 09:20 UTC
Labels: area/helm-chart-repo, kind/bug
