### ISSUE TITLE
docker proxy cache not working

### ISSUE THREAD

**Issue by navidkhalilian** [goharbor/harbor#17730] opened 2022-11-01 18:54 UTC
We can pull node images from proxy project by this command:
docker pull registry/proxypackage/library/node:latest

but for image that's used multipart name not worked.
for example below command not working 
 sudo docker pull registry/proxypackage/library/**mcr.microsoft.com/dotnet/sdk:6.0**

Error:
Error response from daemon: unknown: repository proxypackage/library/mcr.microsoft.com/dotnet/sdk not found

**Comment by stonezdj** [comment] 2022-11-02 02:56
`registry/proxypackage/library/mcr.microsoft.com/dotnet/sdk:6.0` is not a valid repository in proxy cache, please read the document https://goharbor.io/docs/2.4.0/administration/configure-proxy-cache/.
`mcr.microsoft.com` is not a supported registry type for proxy cache, but you could select the docker registry with empty username password.

**Comment by rrgadeev** [comment] 2022-11-03 07:58
add docker.io Endpoint
Provider Docker Hub
add proxy project docker.io

docker pull registry/docker.io/library/node:latest - work
docker pull registry/docker.io/bitnami/pgbouncer:latest  - work

add mcr.microsoft.com Endpoint
Endpoint URL: https://mcr.microsoft.com
name:mcr.microsoft
Provider Azure ACR

add proxy project
mcr.microsoft.com 
docker pull registry/mcr.microsoft.com/dotnet/sdk:6.0 - work

**Comment by rrgadeev** [comment] 2022-11-03 08:18
https://mcr.microsoft.com/v2/dotnet/sdk/tags/list
to make it clear

**Comment by navidkhalilian** [comment] 2022-11-03 09:37
> 

This worked for me.
Thanks

**Comment by navidkhalilian** [comment] 2022-11-05 14:08
Hi everybody.
Sometimes the registry goes into an unhealthy state and causes the image not to be received. What is the problem?
![1](https://user-images.githubusercontent.com/69416447/200123868-eeaa6622-6bb4-4570-b39a-c906f2fefe30.png)
![Untitled](https://user-images.githubusercontent.com/69416447/200123871-d20603e9-6491-4426-aca2-14cf1933f18b.png)

**Comment by rrgadeev** [comment] 2022-11-07 07:25
Maybe the problem is that between you and https://mcr.microsoft.com , there are network errors.
You need to set up availability monitoring mcr.microsoft.com . You should consider a proxy server if there are network issues.

**Comment by zyyw** [comment] 2022-11-07 08:10
This might be due to the network issue, closing it now. Please check the core.log when it becomes unhealthy.

**Closed by zyyw** 2022-11-07 08:10 UTC
Labels: area/proxy-cache
