### ISSUE TITLE
Large amount of storage usage, GC fails

### ISSUE THREAD

**Issue by ssmall** [goharbor/harbor#15991] opened 2021-11-11 04:53 UTC
If you are reporting a problem, please make sure the following information are provided:

**Expected behavior and actual behavior:**

Projects index shows `Storage used: 13.90GiB`
Sum of storage used across individuals projects is `2.467 GiB`

When manually running GC with `Allow garbage collection on untagged artifacts` checked, I see the following stack trace in the jobservice log. Full GC log is attached.

```
panic(0x28041a0, 0x2e1a990)
	/usr/local/go/src/runtime/panic.go:975 +0x47a
math/rand.(*Rand).Int63n(0xc000196180, 0x8000000000000000, 0x4240000000000000)
	/usr/local/go/src/math/rand/rand.go:111 +0x11d
math/rand.Int63n(...)
	/usr/local/go/src/math/rand/rand.go:327
github.com/goharbor/harbor/src/lib.getBackoff(0x25, 0x5f5e100, 0x3b9aca00, 0xec8a01, 0x3b9aca00)
	/harbor/src/lib/retry.go:121 +0xc5
github.com/goharbor/harbor/src/lib.RetryUntil(0xc0006bd2f0, 0xc0006bd290, 0x1, 0x1, 0x1, 0x1)
	/harbor/src/lib/retry.go:102 +0x147
github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).sweep(0xc000d9e510, 0x2eb4460, 0xc0003da0f0, 0x0, 0x0)
	/harbor/src/jobservice/job/impl/gc/garbage_collection.go:302 +0x834
github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).Run(0xc000d9e510, 0x2eb4460, 0xc0003da0f0, 0xc000
2021-11-11T04:41:05Z [ERROR] [/jobservice/runner/redis.go:113]: Job 'GARBAGE_COLLECTION:90eaafce8f0f11690a722f97' exit with error: runtime error: invalid argument to Int63n; stack: goroutine 130 [running]:
github.com/goharbor/harbor/src/jobservice/runner.(*RedisJob).Run.func2(0xc0006bd7d0, 0xc000d20000)
	/harbor/src/jobservice/runner/redis.go:150 +0xa5
panic(0x28041a0, 0x2e1a990)
	/usr/local/go/src/runtime/panic.go:975 +0x47a
math/rand.(*Rand).Int63n(0xc000196180, 0x8000000000000000, 0x4240000000000000)
	/usr/local/go/src/math/rand/rand.go:111 +0x11d
math/rand.Int63n(...)
	/usr/local/go/src/math/rand/rand.go:327
github.com/goharbor/harbor/src/lib.getBackoff(0x25, 0x5f5e100, 0x3b9aca00, 0xec8a01, 0x3b9aca00)
	/harbor/src/lib/retry.go:121 +0xc5
github.com/goharbor/harbor/src/lib.RetryUntil(0xc0006bd2f0, 0xc0006bd290, 0x1, 0x1, 0x1, 0x1)
	/harbor/src/lib/retry.go:102 +0x147
github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).sweep(0xc000d9e510, 0x2eb4460, 0xc0003da0f0, 0x0, 0x0)
	/harbor/src/jobservice/job/impl/gc/garbage_collection.go:302 +0x834
github.com/goharbor/harbor/src/jobservice/job/impl/gc.(*GarbageCollector).Run(0xc000d9e510, 0x2eb4460, 0xc0003da0f0, 0xc000
```

Subsequent attempts to run GC succeed but show that nothing is eligible to be garbage collected.

**Steps to reproduce the problem:**

Unclear what steps are needed to reproduce aside from running GC

**Versions:**
Please specify the versions of following systems.

- harbor version: 2.3.2
- docker engine version: N/A
- docker-compose version: N/A

**Additional context:**

Deployed to k3s cluster using official Helm chart

- **Harbor config files:** You can get them by packaging `harbor.yml` and files in the same directory, including subdirectory.
- **Log files:** 
[GC.log](https://github.com/goharbor/harbor/files/7517821/GC.log)

**Comment by wy65701436** [comment] 2021-11-11 07:46
The panic was caused the retry func, and it was fixed in v2.3.3. 

However, the GC failure was caused by the backend storage deletion, can you search the registry.log for more details? It seems that the blob ha256:136482bf81d1fa351b424ebb8c7e34d15f2c5ed3fc0b66b544b8312bda3d52d9 cannot be removed within one minute?

**Comment by ssmall** [comment] 2021-11-11 08:04
Unfortunately I don't have the registry logs anymore -- the Kubernetes pod restarted a while ago.

**Comment by wy65701436** [comment] 2022-02-11 09:48
You can upgrade to latest build to have try, the incoming build v2.4.2 or v2.5 but include retry panic fix and skip deletion failure. Reopen it if you still encounter any problem after try.

**Closed by wy65701436** 2022-02-11 09:48 UTC
Labels: pending-for-more-info, area/gc
