### ISSUE TITLE
1.8.2 to 1.9.0  KeyError: 'webhook_job_max_retry'

### ISSUE THREAD

**Issue by Poil** [goharbor/harbor#9156] opened 2019-09-19 11:39 UTC
Hi,

I think something is missing in the upgrade process/documentation about new configuration
With not write `notification_config.get('webhook_job_max_retry', 'default value')` to avoid these problems ?

```
[Step 2]: preparing environment ...
prepare base dir is set to /opt/harbor
Clearing the configuration file: /config/registry/root.crt
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 32, in main
    config_dict = parse_yaml_config(conf, with_notary=with_notary, with_clair=with_clair, with_chartmuseum=with_chartmuseum)
  File "/usr/src/app/utils/configs.py", line 207, in parse_yaml_config
    config_dict['notification_webhook_job_max_retry'] = notification_config["webhook_job_max_retry"]
```

**Comment by Poil** [comment] 2019-09-19 11:57
If I add this value in my harbor.yml another one

```
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 61, in main
    prepare_docker_compose(config_dict, with_clair, with_notary, with_chartmuseum)
  File "/usr/src/app/utils/docker_compose.py", line 27, in prepare_docker_compose
    'log_location': configs['log_location'],
KeyError: 'log_location'
```

**Comment by ninjadq** [comment] 2019-09-19 12:05
Did you run migrator script before start harbor 1.9?

**Comment by Poil** [comment] 2019-09-19 12:09
There is nothing in the upgrade guide about a migrator script if you are already in harbor.yml (not in cfg) ?

**Comment by Poil** [comment] 2019-09-19 12:22
I don't find anyway to upgrade the configuration from harbor.yml 1.8.0 to 1.9.0 with the harbor-migrator
So I patch the config file by using https://github.com/goharbor/harbor/blob/master/tools/migration/cfg/migrator_1_9_0/harbor.yml.jinja

**Comment by Poil** [comment] 2019-09-19 12:28
After that LDAP auth is no more working 

```
==> /var/log/harbor/core.log <==
Sep 19 14:28:05 172.18.0.1 core[1112]: 2019-09-19T12:28:05Z [WARNING] [/core/auth/ldap/ldap.go:65]: ldap search fail: LDAP Result Code 12 "Unavailable Critical Extension": Bad search filter
Sep 19 14:28:05 172.18.0.1 core[1112]: 2019-09-19T12:28:05Z [ERROR] [/core/controllers/base.go:107]: Error occurred in UserLogin: LDAP Result Code 12 "Unavailable Critical Extension": Bad search filter
```

**Comment by Poil** [comment] 2019-09-19 12:56
I have no LDAP filter

**Comment by Poil** [comment] 2019-09-19 13:24
I've rollback to 1.8.x

**Comment by zhaowencheng1991** [comment] 2019-09-20 08:41
我 也遇到了同样的问题。    目前暂时没有解决

**Comment by reasonerjt** [comment] 2019-09-20 08:54
@Poil 
https://github.com/goharbor/harbor/blob/master/docs/migration_guide.md
```
ocker run -it --rm -v ${harbor_cfg}:/harbor-migration/harbor-cfg/harbor.yml -v ${harbor_yml}:/harb
```

**Comment by reasonerjt** [comment] 2019-09-20 08:57
cc @stuclem 

Could you please help us refine the doc to clarify?  @ninjadq and @xaleeks can help you get more background and details.

**Comment by synth3tk** [comment] 2019-09-21 02:04
Here's how I got it running as a workaround. First, added this to `harbor.yml`:
```
notification:
  webhook_job_max_retry: 10

chart:
  absolute_url: disabled
```

Then ran:

```
docker run -it --rm -v ${harbor_cfg}:/harbor-migration/harbor-cfg/harbor.yml -v ${harbor_yml}:/harbor-migration/harbor-cfg-out/harbor.yml goharbor/harbor-migrator:[tag] --cfg up
```

After that I could run the `install.sh`.

**Comment by stuclem** [comment] 2019-09-23 09:07
Since this is a doc bug, I'll assigning it to myself.

**Closed** 2019-09-24 09:16 UTC
Labels: area/doc, area/upgrade, kind/question, target/1.9.0

**Comment by mxplusb** [comment] 2019-10-31 13:25
I can confirm this issue still exists with v1.8.1 -> v1.9.1, following instructions.
