### ISSUE TITLE
Harbor deployment failed in an rare occasion

### ISSUE THREAD

**Issue by danfengliu** [goharbor/harbor#10343] opened 2019-12-26 03:19 UTC
![image](https://user-images.githubusercontent.com/44018302/71455470-207d8800-27d0-11ea-93ab-3545f13c121b.png)

**Comment by ninjadq** [comment] 2019-12-26 05:19
it seems like `goharbor/prepare:dev` is not included in offline package

**Comment by danfengliu** [comment] 2019-12-26 06:35
![image](https://user-images.githubusercontent.com/44018302/71462036-fdad9c80-27ec-11ea-9569-2f577c2887bb.png)

**Comment by ninjadq** [comment] 2019-12-26 07:10
Close this because that I think these two issues are not caused by Harbor.

**Closed by ninjadq** 2019-12-26 07:10 UTC
Labels: area/deployment, target/2.0.0
