### ISSUE TITLE
upgrade doc is between unclear and bugged

### ISSUE THREAD

**Issue by ptempier** [goharbor/harbor#18299] opened 2023-03-02 10:50 UTC
page :  https://goharbor.io/docs/2.7.0/administration/upgrade/

2)
mv harbor /my_backup_dir/harbor
should be 
cp -r --backup ./ ../harbor.bak

3)
separate database backup = useless 

4)
do i actually need that step at all , when i could just docker pull ? 
or do like at step 5, say it s optional

5)
ok

6)
i am not sure why i need to cp the old version
my understanding is that harbor.yml is upgraded in place

7)
ok

**Comment by ptempier** [comment] 2023-05-05 17:48
ping as  AllForNothing added the needs/follow-up label on Mar 6

**Comment by MinerYang** [comment] 2023-05-10 12:42
Hi @lumpidu ,
Thanks for your reply and what the exact python exceptions that are thrown out while you migrate from 2.6.X to 2.7.X?

**Comment by MinerYang** [comment] 2023-05-16 13:42
Hi @lumpidu .
I can not reproduce the expect situation as you described. I would like to close this issue due to we have different topic . Feel free to open another issue and describe the exact steps when you encounter the migrate config yaml issue.

Hi @ptempier,
Will close this issue now , feel free to reopen it if still have further discussion on this topic. 

Appreciate !

**Closed by MinerYang** 2023-05-16 13:42 UTC
Labels: area/doc, needs/follow-up
