### ISSUE TITLE
Unable to push images to S3 backed Harbor (v.2.8.0)

### ISSUE THREAD

**Issue by patbartsch** [goharbor/harbor#18653] opened 2023-05-08 11:27 UTC
Hi all,

we are having trouble pushing images to a S3 storage backed harbor (v2.8.0-89ef156d).

As a S3 endpoint we are using VMware OSE 2.2.1-21443372 backed by a Cloudian S3 storage (7.4.2.1).

# **Error**

Pushing the images always fail with the following error:

docker push 10.0.100.16/harbor-280/hello-world:latest
The push refers to repository [10.0.100.16/harbor-280/hello-world]
e07ee1baac5f: Pushing [==================================================>]  14.85kB
received unexpected HTTP status: 500 Internal Server Error
 
# **Logs**

The "goharbor/registry-photon:v2.8.0" container shows the following logs:

time="2023-05-08T09:55:40.321331286Z" level=debug msg="authorizing request" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=a8aaebae-e948-4c4d-8854-70ba6d514482 http.request.method=POST http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" vars.name="harbor-280/hello-world"
time="2023-05-08T09:55:40.323269218Z" level=info msg="authorized request" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=a8aaebae-e948-4c4d-8854-70ba6d514482 http.request.method=POST http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" vars.name="harbor-280/hello-world"
time="2023-05-08T09:55:40.323319177Z" level=debug msg="(*linkedBlobStore).Writer" auth.user.name="harbor_registry_user" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=a8aaebae-e948-4c4d-8854-70ba6d514482 http.request.method=POST http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" vars.name="harbor-280/hello-world"
time="2023-05-08T09:55:40.345081058Z" level=debug msg="s3aws.PutContent("/docker/registry/v2/repositories/harbor-280/hello-world/_uploads/f8e97606-d636-4b40-8af9-3b50b72c3228/startedat")" auth.user.name="harbor_registry_user" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=a8aaebae-e948-4c4d-8854-70ba6d514482 http.request.method=POST http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" trace.duration=21.727165ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).PutContent" trace.id=89631023-6ebe-4e73-a213-0de9bec45049 trace.line=110 vars.name="harbor-280/hello-world"
time="2023-05-08T09:55:40.357565839Z" level=debug msg="s3aws.Writer("/docker/registry/v2/repositories/harbor-280/hello-world/_uploads/f8e97606-d636-4b40-8af9-3b50b72c3228/data", false)" auth.user.name="harbor_registry_user" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=a8aaebae-e948-4c4d-8854-70ba6d514482 http.request.method=POST http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" trace.duration=12.445752ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Writer" trace.id=fd88f59f-474e-43f3-bf52-be603929dde8 trace.line=142 vars.name="harbor-280/hello-world"
time="2023-05-08T09:55:40.370653354Z" level=debug msg="s3aws.PutContent("/docker/registry/v2/repositories/harbor-280/hello-world/_uploads/f8e97606-d636-4b40-8af9-3b50b72c3228/hashstates/sha256/0")" auth.user.name="harbor_registry_user" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=a8aaebae-e948-4c4d-8854-70ba6d514482 http.request.method=POST http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" trace.duration=13.016317ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).PutContent" trace.id=ae3818f5-48b3-4775-ab01-49624997d4b5 trace.line=110 vars.name="harbor-280/hello-world"
time="2023-05-08T09:55:40.37074816Z" level=info msg="response completed" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=a8aaebae-e948-4c4d-8854-70ba6d514482 http.request.method=POST http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" http.response.duration=50.209231ms http.response.status=202 http.response.written=0
172.18.0.9 - - [08/May/2023:09:55:40 +0000] "POST /v2/harbor-280/hello-world/blobs/uploads/ HTTP/1.1" 202 0 "" "docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \\(linux\\))"
time="2023-05-08T09:55:40.386247381Z" level=debug msg="authorizing request" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=60ae9ebe-2696-498a-a656-3354a8e9cb71 http.request.method=PATCH http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=6XpLQVQgVHG8oNnQqbc9YUP6mpchyL6TarzGmjjRvXx7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MC4zMjMzMzE2MjRaIn0%3D" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" vars.name="harbor-280/hello-world" vars.uuid=f8e97606-d636-4b40-8af9-3b50b72c3228
time="2023-05-08T09:55:40.388210918Z" level=info msg="authorized request" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=60ae9ebe-2696-498a-a656-3354a8e9cb71 http.request.method=PATCH http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=6XpLQVQgVHG8oNnQqbc9YUP6mpchyL6TarzGmjjRvXx7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MC4zMjMzMzE2MjRaIn0%3D" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" vars.name="harbor-280/hello-world" vars.uuid=f8e97606-d636-4b40-8af9-3b50b72c3228
time="2023-05-08T09:55:40.388269434Z" level=debug msg="(*linkedBlobStore).Resume" auth.user.name="harbor_registry_user" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=60ae9ebe-2696-498a-a656-3354a8e9cb71 http.request.method=PATCH http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=6XpLQVQgVHG8oNnQqbc9YUP6mpchyL6TarzGmjjRvXx7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MC4zMjMzMzE2MjRaIn0%3D" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" vars.name="harbor-280/hello-world" vars.uuid=f8e97606-d636-4b40-8af9-3b50b72c3228
time="2023-05-08T09:55:40.411964434Z" level=debug msg="s3aws.GetContent("/docker/registry/v2/repositories/harbor-280/hello-world/_uploads/f8e97606-d636-4b40-8af9-3b50b72c3228/startedat")" auth.user.name="harbor_registry_user" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=60ae9ebe-2696-498a-a656-3354a8e9cb71 http.request.method=PATCH http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=6XpLQVQgVHG8oNnQqbc9YUP6mpchyL6TarzGmjjRvXx7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MC4zMjMzMzE2MjRaIn0%3D" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" trace.duration=23.670288ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=063b4092-67da-4c17-a57b-cd121a21da86 trace.line=95 vars.name="harbor-280/hello-world" vars.uuid=f8e97606-d636-4b40-8af9-3b50b72c3228
time="2023-05-08T09:55:40.436374792Z" level=debug msg="s3aws.Writer("/docker/registry/v2/repositories/harbor-280/hello-world/_uploads/f8e97606-d636-4b40-8af9-3b50b72c3228/data", true)" auth.user.name="harbor_registry_user" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=60ae9ebe-2696-498a-a656-3354a8e9cb71 http.request.method=PATCH http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=6XpLQVQgVHG8oNnQqbc9YUP6mpchyL6TarzGmjjRvXx7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MC4zMjMzMzE2MjRaIn0%3D" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" trace.duration=24.376653ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Writer" trace.id=f3ae69e8-3205-42f9-ad3f-e2bf68486a32 trace.line=142 vars.name="harbor-280/hello-world" vars.uuid=f8e97606-d636-4b40-8af9-3b50b72c3228
time="2023-05-08T09:55:40.449927859Z" level=debug msg="s3aws.PutContent("/docker/registry/v2/repositories/harbor-280/hello-world/_uploads/f8e97606-d636-4b40-8af9-3b50b72c3228/hashstates/sha256/2479")" auth.user.name="harbor_registry_user" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=60ae9ebe-2696-498a-a656-3354a8e9cb71 http.request.method=PATCH http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=6XpLQVQgVHG8oNnQqbc9YUP6mpchyL6TarzGmjjRvXx7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MC4zMjMzMzE2MjRaIn0%3D" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" trace.duration=13.476755ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).PutContent" trace.id=0d55bf4b-1271-4259-91eb-d1e94b388467 trace.line=110 vars.name="harbor-280/hello-world" vars.uuid=f8e97606-d636-4b40-8af9-3b50b72c3228
172.18.0.9 - - [08/May/2023:09:55:40 +0000] "PATCH /v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=6XpLQVQgVHG8oNnQqbc9YUP6mpchyL6TarzGmjjRvXx7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MC4zMjMzMzE2MjRaIn0%3D HTTP/1.1" 202 0 "" "docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \\(linux\\))"
time="2023-05-08T09:55:40.477716542Z" level=debug msg="s3aws.PutContent("/docker/registry/v2/repositories/harbor-280/hello-world/_uploads/f8e97606-d636-4b40-8af9-3b50b72c3228/hashstates/sha256/2479")" auth.user.name="harbor_registry_user" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=60ae9ebe-2696-498a-a656-3354a8e9cb71 http.request.method=PATCH http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=6XpLQVQgVHG8oNnQqbc9YUP6mpchyL6TarzGmjjRvXx7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MC4zMjMzMzE2MjRaIn0%3D" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" trace.duration=12.913192ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).PutContent" trace.id=2b7ee61b-d964-4120-b168-8a2ca8a460d2 trace.line=110 vars.name="harbor-280/hello-world" vars.uuid=f8e97606-d636-4b40-8af9-3b50b72c3228
time="2023-05-08T09:55:40.477742727Z" level=info msg="response completed" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=60ae9ebe-2696-498a-a656-3354a8e9cb71 http.request.method=PATCH http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=6XpLQVQgVHG8oNnQqbc9YUP6mpchyL6TarzGmjjRvXx7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MC4zMjMzMzE2MjRaIn0%3D" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" http.response.duration=93.00325ms http.response.status=202 http.response.written=0
time="2023-05-08T09:55:40.490244535Z" level=debug msg="authorizing request" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=dc31f69f-b885-4b47-972c-f3492a7be2b9 http.request.method=PUT http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=zwb986tOIF5JPHsPK3HfUowRhg7HT-Y5-9s2HVEbYmN7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MjQ3OSwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MFoifQ%3D%3D&digest=sha256%3A2db29710123e3e53a794f2694094b9b4338aa9ee5c40b930cb8063a1be392c54" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" vars.name="harbor-280/hello-world" vars.uuid=f8e97606-d636-4b40-8af9-3b50b72c3228
time="2023-05-08T09:55:40.492370846Z" level=info msg="authorized request" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=dc31f69f-b885-4b47-972c-f3492a7be2b9 http.request.method=PUT http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=zwb986tOIF5JPHsPK3HfUowRhg7HT-Y5-9s2HVEbYmN7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MjQ3OSwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MFoifQ%3D%3D&digest=sha256%3A2db29710123e3e53a794f2694094b9b4338aa9ee5c40b930cb8063a1be392c54" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" vars.name="harbor-280/hello-world" vars.uuid=f8e97606-d636-4b40-8af9-3b50b72c3228
time="2023-05-08T09:55:40.492431776Z" level=debug msg="(*linkedBlobStore).Resume" auth.user.name="harbor_registry_user" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=dc31f69f-b885-4b47-972c-f3492a7be2b9 http.request.method=PUT http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=zwb986tOIF5JPHsPK3HfUowRhg7HT-Y5-9s2HVEbYmN7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MjQ3OSwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MFoifQ%3D%3D&digest=sha256%3A2db29710123e3e53a794f2694094b9b4338aa9ee5c40b930cb8063a1be392c54" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" vars.name="harbor-280/hello-world" vars.uuid=f8e97606-d636-4b40-8af9-3b50b72c3228
time="2023-05-08T09:55:40.506942797Z" level=debug msg="s3aws.GetContent("/docker/registry/v2/repositories/harbor-280/hello-world/_uploads/f8e97606-d636-4b40-8af9-3b50b72c3228/startedat")" auth.user.name="harbor_registry_user" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=dc31f69f-b885-4b47-972c-f3492a7be2b9 http.request.method=PUT http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=zwb986tOIF5JPHsPK3HfUowRhg7HT-Y5-9s2HVEbYmN7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MjQ3OSwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MFoifQ%3D%3D&digest=sha256%3A2db29710123e3e53a794f2694094b9b4338aa9ee5c40b930cb8063a1be392c54" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" trace.duration=14.454591ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).GetContent" trace.id=a5316691-661c-4830-838d-388e891e2630 trace.line=95 vars.name="harbor-280/hello-world" vars.uuid=f8e97606-d636-4b40-8af9-3b50b72c3228
172.18.0.9 - - [08/May/2023:09:55:40 +0000] "PUT /v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=zwb986tOIF5JPHsPK3HfUowRhg7HT-Y5-9s2HVEbYmN7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MjQ3OSwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MFoifQ%3D%3D&digest=sha256%3A2db29710123e3e53a794f2694094b9b4338aa9ee5c40b930cb8063a1be392c54 HTTP/1.1" 500 104 "" "docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \\(linux\\))"
time="2023-05-08T09:55:40.530413261Z" level=debug msg="s3aws.Writer("/docker/registry/v2/repositories/harbor-280/hello-world/_uploads/f8e97606-d636-4b40-8af9-3b50b72c3228/data", true)" auth.user.name="harbor_registry_user" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=dc31f69f-b885-4b47-972c-f3492a7be2b9 http.request.method=PUT http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=zwb986tOIF5JPHsPK3HfUowRhg7HT-Y5-9s2HVEbYmN7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MjQ3OSwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MFoifQ%3D%3D&digest=sha256%3A2db29710123e3e53a794f2694094b9b4338aa9ee5c40b930cb8063a1be392c54" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" trace.duration=23.43451ms trace.file="/go/src/github.com/docker/distribution/registry/storage/driver/base/base.go" trace.func="github.com/docker/distribution/registry/storage/driver/base.(*Base).Writer" trace.id=c770a743-9cdf-4ede-9d37-489638a169b4 trace.line=142 vars.name="harbor-280/hello-world" vars.uuid=f8e97606-d636-4b40-8af9-3b50b72c3228
time="2023-05-08T09:55:40.530439206Z" level=error msg="error resolving upload: s3aws: SerializationError: failed to decode REST XML response
caused by: parsing time "2023-05-08T09:55:40.981+00:00" as "2006-01-02T15:04:05Z": cannot parse "+00:00" as "Z"" auth.user.name="harbor_registry_user" go.version=go1.20.3 http.request.host=10.0.100.16 http.request.id=dc31f69f-b885-4b47-972c-f3492a7be2b9 http.request.method=PUT http.request.remoteaddr=10.0.100.16 http.request.uri="/v2/harbor-280/hello-world/blobs/uploads/f8e97606-d636-4b40-8af9-3b50b72c3228?_state=zwb986tOIF5JPHsPK3HfUowRhg7HT-Y5-9s2HVEbYmN7Ik5hbWUiOiJoYXJib3ItMjgwL2hlbGxvLXdvcmxkIiwiVVVJRCI6ImY4ZTk3NjA2LWQ2MzYtNGI0MC04YWY5LTNiNTBiNzJjMzIyOCIsIk9mZnNldCI6MjQ3OSwiU3RhcnRlZEF0IjoiMjAyMy0wNS0wOFQwOTo1NTo0MFoifQ%3D%3D&digest=sha256%3A2db29710123e3e53a794f2694094b9b4338aa9ee5c40b930cb8063a1be392c54" http.request.useragent="docker/23.0.4 go/go1.19.8 git-commit/cbce331 kernel/5.14.0-162.6.1.el9_1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/23.0.4 \(linux\))" vars.name="harbor-280/hello-world" vars.uuid=f8e97606-d636-4b40-8af9-3b50b72c3228
time="2023-05-08T09:55:40.530478456Z" level=error msg="response completed with error" auth.user.name="harbor_registry_user" err.code=unknown err.detail="s3aws: SerializationError: failed to decode REST XML response

Here also the harbor.yml file we used to install the harbor. 

[harbor.txt](https://github.com/goharbor/harbor/files/11420595/harbor.txt)

Is this a known issue or how can we fix that?

Thanks in advance!

**Comment by chlins** [comment] 2023-05-09 01:19
The registry throws the error `error resolving upload: s3aws: SerializationError: failed to decode REST XML response
caused by: parsing time "2023-05-08T09:55:40.981+00:00" as "2006-01-02T15:04:05Z": cannot parse "+00:00" as "Z"`, it seems the time format responded by s3 endpoint cannot be parsed by registry, could you check whether exist related configuration from s3 endpoint?

**Comment by patbartsch** [comment] 2023-05-09 11:36
I checked the NTP configuration on the Harbor VM as also on the S3 endpoint and both are synced and configured for the same timezone.

**Comment by stonezdj** [comment] 2023-05-11 09:15
Not sure registry support Cloudian S3 storage, you could try to setup a registry container in local and try to push image to it
see: https://github.com/distribution/distribution/blob/main/docs/deploying.md, if it doesn't work, Harbor doesn't support either.

**Comment by patbartsch** [comment] 2023-05-12 09:27
I tested Harbor now with local storage and an Amazon S3 Bucket and both are working, images can be pushed and pulled. Looks like the problem occures only when I use VMware OSE/Cloudian S3. Is there any chance that VMware OSE/Cloudian S3 will be supported by Harbor?

**Comment by chlins** [comment] 2023-05-15 08:05
The storage you used seems not standard S3 storage, please reach out to the S3 server for assistance.

**Closed by chlins** 2023-05-15 08:05 UTC

**Comment by vitality411** [comment] 2024-07-05 12:38
I have the same issue but was able to workaround by using Cloudian HyperStore directly as storage backend for Harbor registry instead of OSE.
