### ISSUE TITLE
No timestamp on logs in FF browser

### ISSUE THREAD

**Issue by CrazyMushu** [goharbor/harbor#12365] opened 2020-06-30 16:28 UTC
**Expected behavior and actual behavior:**

The log tab in the UI first loads for a very long time

![c474f905d6cfb3f7b8b3fcf9519f8431](https://user-images.githubusercontent.com/44494231/86151347-49783000-bb07-11ea-80bd-d8815a63b8d5.png)

and then does not show a timestamp

![695843ce5a246954194e4965000182b7](https://user-images.githubusercontent.com/44494231/86151396-585ee280-bb07-11ea-92d4-b7d5a3be12c0.png)

**Steps to reproduce the problem:**
Update from 1.10.2 to 2.0.0 and then 2.0.1
in version 1.10.2 there was a timestamp, in version 2.0.0 and 2.0.1 - it was already gone

**Versions:**

- harbor version: 2.0.1
- docker engine version: 19.03.12
- docker-compose version 1.25.5, build 8a1c60f6

**Comment by wy65701436** [comment] 2020-07-03 03:59
what brower are you using? Can you try with chrome？

**Comment by CrazyMushu** [comment] 2020-07-05 16:18
> 
> 
> what brower are you using? Can you try with chrome？

works in chrome!
![dd0b2e65d9fd881eaef52f5c4d45716a](https://user-images.githubusercontent.com/44494231/86536959-4bba0000-bef4-11ea-8008-357a2f08ee14.png)


in firefox does not work

**Comment by reasonerjt** [comment] 2020-07-06 08:10
The root cause is the timestamp can't be recognized in FF.

**Comment by wy65701436** [comment] 2020-07-07 08:34
I'll have a fix to make the timestamp can be recognized both in Chrome and FF. Hopefully, we can have it in the v2.1.0.

**Comment by wy65701436** [comment] 2020-07-31 07:42
close it as PR merged. https://github.com/goharbor/harbor/pull/12629

**Closed by wy65701436** 2020-07-31 07:42 UTC
Labels: candidate/2.1.0, kind/bug

**Comment by CrazyMushu** [comment] 2020-08-08 12:18
> 
> 
> close it as PR merged. #12629

Hello !
Sorry, problem is not resolved :(

**Comment by CrazyMushu** [comment] 2020-08-08 12:20
![8539f02a00a38a05e34b5b5d3bfb706b](https://user-images.githubusercontent.com/44494231/89710328-9f53b980-d98a-11ea-8eea-7fbc516e18f7.png)
