### ISSUE TITLE
admin login failed

### ISSUE THREAD

**Issue by Hokwang** [goharbor/harbor#10832] opened 2020-02-24 23:50 UTC
Hi,

I use admin account in Jenkins CI pipeline, sometimes docker login command failed, so I find out why this happened.

Here's jenkins output.
```
10:38:27  + echo ****
10:38:27  + docker login -u **** --password-stdin harbor.company.net
10:38:27  Error response from daemon: Get https://harbor.company.net/v2/: unauthorized: authentication required
```

I found that you have the code which is for locking account when it login failed in https://github.com/goharbor/harbor/issues/9429.
(but I don't know locking works how many failed and how long lock the account)

I search pod log and find admin login fail.
```
# k logs harbor-prod-harbor-core-6cfdcd5bf5-s4cns -n harbor-prod | grep "failed to authenticate admin" | tail
2020-02-19T07:24:16Z [ERROR] [/core/filter/security.go:430]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
2020-02-19T07:24:47Z [ERROR] [/core/filter/security.go:430]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
2020-02-19T07:28:37Z [ERROR] [/core/filter/security.go:430]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
2020-02-19T07:28:56Z [ERROR] [/core/filter/security.go:430]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
2020-02-19T07:30:26Z [ERROR] [/core/filter/security.go:430]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
2020-02-19T07:30:56Z [ERROR] [/core/filter/security.go:430]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
2020-02-19T07:37:46Z [ERROR] [/core/filter/security.go:430]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
2020-02-19T07:47:36Z [ERROR] [/core/filter/security.go:430]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
2020-02-19T07:49:29Z [ERROR] [/core/filter/security.go:430]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
2020-02-19T07:51:47Z [ERROR] [/core/filter/security.go:430]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
```

I don't know why admin login fails, cause no one, except me, will not know admin password.

I grep before and after to find out reason.
```
# k logs harbor-prod-harbor-core-6cfdcd5bf5-s4cns -n harbor-prod | grep -B3 -A3 "failed to authenticate admin" | tail -20
2020-02-24T23:32:36Z [ERROR] [/core/filter/security.go:430]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
2020/02/24 23:32:37 [D] [server.go:2774] |      127.0.0.1| 200 | 1.627553764s|   match| GET      /service/token   r:/service/token
2020/02/24 23:32:37 [D] [server.go:2774] |   10.244.2.189| 200 |   9.509607ms|   match| POST     /service/notifications   r:/service/notifications
2020/02/24 23:32:37 [D] [server.go:2774] |      127.0.0.1| 200 |  78.393487ms|   match| GET      /v2/se/swarm_at_sa/manifests/latest   r:/v2/*
--
2020/02/24 23:36:37 [D] [server.go:2774] |     10.244.2.1| 200 |  10.669165ms|   match| GET      /api/ping   r:/api/ping
2020/02/24 23:36:42 [D] [server.go:2774] |      127.0.0.1| 401 |   12.29183ms|   match| GET      /v2/   r:/v2/*
2020-02-24T23:36:42Z [ERROR] [/core/filter/security.go:244]: Failed to verify secret: user is not onboarded as OIDC user
2020-02-24T23:36:43Z [ERROR] [/core/filter/security.go:430]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
2020/02/24 23:36:46 [D] [server.go:2774] |     10.244.2.1| 200 |  11.216593ms|   match| GET      /api/ping   r:/api/ping
2020/02/24 23:36:47 [D] [server.go:2774] |     10.244.2.1| 200 |  11.265171ms|   match| GET      /api/ping   r:/api/ping
2020/02/24 23:36:51 [D] [server.go:2774] |      127.0.0.1| 200 |  15.207937ms|   match| GET      /v2/core_svr19a1/amf-aic/tags/list   r:/v2/*
--
2020/02/24 23:41:38 [D] [server.go:2774] |     10.244.2.1| 200 |  17.973302ms|   match| GET      /api/ping   r:/api/ping
2020/02/24 23:41:43 [D] [server.go:2774] |      127.0.0.1| 401 |  18.821842ms|   match| GET      /v2/   r:/v2/*
2020-02-24T23:41:43Z [ERROR] [/core/filter/security.go:244]: Failed to verify secret: user is not onboarded as OIDC user
2020-02-24T23:41:45Z [ERROR] [/core/filter/security.go:430]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
2020/02/24 23:41:46 [D] [server.go:2774] |     10.244.2.1| 200 |  13.547409ms|   match| GET      /api/ping   r:/api/ping
2020/02/24 23:41:47 [D] [server.go:2774] |      127.0.0.1| 401 |  18.085535ms|   match| GET      /v2/   r:/v2/*
2020-02-24T23:41:47Z [ERROR] [/core/filter/security.go:244]: Failed to verify secret: failed to refresh token
```

I can see `user is not onboarded as OIDC user` message.
I am using OIDC integration now.

**I doubt about OIDC integration and admin account. Please check this problem.**

**Versions:**
- harbor version: 1.10.0

Thanks,

**Comment by reasonerjt** [comment] 2020-04-10 16:31
@Hokwang 

When you mention that  you `sometimes` failed to login as admin,  do you mean sometimes it works and sometimes it doesn't?

**Comment by Hokwang** [comment] 2020-04-14 04:29
@reasonerjt 
Yes, I can not find "sometimes" is which condition, or when exactly..
Now, I create robot account for this Jenkins CI job, and will not use admin account if possible.

**Comment by xaleeks** [comment] 2020-05-27 10:32
@Hokwang Do you still need some help here?

**Comment by Hokwang** [comment] 2020-05-28 05:18
@xaleeks yes, 
from wrote this issue to now,
I create new kubernetes cluster, install postgresql externally, redis externally,
and install harbor 1.10.2 using helm, completely newly.

still I am so many errors in logs.
```
$ k get pod harbor-harbor-core-5b7b94779b-c92sw -n harbor-prod
NAME                                  READY   STATUS    RESTARTS   AGE
harbor-harbor-core-5b7b94779b-c92sw   1/1     Running   0          19d
$ k logs harbor-harbor-core-5b7b94779b-c92sw -n harbor-prod | grep "failed to authenticate admin" | wc -l
1733
```

and I experienced real problem in jenkins,
```
17:47:48  [Pipeline] withCredentials
17:47:48  Masking supported pattern matches of $DOCKER_USER or $DOCKER_PASSWORD
17:47:48  [Pipeline] {
17:47:48  [Pipeline] sh
17:47:49  + echo ****
17:47:49  + docker login -u **** --password-stdin my.company.harbor.net
17:47:49  Error response from daemon: Get https://my.company.harbor.net/v2/: unauthorized: authentication required
17:47:49  [Pipeline] }
```

**Comment by xaleeks** [comment] 2020-05-30 06:58
@ninjadq  @wy65701436  can you help take a look?

**Comment by wusphinx** [comment] 2020-06-10 08:17
I deployed harbor(v1.9.4) with helm and got the same error when I call the api in the core Pod  as below:
```
harbor [ /harbor ]$ curl http://127.0.0.1:8080/api/logs -uadmin
Enter host password for user 'admin':
{"code":401,"message":"Unauthorized"}
harbor [ /harbor ]$ curl http://127.0.0.1:8080/api/logs -uadmin
Enter host password for user 'admin':
{"code":401,"message":"Unauthorized"}
harbor [ /harbor ]$ curl http://127.0.0.1:8080/api/logs -uadmin
Enter host password for user 'admin':
{"code":401,"message":"Unauthorized"}
harbor [ /harbor ]$ curl http://127.0.0.1:8080/api/logs -uadmin
Enter host password for user 'admin':
[
  {
    "log_id": 2,
    "username": "admin",
    "project_id": 3,
    "repo_name": "system/",
    "repo_tag": "N/A",
    "guid": "",
    "operation": "create",
    "op_time": "2020-06-10T06:41:14.729956Z"
  },
  {
    "log_id": 1,
    "username": "admin",
    "project_id": 2,
    "repo_name": "default/",
    "repo_tag": "N/A",
    "guid": "",
    "operation": "create",
    "op_time": "2020-06-10T06:41:14.679558Z"
  }
]harbor [ /harbor ]$ 
```
the error is something like:
```
2020/06/10 08:11:03 [D] [server.go:2774] |      127.0.0.1| 401 |   2.402562ms|   match| GET      /api/logs   r:/api/logs
2020-06-10T08:11:03Z [ERROR] [/core/filter/security.go:434]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'
2020-06-10T08:11:03Z [DEBUG] [/core/filter/security.go:454]: can not get user information from session
2020-06-10T08:11:03Z [DEBUG] [/core/filter/security.go:509]: user information is nil
2020-06-10T08:11:03Z [DEBUG] [/core/filter/security.go:523]: using local database project manager
2020-06-10T08:11:03Z [DEBUG] [/core/filter/security.go:525]: creating local database security context...
2020-06-10T08:11:03Z [ERROR] [/common/api/base.go:73]: GET /api/replication/policies failed with error: {"code":401,"message":"UnAuthorized"}
```

**Comment by skandragon** [comment] 2020-07-10 23:53
I'm seeing this also on the Bitnami-based docker-compose.yml example:

https://github.com/bitnami/bitnami-docker-harbor-portal/issues/7

I know the password used is correct, as it can log into the UI.  I'm not using Kubernetes (yet...) but the error seems similar.

**Comment by xtreme-conor-nosal** [comment] 2020-07-28 14:54
Also seeing this on harbor 2.0.1 deployed via helm, with UAA auth integration. We have harbor-exporter configured with admin credentials, and various API calls (fetch repos, policies, executions, etc) will fail with a 401 1-3% of the time.

Core logs `[ERROR] [/server/middleware/security/basic_auth.go:41][requestID="502f1597-46d2-48c3-80ce-d5b9f4d7c453"]: failed to authenticate admin: Failed to authenticate user, due to error 'Invalid credentials'`

**Comment by reasonerjt** [comment] 2020-08-12 07:45
@xtreme-conor-nosal 
If this is constantly reproducible, could you turn the log level to debug by updating the environment variable of Harbor core?

To prevent brutal force attack to login Harbor will lock the user for a few seconds, if it failed to authenticate a user.

Is it possible another thread tried to login the same user with wrong password?

**Comment by xtreme-conor-nosal** [comment] 2020-08-12 14:42
We have various automation pipelines that authenticate with our registry, and one of them was misconfigured, so a temporary lockout is plausible. The pipeline in question only ran once every 20 minutes though. 

What is the threshold for a lockout to occur and how long does it last? Is there a specific log entry I can search for to verify?

**Comment by reasonerjt** [comment] 2020-09-23 05:32
@xtreme-conor-nosal 
Conor, there will be debug message like `Login failed, locking xxx....`:
https://github.com/goharbor/harbor/blob/b21f9dc6f10dec60597d7a279c1d5f4b999dcba7/src/core/auth/authenticator.go#L152

**Comment by reasonerjt** [comment] 2020-09-23 05:34
@skandragon 
We do not maintain the chart under `bitnami` please talk to the maintainer of the chart to help you debug.

**Comment by reasonerjt** [comment] 2020-09-23 05:34
I see there are different conversation happening in this issue

I'm closing this one, and if you still see the problem, please create a new issue.

**Closed by reasonerjt** 2020-09-23 05:34 UTC
Labels: area/oidc, area/robot-account
