### ISSUE TITLE
Allow robot accounts to be shared accoss multiple projects

### ISSUE THREAD

**Issue by finbourne-bot-public** [goharbor/harbor#10774] opened 2020-02-19 12:50 UTC
**Is your feature request related to a problem? Please describe.**
Motivation is that when building images sometimes mutiple projects are used. Since a robot account cannot be shared accross projects it is not possible to build an image from images in multiple projects using a robot account. Multiple projects are desired in order to have granular permissions.

**Describe the solution you'd like**
I would like a given robot account to be able to pull from and push to multiple projects.

**Describe the main design/architecture of your solution**
Either allow the token for a robot account to be specified on creation or else some mechanism in the project to add a robot account from another project.

**Describe the development plan you've considered**

**Additional context**

**Comment by renmaosheng** [comment] 2020-02-24 03:54
assign to alex to prioritize the requirement. thanks.

**Comment by xaleeks** [comment] 2020-03-01 01:24
@finbourne-bot-public  This is well understood and definitely in our backlog.  Docker builds are a multi stage process that often reach across several different projects so scoping robots out of projects is the best approach.  We will allow tying robot account to different projects and configure different levels of access to the projects.  This will most likely happen after our 2.0 release scheduled for mid April because it relies on the set of new APIs being worked on.

**Comment by Hokwang** [comment] 2020-03-17 01:42
@xaleeks I am really looking forward this feature. But I can't find this on the backlog, which one is that?

**Comment by xaleeks** [comment] 2020-03-19 01:13
@Hokwang I thought there was another one https://github.com/goharbor/harbor/issues/7867 , we can use this issue to track the requirement.

**Comment by sunlianqiang** [comment] 2020-04-03 09:53
@xaleeks also eager for this feature.

**Comment by xaleeks** [comment] 2020-04-08 07:21
This is impacted by design of https://github.com/goharbor/harbor/issues/10159, tackling in the 2.1 or 2.2 release

**Comment by Sharath52** [comment] 2020-05-05 15:41
@xaleeks any idea on when this will be released!? eagerly waiting for this update!

**Comment by kamal94** [comment] 2020-08-04 15:07
This is a critical feature for our workflow. Would greatly appreciate any expedition here. Thanks!

**Comment by rarick** [comment] 2020-08-10 21:55
👍 To this.

To give some context as to why this is critical for us:

We're using a gitlab runner to build images for several different projects. Access control is granted on a per-project basis, so I've separated my company's teams into different Harbor projects. 

This is an issue when it comes to gitlab runner, as the teams share gitlab runners. For this reason, I am in need of a robot account capable of uploading to all projects.

**Comment by xaleeks** [comment] 2020-10-25 06:55
system robot accounts coming in 2.2, proposal here https://github.com/goharbor/community/pull/148

project robots are still available to project admins

**Comment by bienkma** [comment] 2020-12-13 09:59
I'm still waiting this feature

**Comment by adamesg** [comment] 2021-01-26 16:06
Is this feature still slated for 2.2? The proposal linked above hasn't had any movement for a few months.

**Comment by wy65701436** [comment] 2021-02-02 06:55
We can close it as the system level robot is introduced in v2.2, just try with https://github.com/goharbor/harbor/releases/tag/v2.2.0-rc1.

**Closed by wy65701436** 2021-02-02 06:55 UTC
Labels: area/robot-account, backlog, kind/requirement
