### ISSUE TITLE
Allow user deletion in Harbor for LDAP backend

### ISSUE THREAD

**Issue by eroji** [goharbor/harbor#9167] opened 2019-09-20 00:27 UTC
Once you have LDAP authentication configured, when/if a user logs into Harbor, the user is populated in the Users section. There is no means of removing that user out of the Users section, even if the user is no longer valid on the LDAP server end. This should be strictly an operation to remove the user out of Harbor's database so it would be nice to have as general housekeeping.

**Comment by takyon77** [comment] 2019-09-20 14:52
I'm also interested to have this feature if possible.

**Comment by stonezdj** [comment] 2019-10-29 08:21
Please refer the wiki: https://github.com/goharbor/harbor/wiki/Harbor-FAQs#authentication

**Comment by xaleeks** [comment] 2019-11-11 09:48
How can Harbor know that user has been deleted from ldap server so it can do the housekeeping?  Deleted users from ldap will no longer be able to login to Harbor so I think it's ok. @eroji

**Comment by nathantran** [comment] 2020-05-08 20:34
I'm also interested in this feature, in addition to allowing renaming of the username.

We ran into an issue recently where a username got changed in LDAP because the person got married. But the username didn't get updated in Harbor. As such, the user couldn't log into Harbor with the new username, presumably because the uid assocaciated with the user already exists in harbor so it didn't attempt to create a new username. I guess because of the mismatched username, Harbor didn't allow the user to log in.

If we could delete the user from Harbor then maybe Harbor can try to import the user attributes again.

**Comment by xaleeks** [comment] 2020-05-29 19:19
this is essentially the same problem as https://github.com/goharbor/harbor/issues/8424.  Because you can have something like dex connecting to LDAP in the background, the crux of the problem is the existence of a user on LDAP is not shared with Harbor.  

We just reopened that ticket to discuss better resolution.  Please join the convo over there, I think we can close this

**Closed by xaleeks** 2020-05-29 19:19 UTC
Labels: kind/requirement
