### ISSUE TITLE
Change the domain name,but the original domain name is still in the web console "Pull Command"

### ISSUE THREAD

**Issue by Yeefoner** [goharbor/harbor#7659] opened 2019-05-07 02:55 UTC
Change the domain name,but the original domain name is still in the web console "Pull Command"
version:1.7.5

**Comment by jwangyangls** [comment] 2019-07-30 07:19
@reasonerjt  the original domain come from API ：   api/systeminfo, I think the problem is that the return data of this interface is not refreshed.

**Comment by reasonerjt** [comment] 2019-07-30 07:25
@Yeefoner please make sure you update the hostname in the configuration file rerun `prepare` and use `docker-compose` to restart Harbor.
The domain name will be populate to different components so rerun `prepare` is a must.

**Comment by reasonerjt** [comment] 2019-08-19 06:22
Closing this issue, please refer to my latest comment to make the update take effect.

**Closed by reasonerjt** 2019-08-19 06:22 UTC
Labels: area/ui

**Comment by MrAmbiG** [comment] 2020-09-29 11:52
The issue still persists @reasonerjt as of today
